### ISSUE TITLE
ToastrService/ToastrModule import cost is too much

### ISSUE THREAD

**Issue by hamidh2** [scttcper/ngx-toastr#1006]
Instead of the below imports that are extremely costly, we need to import them efficiently! 
```
import { ToastrService } from 'ngx-toastr';
import { ToastrModule } from 'ngx-toastr';
```
![image](https://github.com/scttcper/ngx-toastr/assets/41614055/492655ed-4be4-44fe-815c-61e05c42fcbf)

I tried to import as the below 
```
import { ToastrService } from 'ngx-toastr/toastr/toastr.service';

```
but I got an error! 

> Module not found: Error: Package path ./toastr/toastr.service is not exported from package C:\Projects\mbr_frontend\node_modules\ngx-toastr (see exports field in C:\Projects\mbr_frontend\node_modules\ngx-toastr\package.json)

**Comment by scttcper** [comment]
that's nowhere near the size after being bundled. whatever tool you're using is wrong
