### ISSUE TITLE
progressbar not visible when using custom toast

### ISSUE THREAD

**Issue by akshata456** [scttcper/ngx-toastr#1018]
we're using custom toast , refering the same pink toast example . here also in demo  progresbar not working . progresbar width is not updating .
<img width="540" alt="Screenshot 2024-06-06 at 5 19 13 PM" src="https://github.com/scttcper/ngx-toastr/assets/34393874/2c1c8943-9b6f-46fd-be51-bc037c2d19c6">
lmk we need to handle this case separataly.

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toast.component.ts#L39-L41
