### ISSUE TITLE
QUESTION: Is this module testable with protractor?

### ISSUE THREAD

**Issue by chriseenberg** [scttcper/ngx-toastr#109]
Hi.

I'd like to know if this module is testable through protractor?

i'm using angular 2.4.x and protractor 5.x

EDIT:
I've not been able to make it work with protractor, i've created an issue for anyone interested in the same subject here - [Post on stackoverflow](http://stackoverflow.com/questions/43322381/how-to-test-ngx-toastr-with-protractor-in-angular-2)

Kind regards Chris

**Comment by scttcper** [comment]
I gave it a good shot and wasn't able to figure it out. I think it might be the animations. 
`by.id('toast-component')` for some reason is always empty
https://github.com/angular/material2/tree/master/e2e/components with their dialog as the closest thing. They seem to have e2e for their snackbar component which would be an exact match for what we're doing here

**Comment by scttcper** [comment]
Might need to run outside ngZone or something https://github.com/angular/protractor/blob/master/docs/timeouts.md will try to look into this on monday

**Comment by scttcper** [comment]
Manged to get e2e working. https://github.com/scttcper/ngx-toastr/blob/7ca736fde0c0569d870acb1f4634329d94232db0/e2e/app.e2e-spec.ts#L15

**Comment by mmmichl** [comment]
Hello, I ran into the same issue of not being able to query the toasts and they substantially slow my e2e tests down (the execution halts until the toast disappears). Although your workaround is helping, it is not feasible for me, as my tests continue and I don't want to the waiting for angular on and off add each time to the callback-hell ;)

When I read the changelog of angular, I ran into following change:

> upgrade: call setInterval outside the Angular zone (269bbe0)
https://github.com/angular/angular/commit/269bbe0

I think there might be a hint for a solution on this topic. I didn't had time to future investigate it, but I probably will.

**Comment by scttcper** [comment]
@mmmichl lets keep it open then.

I tried a few things and stopped when it finally worked. Couldn't figure out fakeAsync or any of the other recommendations I ran across.

**Comment by PhilippStein** [comment]
Hi @scttcper I have the same problem and as you already suggested "running outside ngZone" was the solution. I provided pull request #299 which solved the issue for me. With the patched version I'm able to wait for the toastr to be visible in protractor.
Would be glad if you could merge the pull request and create a new version.
Thanks,
Philipp

**Comment by scttcper** [comment]
@PhilippStein what do your tests look like?

**Comment by PhilippStein** [comment]
@scttcper just remove the line `browser.waitForAngularEnabled(false);` in the existing test, or have a look at pull request #311 . I've added tests to check for toasts with `waitForAngularEnabled` on true and also a test that the toasts still automatically disappear.
Thanks for merging the pull request #299

**Comment by scttcper** [comment]
awesome thanks!
