### ISSUE TITLE
Could you please add position "center center"

### ISSUE THREAD

**Issue by wsyt1985** [scttcper/ngx-toastr#113]
such as 
`toastrConfig.positionClass = 'toast-center-center'`

This will be useful to us.

**Comment by yarrgh** [comment]
center-center is hard to achieve because there is no way of knowing how big the height is going to be. It is purely dependent on how much text is placed into the toast. But then again, I'm not a css expert.

You, or anyone else, is welcome to open a pull request if you know how to implement this.

**Comment by wsyt1985** [comment]
I've pushed to the branch.
You can merge it.
So, we can use toastrConfig such as "toastrConfig.positionClass = 'toast-center-center';"

**Comment by scttcper** [comment]
released in 5.2.0
