### ISSUE TITLE
No component factory found for t 

### ISSUE THREAD

**Issue by carlosvpp** [scttcper/ngx-toastr#123]
I'm getting this error when building and deploying my app to the server:

No component factory found for t. Did you add it to @NgModule.entryComponents...

Project settings:
Angular 4.1
ngx-toastr 5.2
Added ToastrModule.root() to app.module
Tried adding ToastrModule to the child module as well
Tried adding Toast Component as entry components in app.module.

Thanks

**Comment by cmckni3** [comment]
Are you setting a custom component to use with the `toastComponent` option?

**Comment by carlosvpp** [comment]
Nope. Just the default one.

**Comment by scttcper** [comment]
Are you using webpack or systemjs?

**Comment by carlosvpp** [comment]
Webpack.

 Thank you.

**Comment by scttcper** [comment]
Cool, able to reproduce. I think its one of the build settings i changed recently. Going to revert those.

**Comment by carlosvpp** [comment]
Great!  Thanks a lot for your time.

**Comment by scttcper** [comment]
Please give 5.2.1 a try. Its working in my test case. I probably won't try touching the build system again 😆

**Comment by carlosvpp** [comment]
It works like a charm! Thanks. Deploying a new build right now! 

I cannot thank you enough.
