### ISSUE TITLE
Missing ngx-toaster.js

### ISSUE THREAD

**Issue by kevin192291** [scttcper/ngx-toastr#124]
(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/ngx-toastr.js
I am getting this issue in a new project. Not build with angular CLI.
after saving, and doing an npm i, inside my node_modules\ngx-toastr folder I am getting(no ngx-toastr.js file):
`Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       05/08/2017  11:12 AM                overlay
d-----       05/08/2017  11:12 AM                portal
d-----       05/08/2017  11:12 AM                toastr
-a----       05/08/2017  11:12 AM            624 index.d.ts
-a----       05/08/2017  11:12 AM            611 index.js
-a----       05/08/2017  11:12 AM           1483 index.metadata.json
-a----       05/08/2017  11:12 AM           1079 LICENSE
-a----       05/08/2017  11:12 AM           2416 package.json
-a----       05/08/2017  11:12 AM           7337 README.md
-a----       05/08/2017  11:12 AM           6814 toastr.css
-a----       05/08/2017  11:12 AM          33370 toastr.umd.js
-a----       05/08/2017  11:12 AM          60593 toastr.umd.js.map`
Is this expected? Did I miss a step?
Thank you very much

**Comment by scttcper** [comment]
"main": "toastr.umd.js",
"module": "index.js",
"typings": "index.d.ts",

It shouldn't be looking for a ngx-toastr.js if you're using systemjs make sure you have it setup like it says in the readme.

**Comment by kevin192291** [comment]
Sorry, I missed that, I am up and running! I love ngx-toastr!!!!
