### ISSUE TITLE
Toastr in service dosent work

### ISSUE THREAD

**Issue by JokerzFree** [scttcper/ngx-toastr#127]
Hi.

Try to show toast from service, but this.toastr is undefined when i reach him.
Test calling from constructor working, but in another function which called from other places (components, servises) toastr already being undefined

Angular 4.0.3
Toastr 5.2.1

ToasterModule.forRoot() running inside app.module, my custom service laying in providers of app.module. (So everything like in README)

**custom.service.ts**
```
import { ToastrService } from "ngx-toastr";

@Injectable()

export class CustomService {

    constructor(toastr: ToastrService) {
        console.log(this.toastr); //Return object
    }

    function(){ //Which called from somewhere
        console.log(this.toastr); //Undefined
    }
}
```

**Comment by scttcper** [comment]
You're missing "private" in your example
```
constructor(private toastr: ToastrService) {
  console.log(this.toastr); //Return object
}
```

**Comment by JokerzFree** [comment]
> You're missing "private" in your example

Nothing changed after adding private.

**Comment by JokerzFree** [comment]
**scttcper**,
Thanks for spending time for me :D
Already find what is it all about. Trying to show toast message inside function of observable catch block.

**Comment by calebeaires** [comment]
@JokerzFree How do you did it in an service?

**Comment by scttcper** [comment]
@calebeaires it works the same as it does in controllers inside your service. You can try turning on `onActivateTick` setting.
