### ISSUE TITLE
ERROR Error: Found the synthetic property @flyInOut

### ISSUE THREAD

**Issue by subhani1249** [scttcper/ngx-toastr#136]
Hi ,
I have installed ngx-toastr by running this command. 
In map integrated  'ngx-toastr': 'npm:ngx-toastr/toastr.umd.js',
in module --> import { ToastrModule } from 'ngx-toastr';
imports: [BrowserModule,  ToastrModule.forRoot()],
im my component imported ToastrService and using like this 
this.toastrService.success('Hello world!', 'Toastr fun!'); 

but when i click to raise the toaster then i am getting error as below
![image](https://user-images.githubusercontent.com/10893928/27223152-dfaa9296-52ac-11e7-8291-434d0d38d390.png)

I am trying to Import BrowserAnimationsModule  like below 

npm install --save @angular/animations
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';

@NgModule({
  ...
  imports: [BrowserAnimationsModule],
  ...
})
after importing in build i am getting these errors
![image](https://user-images.githubusercontent.com/10893928/27223379-bb75a590-52ad-11e7-9202-94b6f979a869.png)

if i run,  iam getting the error 
![image](https://user-images.githubusercontent.com/10893928/27223435-0b520bd0-52ae-11e7-9920-653d5ec3d35b.png)

**Comment by cmckni3** [comment]
The import should be `import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`

**Comment by yarrgh** [comment]
My guess is that line 20 is the bad import statement for BrowserAnimationsModule and it's trying to fetch it but getting a 404 not found with HTML. Angular is then complaining about receiving HTML instead of the expected response.

**Comment by yarrgh** [comment]
Looks like the BroswerAnimationsModule is no longer mentioned in the readme. Was that intentional?

**Comment by cmckni3** [comment]
I see the link to Angular animations in the README. Looks like the setup instructions may need to be updated.

**Comment by scttcper** [comment]
Bummer. Will have to make sure that's there tomorrow

**Comment by scttcper** [comment]
Or if @cmckni3 or @yarrgh do it first. You guys can commit whatever you want. Go for it. 🚀🙂

**Comment by cmckni3** [comment]
@scttcper That update looks good 👍 

@subhani1249 can you try with the updated instructions?

**Comment by lholznagel** [comment]
Following the instructions and updating all angular dependencies to the same version, it seems to work fine.

**Comment by wsh92** [comment]
Included BrowserAnimations correctly and followed all the steps in the Readme file, but still facing the same issue -->
![image](https://user-images.githubusercontent.com/37227370/48597437-c737f980-e92b-11e8-9437-b308e6d0cd45.png)

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`

FYI...I have implemented a custom toast component.
