### ISSUE TITLE
Expression has changed after it was checked. Previous value: 'undefined'.

### ISSUE THREAD

**Issue by ARCHAMO** [scttcper/ngx-toastr#138]
Good morning. I already managed to implement the library to see notifications, but at the moment of using the notification appears correctly but in the browser console I get the following message.

![image](https://user-images.githubusercontent.com/12633358/27254574-75218408-5350-11e7-8934-66f25f16ee19.png)

**Comment by scttcper** [comment]
Thats no good. Can you show us how you're using it? What event is triggering the notification?

**Comment by ARCHAMO** [comment]
Hello the problem was when I called the toast, since I was doing it inside the constructor and apparently for some reason it was not loaded yet, but when I called it inside a ng-click it works correctly.
Thank you

**Comment by scttcper** [comment]
yeah has to at least be inside ngOnInit. Constructor is too early in component lifecycle
