### ISSUE TITLE
How to use custom icon with ngx-toastr

### ISSUE THREAD

**Issue by jdang67** [scttcper/ngx-toastr#140]
I am not quite sure if  I can use different icon with ngx-toastr.

thanks,

Jdang

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr.css#L130
Change the css. Override it with your own or create a new class and pass it as an option.

**Comment by goremukin** [comment]
@scttcper, Icons are OK. But I'm sure many people face the need to change their color. If you place icons as elements inside a container, you can easily do this using css:
```
.toast-error .icon {
  fill: red;
}
```

What do you think about this?
