### ISSUE TITLE
ng4.0.1报错

### ISSUE THREAD

**Issue by Alex-0407** [scttcper/ngx-toastr#142]
Failed to compile.

E:/angular4/phoenix/src/main/webapp/node_modules/@angular/platform-browser/animations/src/providers.d.ts (8,119): Module '"E:/angular4/phoenix/src/main/webapp/node_modules/@angular/animations/browser"' has no exported member 'ɵDomAnimationEngine'.

怎么解决呢

**Comment by scttcper** [comment]
Do you have `@angular/animations` package and import `BrowserAnimationsModule`

**Comment by Alex-0407** [comment]
yes, I did

**Comment by scttcper** [comment]
I'd try updating angular to 4.2.0 first. I haven't seen "ɵDomAnimationEngine" error

**Comment by yarrgh** [comment]
Check out https://github.com/angular/angular/issues/17400. Might be related to what you're seeing. If so, the solution seems to be to upgrade @angular/animations to at least 4.1.3 (I suggest getting the latest).

Some had issues after "upgrading" until they've removed their `node_modules/` folder and then reinstall all npm dependencies via `npm install`
