### ISSUE TITLE
CNDJS ?

### ISSUE THREAD

**Issue by Davilink** [scttcper/ngx-toastr#144]
Do you think you can publish on CDNJS : https://github.com/cdnjs/cdnjs

**Comment by scttcper** [comment]
Are there steps anywhere?

**Comment by Davilink** [comment]
It's was more like have a CDN to get the JS AND CSS without need to create a style shee in our project.

**Comment by scttcper** [comment]
https://unpkg.com/ngx-toastr@latest/toastr.css

You still would need to use systemjs to handle dependency injection.

**Comment by Davilink** [comment]
We don't use systemJS, because we use the angular-cli (with WebPack) and we only reference the JS and the CSS in the index.html. Maybe we don't use in the right way, but it work.

**Comment by yarrgh** [comment]
Why don't you use the `.angular-cli.json` file to inject the css? The JS is already being handled by webpack.

Something like this:
```
{
  // ...

  "styles": [
       "../node_modules/bootstrap/dist/css/bootstrap.min.css",
       "../node_modules/ngx-toastr/toastr.css",
       "styles.css"
    ],

  // ...
}
```

**Comment by Davilink** [comment]
Isn't better to use a CND ? If the CSS and JS file has already been loaded on an another website/webApp, it will already be in the browser cache for my webApp. Other thing, i discharge my server for delivering these librairies; maybe my server is in an another country, but the CDN will be closer to the end User.

**Comment by yarrgh** [comment]
What are you currently doing about the `vendor.bundle.js` and `polyfills.bundle.js` files? Those are webpacked js bundles that wouldn't be on a CDN (that I know of). I'd be more worried about those than the small toastr.css used in this library.

**Comment by Davilink** [comment]
Thank you for the feedback, i will go with your idea. I close the issue.
