### ISSUE TITLE
create toaster in div container

### ISSUE THREAD

**Issue by DuncanFaulkner** [scttcper/ngx-toastr#147]
Trying to get toaster into own div container, but doesn't appear to be working, followed instructions in readme. the toaster does appear just not from the container i was expecting.

are there any additional steps or an example of this working some where?

Cheers

**Comment by scttcper** [comment]
I've updated the readme with more clear instructions.  Let me know if that gets you anywhere.

https://github.com/scttcper/ngx-toastr/blob/master/README.md#put-toasts-in-your-own-container

Put up a repo where I have it working https://github.com/scttcper/toastrdiv

**Comment by DuncanFaulkner** [comment]
Thanks, will take a look at this later.

**Comment by DuncanFaulkner** [comment]
Thanks for the updated readme and examples but needed to add other directives to the div and no matter what I tried the additional directives just didn't seem to get picked.
Thanks again, will revisit this issue when I can get to it.

**Comment by ceoaliongroo** [comment]
Hi readme not work to me!  I want to open the toast inside a `DIV`too

The toast do not appears, if i change `positionClass` appears according the css class, but overlay not inside a dive with the directive.

**Comment by scttcper** [comment]
@ceoaliongroo please create a new issue.

**Comment by muniom** [comment]
I also have this same issue, it is not another issue, does not work as per readme

**Comment by scttcper** [comment]
@muniom you're right. ToastContainerModule needs to be imported in the module where you're trying to use it. Having a forRoot function on it is misleading. I've removed that in 6.4.0.

Please import ToastContainerModule where you need the directive available.

**Comment by adlh** [comment]
I also had the problem, that this only worked for standard toasts. Custom toasts were not placed on the container. Adding {static: true} to the @ViewChild declaration seems to fix the problem.

**Comment by feitzi** [comment]
@adlh you are right. It works for me after adding static true.
@scttcper can you maybe update the documentation?

```typescript
  @ViewChild(ToastContainerDirective, {static: true}) toastContainer: ToastContainerDirective;
```
