### ISSUE TITLE
Angular4 AOT compilation causes toastr message to display Ã— for 'X' icon

### ISSUE THREAD

**Issue by harikrishnan-u01** [scttcper/ngx-toastr#150]
Angular4 prod build (AOT compilation) causes toastr message to display Ã— for 'X' icon.
This works fine in dev build.

PFB screenshot:

![image](https://user-images.githubusercontent.com/10159959/28375006-5a4c33e8-6c74-11e7-95cf-5dc70afb9d65.png)

Any help in resolving this issue?

Thanks,
Hari

**Comment by scttcper** [comment]
The demo is in AOT so I'm not sure that's the case. I would try disabling any other css styles you have or make sure the toastr is loaded last.

The html for close button is here 
https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toast-component.ts#L25-L27

**Comment by cmckni3** [comment]
Does your HTML specify a character set, @harikrishnan-u01?

**Comment by harikrishnan-u01** [comment]
Hi @cmckni3 ,

Yes , I have the following:

   <meta charset="utf-8">

**Comment by cmckni3** [comment]
Cool, that's correct.

I was able to build and run my application correctly using version `5.3.0`. I would check your styles and make sure `toastr.css` is loaded as @scttcper said.

**Comment by harikrishnan-u01** [comment]
Hi @cmckni3 ,

I guess this is something to do with angular-cli and not a toastr specific issue.

Even `&nbsp; ` in the HTML code changes to` Â&nbsp;` in --prod build.

Not sure what to do.

Thanks,
Hari

**Comment by cmckni3** [comment]
That is very odd. Which version of the cli are you using?

**Comment by cmckni3** [comment]
I am curious as well. What OS are you running and what is the encoding of your files?

**Comment by harikrishnan-u01** [comment]
Hi @cmckni3 ,

I am using the cli version "1.3.0-beta.0".
This issue occurs in both Linux and Windows OS.

The encoding is URIEncoding="UTF-8" and am using tomcat server.

Thanks,
Hari

**Comment by cmckni3** [comment]
Is tomcat serving the files up using a different encoding?

The reason I asked about the encoding of the file itself is because Windows doesn't default to UTF-8 for new files AFAIK.

See https://stackoverflow.com/questions/40504558/angular-cli-angular2-non-standard-chars-only-load-correctly-in-index-html-not/40513193

**Comment by harikrishnan-u01** [comment]
Hi @cmckni3 ,

Tomcat is encoding the files in URIEncoding="UTF-8" and the files are saved as UTF-8 through VS code editor.

PFB the VS code editor setting:
  `// The default character set encoding to use when reading and writing files.
  "files.encoding": "utf8",`

**Comment by cmckni3** [comment]
I am out of ideas other than trying a different version of Angular CLI. Why are you using the beta version?

**Comment by harikrishnan-u01** [comment]
Hi @cmckni3 ,

Can I override the HTML used inside the toastr messages?
If so can you guide me how to do that?

I am thinking of a work around to fix this issue.

Thanks,
Hari

**Comment by scttcper** [comment]
You can create your own toast component like the Demo does. https://github.com/scttcper/ngx-toastr/blob/master/src/app/pink.toast.ts

Pass it to `toastComponent` option in individual or global options. Also add the component to your ngmodule entryComponents `entryComponents: [Toast]`

**Comment by cmckni3** [comment]
You can [extend](https://github.com/scttcper/ngx-toastr/blob/master/src/app/pink.toast.ts) the `Toast` class. If you want to use HTML inside of a message without extending, you can add the `enableHTML` option.

**Comment by harikrishnan-u01** [comment]
Hi @scttcper, @cmckni3  ,

The issue was with UTF-8 encoding. 

Found this by installing "Set Character Encoding" plugin in Chrome browser: https://chrome.google.com/webstore/detail/set-character-encoding/bpojelgakakmcfmjfilgdlmhefphglae

Added the following configuration in spring boot to resolve the issue:

spring.messages.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

Reference: http://netkiller.github.io/java/spring/boot/application.properties.html#charset

Thanks,
Hari
