### ISSUE TITLE
ToastrConfig no longer available to customize individual toasts

### ISSUE THREAD

**Issue by fmorriso** [scttcper/ngx-toastr#158]
As of August 8, 2017, the following code no longer works.  It worked just fine before the most recent release:

```
import { ToastrService, ToastrConfig } from 'ngx-toastr';

    private readonly freezeToast: ToastrConfig = {
		closeButton: true,
		timeOut: 0
	};

```
It appears that ToastrConfig is no longer exported.

The (hopefully temporary) work-around is:
```
import { ToastrService } from 'ngx-toastr';
import { IndividualConfig as ToastrConfig } from 'ngx-toastr';  // temporary? workd-around

    private readonly freezeToast: ToastrConfig = {
		closeButton: true,
		timeOut: 0
	};
```
If this is a permanent change, please update the documentation and examples to show that individual toasts need to pass a structure of type IndividualConfig instead of ToastrConfig as was the case in the most recent prior release.

**Comment by scttcper** [comment]
Added the alias back in 6.0.1
