### ISSUE TITLE
error in angular animation

### ISSUE THREAD

**Issue by abadakhshan** [scttcper/ngx-toastr#161]
hi
i use 5.3.1 version
and i get this error when display toast

"this.engine.setProperty is not a function
    at AnimationRenderer.setProperty (animations.es5.js?28df:502)
....."

i use @angular/animations 4.2.6 
and @angular/platform-browser 4.2.6

**Comment by scttcper** [comment]
try running `npm outdated` & then `npm update`

**Comment by abadakhshan** [comment]
Thank you
My problem has been resolved
