### ISSUE TITLE
Question: How to do <br> tag when combining two different message string?

### ISSUE THREAD

**Issue by santosmken** [scttcper/ngx-toastr#166]
This is my code and the `<br>` is not working even the `</br>`.
 
`this.toastr.error(message[0] + <br> + message[1], null, {enableHtml: true});`

**Comment by santosmken** [comment]
Already fix it. Is it possible to handle an event from the toastr? Like there is confirmation dialog.

**Comment by scttcper** [comment]
Unfortunately, thats in the realm of a custom toast component. The pink toast would be a good example https://github.com/scttcper/ngx-toastr/blob/master/src/app/pink.toast.ts Pass whatever you want on click to triggerAction and you can subscribe to `onAction` in the response of this.toastr.success.

**Comment by santosmken** [comment]
I see, thank you for your response :)
