### ISSUE TITLE
Upgrade from 5.2.0 to 6.0.1 breaking

### ISSUE THREAD

**Issue by samnadarajan** [scttcper/ngx-toastr#169]
I recently upgraded my ngx-toastr package from 5.2.0 to 6.0.1. The application builds fine (angular/cli 1.0) but when I launch the browser I get the following error:

`core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: ToastrModule is already loaded. It should only be imported in your application's main module.
Error: ToastrModule is already loaded. It should only be imported in your application's main module.
    at new ToastrModule (toastr-module.js:11)
    at _createClass (core.es5.js:9515)
    at _createProviderInstance$1 (core.es5.js:9487)
    at initNgModule (core.es5.js:9441)
    at new NgModuleRef_ (core.es5.js:10555)
    at Object.createNgModuleRef (core.es5.js:10539)
    at NgModuleFactory_.webpackJsonp.../../../core/@angular/core.es5.js.NgModuleFactory_.create (core.es5.js:13828)
    at MapSubscriber.project (router.es5.js:3520)
    at MapSubscriber.webpackJsonp.../../../../rxjs/operator/map.js.MapSubscriber._next (map.js:77)
    at MapSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next (Subscriber.js:89)
    at new ToastrModule (toastr-module.js:11)
    at _createClass (core.es5.js:9515)
    at _createProviderInstance$1 (core.es5.js:9487)
    at initNgModule (core.es5.js:9441)
    at new NgModuleRef_ (core.es5.js:10555)
    at Object.createNgModuleRef (core.es5.js:10539)
    at NgModuleFactory_.webpackJsonp.../../../core/@angular/core.es5.js.NgModuleFactory_.create (core.es5.js:13828)
    at MapSubscriber.project (router.es5.js:3520)
    at MapSubscriber.webpackJsonp.../../../../rxjs/operator/map.js.MapSubscriber._next (map.js:77)
    at MapSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next (Subscriber.js:89)
    at resolvePromise (zone.js:783)
    at resolvePromise (zone.js:754)
    at zone.js:831
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:191)
    at drainMicroTaskQueue (zone.js:595)
    at ZoneTask.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1370)
defaultErrorLogger @ core.es5.js:1020
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
next @ core.es5.js:4503
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
(anonymous) @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:141
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844
onHandleError @ core.es5.js:3912
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runGuarded @ zone.js:157
_loop_1 @ zone.js:666
api.microtaskDrainDone @ zone.js:675
drainMicroTaskQueue @ zone.js:603
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1370
globalZoneAwareCallback @ zone.js:1388
XMLHttpRequest.send (async)
(anonymous) @ VM29404:1
scheduleTask @ zone.js:2622
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:300
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:235
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:258
(anonymous) @ zone.js:2646
proto.(anonymous function) @ zone.js:1227
(anonymous) @ http.es5.js:1275
webpackJsonp.../../../../rxjs/Observable.js.Observable._trySubscribe @ Observable.js:171
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:159
webpackJsonp.../../../../rxjs/operator/map.js.MapOperator.call @ map.js:54
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
webpackJsonp.../../../../rxjs/operator/catch.js.CatchOperator.call @ catch.js:79
webpackJsonp.../../../../rxjs/Observable.js.Observable.subscribe @ Observable.js:156
(anonymous) @ ted-application.service.ts:41
ZoneAwarePromise @ zone.js:847
webpackJsonp.../../../../../src/app/services/ted-application.service.ts.TedApplicationService.getInitialData @ ted-application.service.ts:34
(anonymous) @ app.module.ts:24
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationInitStatus.runInitializers @ core.es5.js:2807
(anonymous) @ core.es5.js:4506
_callAndReportToErrorHandler @ core.es5.js:4406
(anonymous) @ core.es5.js:4504
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:141
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleFactoryWithZone @ core.es5.js:4495
(anonymous) @ core.es5.js:4537
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:141
(anonymous) @ zone.js:831
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:424
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:191
drainMicroTaskQueue @ zone.js:595
Promise resolved (async)
scheduleMicroTask @ zone.js:578
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:235
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:255
scheduleResolveOrReject @ zone.js:829
ZoneAwarePromise.then @ zone.js:918
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone @ core.es5.js:4537
webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule @ core.es5.js:4522
../../../../../src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap 225725e95543cebf0910:54
3 @ main.bundle.js:7168
__webpack_require__ @ bootstrap 225725e95543cebf0910:54
webpackJsonpCallback @ bootstrap 225725e95543cebf0910:25
(anonymous) @ main.bundle.js:1
`

Currently have an `app.module.ts`, with a submodule `child.module.ts` and an `app-shared.module.ts` I import the ToastrModule in the `app-shared.module.ts` and export it from there as well so it's available to all modules. I checked to make sure I'm not already importing/exporting it elsewhere and I'm not. What am I missing?

**Comment by scttcper** [comment]
does it work without reexporting it?

**Comment by samnadarajan** [comment]
no, if I just include it in the imports in my app-shared.module.ts it still breaks.

**Comment by yarrgh** [comment]
Does your child module also import the shared module?

If so, try moving the ToastrModule import to just AppModule.

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by samnadarajan** [comment]
I moved the ToastrModule import to app module and I'm able to access it inside my child module. THanks!
