### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError on AOT

### ISSUE THREAD

**Issue by phmello** [scttcper/ngx-toastr#170]
Im getting the following error when building AOT:
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'toast-error toast'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?

Am I doing something wrong or that a actual bug?
cheers

**Comment by yarrgh** [comment]
Are you displaying a toast on an angular lifetime event? If so, see #160 

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by phmello** [comment]
yes, [this](https://github.com/scttcper/ngx-toastr/issues/160#issuecomment-321888380) solved the problem.
