### ISSUE TITLE
Adding input or button tag is being removed

### ISSUE THREAD

**Issue by robertbarron** [scttcper/ngx-toastr#171]
Hello,

 I'm trying to use toastrService.error(options) to add some html content into my toastr, but the input and button tags are being removed.

Currently the tags (the one I tried)  that are being removed are button, input and content editable.

Is there a way that I can add those type of html elements?

Thank you

**Comment by yarrgh** [comment]
Your best option is to create your own custom toast component. See the pink toast in [the example ](https://scttcper.github.io/ngx-toastr/)

You can see the source code of the pink component to get a feel for how it is created:
https://github.com/scttcper/ngx-toastr/blob/81162e532b7647a0c6e22fe9218f91d5134083e4/src/app/pink.toast.ts#L15-L114

Then you'd do something like the following to use your new toastr component:
https://github.com/scttcper/ngx-toastr/blob/81162e532b7647a0c6e22fe9218f91d5134083e4/src/app/app.component.ts#L80-L96

**Comment by akash-potdar7** [comment]
I don't want to use loadash, is there any replacements for cloneDeep() and random() funcitons?

**Comment by jacques-hoventer** [comment]
Why was this closed? Could you perhaps point to an explanation of why ngx-toastr removed this built-in functionality of toastr?

**Comment by jacques-hoventer** [comment]
PS. The 'pink' example doesn't work in Edge

**Comment by scttcper** [comment]
Open a new issue if you have a bug.
