### ISSUE TITLE
How get After click close button event

### ISSUE THREAD

**Issue by Aofhero** [scttcper/ngx-toastr#174]
```
  opt.toastComponent = ValidCheckToast;
  opt.toastComponent.wantClear = false
  opt.toastClass = 'pinktoast';
  let t = "Wrong";
  let m = "You Changed value and valid input data";


  let mm =  this.toastrService.show(m, t, opt)
```

I use component toast(Pink Toast from Demo) but can't get callback event on click button 
I don't want catch event in toast component, But I want to know when clicked button on toast in app.component.ts 

Help me please
Thanks

**Comment by scttcper** [comment]
You're doing everything right
```ts
const mm = this.toastrService.show('yas')
mm.onAction.subscribe((action) => console.log(action));
```

then in your custom toast
```ts
click() {
     this.toastPackage.triggerAction('confirmed');
}
```

**Comment by camilosama** [comment]
Hi this work for me. 

`const mm = this.toastr.success(e['mensaje'], 'Proceso Exitoso ', { 
            //timeOut: 8000,
            //closeButton: true,
            enableHtml: true,
            progressBar:true,
            disableTimeOut:true,
            tapToDismiss:true,
            closeButton:true
           },
         );`
`mm.onHidden.subscribe((close) => {
          this.loading = false;
          location.reload();
          this.forma.reset();
        });`
