### ISSUE TITLE
Error in AOT WebPack 

### ISSUE THREAD

**Issue by miguel1603** [scttcper/ngx-toastr#176]
I get this error when generating my webpack in production mode help me please

use `const AotPlugin = require('@ngtools/webpack').AotPlugin;`
 
![image](https://user-images.githubusercontent.com/30298045/29743380-72fa33fe-8a56-11e7-8937-87b60f00a692.png)

webpack config
`new AotPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.module.browser#AppModule'),
                exclude: ['./**/*.server.ts'],
            })`

**Comment by scttcper** [comment]
Use 6.0.1. I forgot to update the path in the package.json. I'll fix it tonight

**Comment by miguel1603** [comment]
ya se actualizo el package.json  a "ngx-toastr": "6.0.1", se elimino la carperta node_modules y limpio cache pero el problema persiste al generar el compilado AOT
![image](https://user-images.githubusercontent.com/30298045/29745978-3a589038-8a90-11e7-8beb-966fc917c64a.png)

**Comment by miguel1603** [comment]
The package.json has been updated to "ngx-toastr": "6.0.1", the node_modules file was removed and the cache cleaned but the problem persists when generating the AOT compiled
![image](https://user-images.githubusercontent.com/30298045/29746026-1b685396-8a92-11e7-94e9-becb1e94038f.png)

**Comment by scttcper** [comment]
Hmmm I'm not sure. I've also just released 6.1.2 which should also work. I've got it compiling w/ AoT on some internal stuff and it seems to be fine.

**Comment by hollandz** [comment]
@scttcper My google searches keep brining me back here. What's the latest stable version of this package that should be AoT compatible with Angular 4?

**Comment by scttcper** [comment]
@hollandz the unfortunately named `6.4.1-beta.0`

**Comment by hollandz** [comment]
Ah got it 😅. If I'm having trouble compiling that AoT, should I open an issue here?
