### ISSUE TITLE
Cannot Inject ToastrService into a custom error handler.

### ISSUE THREAD

**Issue by countzyx** [scttcper/ngx-toastr#179]
Running the latest version of ngx-toastr with Angular 4.1.2. I'm trying to make a custom error handler that puts out toasts when unexpected errors happen. The code looks like this -

`
import { ToastrService } from 'ngx-toastr';
import { ErrorHandler, Inject } from "@angular/core";

export class AppErrorHandler implements ErrorHandler {
    constructor(@Inject(ToastrService) private toastrService:ToastrService) { }

    handleError(error: any): void {
        this.toastrService.error(
            "An unexpected error has occurred.",
            "Error",
            {
              closeButton: true,
              timeOut: 5000
            }
          )
    }
}
`

When I try this I get an error on the console about there being a cyclic dependency while processing the app.module file.
`Error: Provider parse errors:
Cannot instantiate cyclic dependency! ApplicationRef ("[ERROR ->]"): in NgModule AppModule in ./AppModule@-1:-1`

I suspect that this error is misleading and Angular is just having trouble linking dependencies since the error handler gets loaded pretty early in the startup cycle. Is the problem even fixable? Or is there a way to feed error messages into a queue that can be processed by a service that once loaded can emit toasts? Any help is greatly appreciated.

**Comment by yarrgh** [comment]
Try something like what I mentioned in [this post](https://github.com/scttcper/ngx-toastr/issues/137#issuecomment-309217168)

Maybe we need to add this to the FAQ or add an example into the repo

**Comment by yarrgh** [comment]
Your example would be something like the following:

```typescript
import { ErrorHandler, Inject, Injector} from "@angular/core";
import { ToastrService } from "ngx-toastr";

export class AppErrorHandler implements ErrorHandler {
    constructor(@Inject(Injector) private injector: Injector) { }

    private get toastrService(): ToastrService {
        return this.injector.get(ToastrService);
    }

    public handleError(error: any): void {
        this.toastrService.error(
            "An unexpected error has occurred.",
            "Error",
            {
                closeButton: true,
                timeOut: 5000
            }
        );

        throw error;
    }
}
```

**Comment by crhistianr** [comment]
You might also need to turn on `onActivateTick` in the error handler to ensure that the toast is running inside Angular's zone.

An updated example can be found here - https://github.com/scttcper/ngx-toastr/issues/327

**Comment by yarrgh** [comment]
Updated the example here since this is where the FAQ points to.

**Comment by zymr-keshav** [comment]
thank you for this nice snippet  here is my issue
 see the complete issue here : https://stackoverflow.com/questions/49148781/custom-error-handler-throw-error-cannot-read-property-get-of-undefined-inj

**Comment by yarrgh** [comment]
What you're trying to do in that issue on stackoverflow is not the same as what is mentioned here. This issue is about trying to inject `ToastrService` into a custom ErrorHandler. In that SO issue, you're trying to access `ToastrService` from a custom error. This is not the same and isn't possible unless you pass the ToastrService into the constructor of your `AccessDenied` class. `new AccessDenied(toastrService)`

What I suggest doing is creating a custom error handler, like the one mentioned above, and then having that error handler look at the error being passed into the `handleError()` method and see if it is an instance of `AppError` and then use the `ToastrService` to display a message.

Roughly something like this 

```typescript
// ... The rest of the error handler

public handleError(error: any): void {
    if (error instanceof AppError) {
        this.toastrService.error(
          error.message,
          error.title,
          {
            closeButton: true,
            timeOut: 5000,
            onActivateTick: true
          }
        );
    }

    super.handleError(error);
  }
```

**Comment by Alsmith141510** [comment]
I am using angular 7.3.3, angular material and ngrx-toastr. I have a login screen which is a matdialog. On error I want show a toastr with error. but I am getting an error. Any pointer would be helpful.
