### ISSUE TITLE
AOT build failing

### ISSUE THREAD

**Issue by MrBlaise** [scttcper/ngx-toastr#183]
I have created an issue on the angular repository, I am not sure whether this is a problem with angular or this package. Please see details here: https://github.com/angular/angular/issues/19200

**Comment by MrBlaise** [comment]
I've tested my app (which uses a lot of third party packages) without ngx-toastr and it ran fine. Seems like it is special problem related to something in this package. The ng2-toastr package does the same Recursion error. Still no idea what causes it :S

**Comment by yarrgh** [comment]
It's an issue with animations being used by the Toastr component. If you comment out the whole animations section in the Toastr component (and any component that uses animations), everything compiles. Did the use of animations change with angular 5.0.0-beta.7?

The compiler has issues animations being used in `@angular/common`. This includes `trigger`, `animate`, `style`, and probably `transition`

**Comment by yarrgh** [comment]
I meant to create a PR but accidentally pushed to master. Thought I was in my forked repository. I also meant to branch...

But anyways, I just pushed a fix for this. The issue was that we were importing `trigger`, `state`, `animate`, `style`, and `keyframes` from `@angular/core` instead of `@angular/animations`

@scttcper Do you want to make sure that everything still works the way you think it should?

**Comment by scttcper** [comment]
.... how does typescript not pick up the import missing or.. what is even happening...

It does look like @angular/animations is the way to go.

**Comment by scttcper** [comment]
Published 6.2.0

**Comment by yarrgh** [comment]
Yeah I think it may have been the way the initially did animations. I think when they split to `@angular/animations` the code stayed pointed to `@angular/core`. Guess they left it in both places for backwards compatibility until the next major version.

@MrBlaise version 6.2.0 was released. If everything looks good on your end we'll close out both issues.

**Comment by MrBlaise** [comment]
Thanks! It seems to work fine now :)
