### ISSUE TITLE
onAction Event usage

### ISSUE THREAD

**Issue by oleksandrstarov** [scttcper/ngx-toastr#184]
Hi, I've checked this library and found the onAction Observable for custom templates toasts, however not sure how to use this. I cannot pass any (click) listeners to template due to sanitize, and I cannot register any listeners from options too. Is there way to use this without need to extend Toast class as done in pink.toast.ts example?
I want just to use a button in my notification with callback function passed via options.

**Comment by scttcper** [comment]
Have to extend toast for that. There isn't a good solution to passing html+js to a component at runtime because AOT compiling, sanitizing, etc.
