### ISSUE TITLE
Using toast customComponent's elsewhere

### ISSUE THREAD

**Issue by muniom** [scttcper/ngx-toastr#188]
I have some customComponents with specific templates working, they extend the base Toast, which injects toastrService, toastPackage, & appRef.

The selectors for the components are set up as attributes. What i would like to do is re-use these components in my "all notifications" page. However I'm not sure how to convert the selector to a proper tag that can be reused without getting missing provider errors on the dependencies. Is this possible?

Thanks for the library btw!

**Comment by scttcper** [comment]
Uhhhh the providers are going to cause issues. Let me think about it a bit more

**Comment by scttcper** [comment]
Best bet is to use https://github.com/scttcper/ngx-toastr#put-toasts-in-your-own-container
