### ISSUE TITLE
Disabled BrowserAnimationsModule

### ISSUE THREAD

**Issue by hijoncon** [scttcper/ngx-toastr#198]
Thank you for your plugin! Is there a way not to disable the animation?

**Comment by yarrgh** [comment]
I'm not sure if I understand. Are you asking if there is a way to disable the animations?

**Comment by dhardtke** [comment]
Saw this issue. Since the OP did not reply I would kindly ask: Is there any way to use ngx-toastr without having to add a dependency on @angular/animations? :)

**Comment by yarrgh** [comment]
Currently, no. That would require a custom to be used. It could be as simple as copying everything from the Toast component and getting rid of all the animations, and then overriding the default component in the global config.

**Comment by scttcper** [comment]
try `import {NoopAnimationsModule} from '@angular/platform-browser/animations';`

**Comment by dhardtke** [comment]
Thanks for your reply.

Unfortunately, that does not help much because ngx-toastr is still having a dependency on "@angular/animations" internally.

My goal is to reduce the bundle size of my built app.

**Comment by yarrgh** [comment]
I'll take a look at this by possibly introducing a component without animations. This way you won't need to have that dependency.

**Comment by scttcper** [comment]
Published 7.0.0-beta.0 on ngx-toastr@next

Although, i think it would still need to be installed
