### ISSUE TITLE
how to translate toastr messessage

### ISSUE THREAD

**Issue by alimashal** [scttcper/ngx-toastr#201]
I just installed ngx-toaster and need to work with two language and I can't translate the message any suggestion?

**Comment by scttcper** [comment]
How do you usually handle this? I haven't looked into i18n w/ angular yet

**Comment by alimashal** [comment]
by using ngx-translate we can translate in different ways like.
<h1 translate>{{'success-msg'}}</h1>
or <card  cardTitle="{{'success-mgs' | translate}}"></card>

**Comment by yarrgh** [comment]
If you are using ngx-translate, it might be better if you provide the translated text to ngx-toastr using the `TranslateService`.

The example on ngx-translate/core looks like this:
```typescript
translate.get('HELLO', {value: 'world'}).subscribe((res: string) => {
    console.log(res);
    //=> 'hello world'
});
```

So maybe something like this?
```typescript
translate.setTranslation('en', {
    INVALID_CREDENTIALS: 'Invalid Credentials'
});
// Add other language translations

translate.get('INVALID_CREDENTIALS').subscribe((res: string) => {
  toastr.error(res);
});
```

**Comment by alimashal** [comment]
thanks a lot Mr Yarrgh it worked

**Comment by yarrgh** [comment]
I also created a gist with a custom component that would handle the translations for you.

The gist is located at https://gist.github.com/yarrgh/84ee1cb78cdcdb537cc0c7c203b49216

The component is almost exactly like the original Toast component except it uses the Translate pipe on [line 31](https://gist.github.com/yarrgh/84ee1cb78cdcdb537cc0c7c203b49216#file-translate-toast-component-ts-L31) and [line 36](https://gist.github.com/yarrgh/84ee1cb78cdcdb537cc0c7c203b49216#file-translate-toast-component-ts-L36)

I also provided an example app.module.ts of using that custom component.

I haven't actually tested (or even ran) the code, although I think it should work.

**Comment by sammirzagharcheh** [comment]
HI Guys,
How Can I use RTL ?

**Comment by b-jakubowski** [comment]
> How do you usually handle this? I haven't looked into i18n w/ angular yet

I use angular custom i18n in my application 
```
<h1 i18n="@@introductionHeader">Hello i18n!</h1>
```
Is there a way (other then custom component) to support it?
Now when i pass the correct translation key i receive warn in console:
```
WARNING: sanitizing HTML stripped some content 
```

**Comment by fateh14** [comment]
for angular i18n translation of ngx-toastr message check my answer here: 
https://stackoverflow.com/a/56074544/4399281

**Comment by pdotkriz** [comment]
@yarrgh  Unfortunate  the result display only Key not value..
translate.get('INVALID_CREDENTIALS').subscribe((res: string) => {
 this.toasterService.pop(this.createToast("success","Success", res);
});
Pop up gives the INVALID_CREDENTIALS instead Invalid Credentials

**Comment by krzyhan** [comment]
You can always use your own service to translate message before showing toast.

Ex. here:  https://gist.github.com/krzyhan/079989d41d7dbf9de26ee79ef71ffcdc

**Comment by xewertonfilipe** [comment]
The best example using json file

https://stackoverflow.com/questions/46155989/ngx-translate-with-dynamic-text-on-ts-file
