### ISSUE TITLE
onTap not working with preventDuplicates

### ISSUE THREAD

**Issue by bmnicolae** [scttcper/ngx-toastr#202]
First I want to thank you for your hard work.

I've used toastr with ``onTap`` from ``ActiveToast `` and every time I click on it redirects me to a different page. 
```javascript
this.toastrService.success('message').onTap.subscribe(() => {
  this.router.navigateByUrl('/');
});
```
It's work great but when I've tried to block duplicate messages (``preventDuplicates``) I get: ``ERROR TypeError: Cannot read property 'onTap' of null``.

Thank you!

**Comment by yarrgh** [comment]
Does this happen on the first toast as well?

My guess is that (without looking at the code yet) when there's a duplicate, it's supposed to return null because it got rejected.

**Comment by yarrgh** [comment]
Yeah, it looks like if `ToastrService` detects a duplicate message it will return null
https://github.com/scttcper/ngx-toastr/blob/5829621f196c23a71a14768a935629e16bc57902/src/lib/toastr/toastr-service.ts#L179-L181

**Comment by bmnicolae** [comment]
Yes you are right, I need to dig more into toastr source code to understand it and maybe to find a solution.

**Comment by scttcper** [comment]
just check if its null. I think turning on typescript's strict mode would've caught this as well.
```ts
const toast = this.toastrService.success('message')
if (toast) {
  toast.onTap.subscribe(() => {
    this.router.navigateByUrl('/');
  });
}
```

**Comment by bmnicolae** [comment]
Thank you!
