### ISSUE TITLE
Toasts not showing on HTTP Abort

### ISSUE THREAD

**Issue by AshMcConnell** [scttcper/ngx-toastr#204]
Hi Folks, I'm getting some strange behaviour when I cancel a running HTTP request in Angular 4.4.4. For some reason my toasts don't show. I can't see any reasonable explanation why the 2 actions are related. 

Is there anything I should know about unsubscribing from a HTTP request that might cause problems?

If I let the http request complete (by adding a setTimeout around the unsubscribe call) the toast is shown correctly. I know it makes no sense! :smile: 

I'm using a custom error handler and a console.error is appearing that is called immediately before the toasterService.error(...)

Thanks for your help!
Ash

**Comment by AshMcConnell** [comment]
It seems to work if I set the onActivateTick option.  Is there a way to set that globally by any chance?

**Comment by scttcper** [comment]
All individual options can be overridden in the global options to affect all toasts
https://github.com/scttcper/ngx-toastr#global-options

**Comment by AshMcConnell** [comment]
Thanks!  Missed that line
