### ISSUE TITLE
fade in/out fly right/left

### ISSUE THREAD

**Issue by alireza-saberi** [scttcper/ngx-toastr#211]
HI;
I am trying to have some animations on the toast (success/error/info) but I can't make it with this library. 
However, I see that there is `Pink toast` with animation.
What is the trick to have fade in/out fly right/left on these normal toasts?

**Comment by scttcper** [comment]
Its hardcoded into the pink toast. https://github.com/scttcper/ngx-toastr/blob/master/src/app/pink.toast.ts#L59-L92

**Comment by alireza-saberi** [comment]
cool. thanks for quick response.
I noticed the appearance of normal toasts i.e. success/error/info are also having fade in/out. but mine is flashing to show and disappear. Am I missing something that is not written in the `README` file?

**Comment by alireza-saberi** [comment]
Yes, I imported it in my `app.module.ts`

**Comment by scttcper** [comment]
What browser+version and version of angular?

**Comment by alireza-saberi** [comment]
Browser is Chrome `Version 61.0.3163.100 (Official Build) (64-bit)`,
AngularJS is 
```"@angular/cli": "1.4.4",```
``` "@angular/compiler-cli": "4.0.0",```

**Comment by scttcper** [comment]
i think there was pretty big changes in angular ^4.4.0 which might be causing issues.

**Comment by yarrgh** [comment]
Are you trying to use custom toast components? If so, can you post your coffee for us to take a look at?
