### ISSUE TITLE
Uncaught TypeError: (void 0) is not a function

### ISSUE THREAD

**Issue by iTwangcj** [scttcper/ngx-toastr#238]
In production mode, any code changes are saved, and the browser throws the error:
Uncaught TypeError: (void 0) is not a function

![image](https://user-images.githubusercontent.com/7961076/32772507-00111106-c961-11e7-8011-3d79c33d5536.png)

![image](https://user-images.githubusercontent.com/7961076/32778719-f3268f6a-c975-11e7-9b28-ada05208c92c.png)

**Comment by scttcper** [comment]
probably need more details. i don't think anyone else has this problem

**Comment by yarrgh** [comment]
What version of ngx-toastr are you using? 

When/how are you seeing that error?

We need more details or we cannot help.

**Comment by jberlynn** [comment]
@iTwangcj I'm getting the same problem. Did you ever come to a solution?

**Comment by scttcper** [comment]
@jberlynn open a new issue with more details.
