### ISSUE TITLE
Toastr not showing in global error handler

### ISSUE THREAD

**Issue by phillashworth** [scttcper/ngx-toastr#267]
I'm trying to display toasts in a custom error handler as explained in the FAQ, they do work if I `throw()` an error in code but if there are errors for example in the Angular template the error handler is called but the toasts do not display. 

From reading other tickets such as #226 I suspect it may have something to do with change detection but `onActivateTick` seems to make no difference.

I've created a Plunk to illustrate the problem https://plnkr.co/edit/YPGcotdSfMmenyX3zq6D where you can see Toastr working for thrown() errors but if one deliberately introduces an error by editing the template:

 ```
 template: `
    <div>
      <h2>Hello {{nameee.foo}}</h2>
      <button (click)="showToast()">Pop toast</button>
      <button (click)="throwError()">Throw error</button>
    </div>
  `,
```
The error handler runs but the toast does not display.

Angular 4.4.6 + ngx-toastr 6.5.0

**Comment by yarrgh** [comment]
This should be fixed in #237 

I was able to duplicate the issue and see that it was also fixed. This may be because we're switching to running change detection on the overlay when `onActivateTick` is set to true, and not the entire application.

**Comment by gopal-g** [comment]
I have run into the same issue now not sure why the toast is not showing ... Im using `"ngx-toastr": "^8.7.3",`.  

I have used injector to get the toastr service into the globalHandler when error occurs toast wont show...
I also added another toast trigger in my login component which shows and when this toast is about to dismiss the errorHandler toast shows and vanishes immediately! 

If i remove the toast from login component the errorHandler toast never shows up! Please help.

**Comment by gopal-g** [comment]
#327  helped me fix this thank you .... :)
