### ISSUE TITLE
Config interface should have optional attributes

### ISSUE THREAD

**Issue by zentoaku** [scttcper/ngx-toastr#271]
Hi,

I've noticed that in newer versions GlobalConfig interface was changed that all attributes are no longer optional. This doesn't make any sense as they all have default values and making them required prevents user from using them in implicit way and forces to define all of them each time he would like to change only one. Last version I know of that have those attributes optional is 6.1.4.
Do you think it's possible to revert them to be optional again?

PS. Good job with this lib :)

**Comment by yarrgh** [comment]
They are optional. `ToastrModule.forRoot()` now accepts a `Partial<GlobalConfig>` which makes everything optional.

If you're using the type `GlobalConfig` directly, just change it to `Partial<GlobalConfig>`

**Comment by zentoaku** [comment]
Ok. thanks for this, missed it in source code :)
