### ISSUE TITLE
Add button or link in toaster

### ISSUE THREAD

**Issue by CalibanAngel** [scttcper/ngx-toastr#272]
Hi,
I'd like to add a button or a link in my toastr, so I try to put HTML inside the message but it doesn't do anything. Am I doing something wrong ? 

Here is my code:

```
private totoTemplate =
    '<p>Toastr to print toto</p>' +
    '<p><button class="btn btn-link" type="button" (click)="toto()">click here</button> to do something.</p>';

  constructor(private toastr: ToastrService) { }

  unvalidateAccount() {
    this.toastr.warning(this.totoTemplate, 'Print toto', {timeOut: 10 * 1000, enableHtml: true, closeButton: true, tapToDismiss: false});
  }

  toto() {
    console.log('toto');
  }
```

thanks for your job :)

**Comment by scttcper** [comment]
Angular doesn't let you do that. If you're looking for a custom toast with an action see the pink toast in the demo.  https://github.com/scttcper/ngx-toastr/blob/master/src/app/pink.toast.ts

**Comment by CalibanAngel** [comment]
thank you !

**Comment by faizan78693** [comment]
How can i execute my component logic based on toastr button click ?
undo is getting changed to undid , but its written inside the pinktoastr component itself.

**Comment by scttcper** [comment]
@faizan78693 look at using onAction in your toast https://github.com/scttcper/ngx-toastr#toastr-service-methods-return
