### ISSUE TITLE
Animation Not Working on Custom toast component

### ISSUE THREAD

**Issue by afour-bhargav** [scttcper/ngx-toastr#278]
Animation not working when using Custom Toast component. I've create same custom component as 'pink.toast.ts' . The only change is my all imports are like 'from 'ngx-toastr' .

**Comment by scttcper** [comment]
Do you have BrowserAnimationsModule loaded? Do the animations work without using a custom toast?

**Comment by afour-bhargav** [comment]
Yes BrowserAnimationModule is loaded. I am using animation for other functionality. And animation is also working for noraml toast.

**Comment by yarrgh** [comment]
I'm not able to duplicate this: [https://embed.plnkr.co/soyqVh/](https://embed.plnkr.co/soyqVh/)

We'll need more information in order to help you out. Can you post your code in Plunker or in another repo so we can take a look at your code?

**Comment by afour-bhargav** [comment]
I tried on provided plunkr by putting my toastr component. Animation is working working properly.
In my application animation is working for progress and when toastr leave. It's just not working when toastr is shown (enter animation).

**Comment by afour-bhargav** [comment]
It's working now. I just changed the initial transition state. I've put 'void' in place of 'inactive'.

**Comment by scttcper** [comment]
👍
