### ISSUE TITLE
Only for Angular 5+?

### ISSUE THREAD

**Issue by 1-0-1** [scttcper/ngx-toastr#280]
Is the new version (7) only for Angular 5+ now?

ngx-toastr@7.0.2 requires a peer of @angular/core@>=5.0.0

**Comment by scttcper** [comment]
yep, anything built using angular 5 can only be used w/ angular 5

**Comment by yarrgh** [comment]
Is there some kind of documentation from Angular stating this? I'm able to use ngx-toastr v7.0.2 with Angular 4.4.6 and I don't see any issues. 

With further testing I was able to see that with anything less than 4.2, the animations stop working, otherwise it seems to work just fine. I've even tested against 4.0 and it still seems to work.

**Comment by scttcper** [comment]
That has been my experience. Are you using aot?

https://github.com/angular/angular/issues/19607

**Comment by 1-0-1** [comment]
So the latest fixes aren't available in the Angular 4 version?
Upgrading to Angular 5 isn't possible right now.  I've got a very large project and the TypeScript upgrade for Angular 5 has some breaking changes for me.

**Comment by 1-0-1** [comment]
#yarrgh - You might want to verify that you are getting the latest.  I thought I was using version 7, but it must not have been installing it.  I had a co-worker who ended up with build problems and when I killed my node-modules folder and built from scratch I ended up with the same errors.

**Comment by scttcper** [comment]
try `ngx-toastr@6.4.1-beta.0` which is on the `ngx-toastr@ng4` tag. hopefully people don't accidentally get it from npm.

**Comment by anupdash1991** [comment]
Hi,
for me without adding the BrowserAnimationsModule was working fine day before yesterday.
the toastr was loading ..
however all of a sudden the toastrs wont come up and am getting the bellow error in console.

Found the synthetic property @flyInOut. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
ToastrModule:1
ERROR CONTEXT

now if add BrowserAnimationsModule its giving me duplicated data :(
Please help
