### ISSUE TITLE
support high resolution on images

### ISSUE THREAD

**Issue by johaven** [scttcper/ngx-toastr#281]
Hello, first of all thank you great job!
I have a request about notification images, they seem to be in low resolution :(
I think it should convert to base64 images with a size of at least 256x256 or 512x512
On retina screen or other high dpi screen it's not far from being ugly :)

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr.css#L109-L120 they're svg so they'd have to be modified

**Comment by johaven** [comment]
<img width="444" alt="capture d ecran 2017-12-03 a 18 35 22" src="https://user-images.githubusercontent.com/5459596/33527906-ce87ac56-d858-11e7-8224-4087650919b3.png">
Given the background-image data I think the resolution not exceed 128x128 from the original image. High DPI screens that scaling image divide the ratio of pixel by 2 (in general). 
Can you re-encode in base 64 with a resolution of 256x256?

**Comment by scttcper** [comment]
i didn't make them as this project is just a port to angular from the original, unfortunately.

**Comment by scttcper** [comment]
Maybe they got them from fontawesome or something. they do look familiar

**Comment by johaven** [comment]
👍

**Comment by scttcper** [comment]
not planning to merge it in just yet. feel free to copy the css and overwrite yours locally

**Comment by johaven** [comment]
Thank you 👍

**Comment by TimFerrell** [comment]
@scttcper - yep, they're from FontAwesome.
