### ISSUE TITLE
[Bug] if deactivate tapToDimiss and click on toaster instance.

### ISSUE THREAD

**Issue by BenevidesLecontes** [scttcper/ngx-toastr#282]
Hi thanks for this nice component, i found a little bug when i deactivate tapToDimiss and click on the toaster instance and after that click on any element on the body it closes the opened toaster. It happens in the demo site also.

**Comment by yarrgh** [comment]
I don't think it's an actual bug with the tap/click. When you mouseenter and mouseleave, the extended timeout kicks in. By default it is set to 1 second. By the time you mouseenter, click, mouseleave, and click on another element, the 1 second has most likely past and the toast closes.

Setting the extendedTimeout to 0 will disable the timeOut after you mouseleave.

**Comment by BenevidesLecontes** [comment]
@yarrgh thanks, i set the extendedTimout 0 and timeout to 0 and is working fine, but i don't think that is correct to have two options to disable this behaviour.

**Comment by yarrgh** [comment]
The original purpose of this library was to port the existing javascript toastr over to Angular. It's an option that is in the original library and was included in this library as well. We've had to deviate a bit to make certain things work with Angular and have added a few enhancements here and there.

Having said that, I don't see a reason we can't deviate a bit more and maybe add a possibly add a convenience configuration property to disable both time outs. Maybe something like `disableTimeOut` which would default to false?

**Comment by BenevidesLecontes** [comment]
@yarrgh yes i agree with this this name and default value.
