### ISSUE TITLE
HTML Message issue

### ISSUE THREAD

**Issue by emrealparslan93** [scttcper/ngx-toastr#283]
Hi,

I want to use html in toastr's message but I couldn't run it properly.
I use Angular 5 and "ngx-toastr": "7.0.2".

Here is my code:

    `this.toastr.success('Click here to refresh dashboard',
                   '<p>A new device is connected' 
                        + device.model + '<br>' 
                        + device.systemName + ' ' + device.systemVersion + '<br>' 
                        + 'FineDine ' + device.appVersion + '</p>', {
                            enableHtml: true,
                            closeButton: true,
                            timeOut: 10000
                        });`

And it shows me this:

![toastr](https://user-images.githubusercontent.com/9310800/33555829-d749b25c-d912-11e7-8f21-28bbe2c9bd62.png)

Can you tell me where I'm wrong?

**Comment by yarrgh** [comment]
The issue is that, currently, the toast title can't have HTML, only the message/body of the toast.

**Comment by emrealparslan93** [comment]
Oh I see, it's my mistake. Sorry for this idiotic question. I though first parameter is title and second is message at first...
