### ISSUE TITLE
On css custom class close button and click to dimiss not working

### ISSUE THREAD

**Issue by filipemansano** [scttcper/ngx-toastr#285]
I used the bootstrap classes to customize toastr

 toastClass: 'alert',
  iconClasses: {
    error: 'alert-error',
    info: 'alert-info',
    success: 'alert-success',
    warning: 'alert-warning',
  }

but with this classes, the close button, and click to dimiss not working...

**Comment by yarrgh** [comment]
Add this to your css: 

```css
.alert {
  pointer-events: auto;
}
```

**Comment by filipemansano** [comment]
@yarrgh Thanks ! this css fix the problem, grateful to inform me about the danger class had not noticed too
