### ISSUE TITLE
Use in static method?

### ISSUE THREAD

**Issue by clabough** [scttcper/ngx-toastr#286]
Is there a way to use this in a static method?

**Comment by scttcper** [comment]
does it not work in static methods?

**Comment by clabough** [comment]
I cannot find a way to get an instance of an injectable service within a static method of a class. Items passed into the constructor are not accessible to static methods, because they're instance variables.

**Comment by clabough** [comment]
Thanks, that got me to where I needed. 

Here's a simplified snippet of what I'm doing:


```javascript
export class ToastrClass {
	public static toastr: ToastrService;

	constructor(toastrService: ToastrService) {
		ToastrClass.toastr = toastrService;
	}
}

export class Utils {
	static showErrorMessage(msg: string) {
		ToastrClass.toastr.error(msg);
	}
}
```
