### ISSUE TITLE
disableTimeOut is not defined on IndividualConfig interface

### ISSUE THREAD

**Issue by minuz** [scttcper/ngx-toastr#288]
Hi, on the documentation there's a property called `disableTimeOut` but that is not defined on the `IndividualConfig` interface and therefore, prevents the ts compilation. Is that property available on the component or has it been deprecated?

**Comment by yarrgh** [comment]
It's pending release. It'll be out soon.

**Comment by scttcper** [comment]
7.1.0 should have it

**Comment by yarrgh** [comment]
That's right. I didn't realize that it had been released a little while ago.

**Comment by minuz** [comment]
Thanks! I’ll update my solution with the new version!
