### ISSUE TITLE
Toastr styles not getting applied in webpack

### ISSUE THREAD

**Issue by susisumesh** [scttcper/ngx-toastr#289]
Hi,

I can create the toastr using ToastrService from ngx-toastr . But styles are not getting applied to it. 

1.) Tried loading toastr.css in component Styleurls.
2.) Override styles in component css 

but no joy..

I am using webpack for build. how to apply style to toastr component?

**Comment by yarrgh** [comment]
> Override styles in component css

That won't work since component css is meant for just the component itself.

> I am using webpack for build. how to apply style to toastr component?

Are you using angular-cli or another starter template? If you're using angular-cli, there's documentation in the README. If you're using a different starter template or rolling your own webpack config, you'll need to add the toastr.css to the webpack config and import the css into your main module file.

Something like:
`import '../node_modules/ngx-toastr/toastr.css';`

**Comment by johaven** [comment]
i got this error on build:

```javascript
Module build failed:
  @return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="' + $viewbox + '"><path fill="' + rgba($fill-color, 0.999999) + '" d="' + $path + '"/></svg>';
                                                                                             ^
      Argument `$color` of `rgba($color, $alpha)` must be a color

Backtrace:
	node_modules/ngx-toastr/toastr-bs4-alert.scss:121, in function `rgba`
	node_modules/ngx-toastr/toastr-bs4-alert.scss:121, in function `svg-factory`
	node_modules/ngx-toastr/toastr-bs4-alert.scss:128
      in /Users/johaven/Documents/Perso/Sync-in/Web2/node_modules/ngx-toastr/toastr-bs4-alert.scss (line 121, column 95)
Error:
  @return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="' + $viewbox + '"><path fill="' + rgba($fill-color, 0.999999) + '" d="' + $path + '"/></svg>';
                                                                                             ^
      Argument `$color` of `rgba($color, $alpha)` must be a color
```

**Comment by yarrgh** [comment]
@johaven could you open a new issue? That error is completely separate from the one in this issue.

**Comment by johaven** [comment]
Sorry no errors, i forget to put the main scss :)
