### ISSUE TITLE
Add toastr example

### ISSUE THREAD

**Issue by yarrgh** [scttcper/ngx-toastr#291]
![ngx-toastr-example](https://user-images.githubusercontent.com/1577822/33684957-412d30c4-da8d-11e7-90fc-c2d61d6df2fa.png)

Dummy issue to add image to github

**Comment by scttcper** [comment]
yeah snuck it into that pr from your comment on the other one

**Comment by yarrgh** [comment]
I've seen other repos doing this and I was curious. I was going to suggest that you add it but decided at the last moment that it didn't matter much. Just helps locally when you change images so that you can see the changes before they hit github
