### ISSUE TITLE
Config property disableTimeOut does not exist

### ISSUE THREAD

**Issue by filipemansano** [scttcper/ngx-toastr#294]
i try to remove timeOut using the **disableTimeOut** property 

https://github.com/scttcper/ngx-toastr#options

> disableTimeOut | boolean | false | Disable both timeOut and extendedTimeOut

`this.ToastrService.info('wait for search.','Searching',{
        disableTimeOut: true
    });`

but i recive this message error

`ERROR TS2345: Argument of type '{ disableTimeOut: boolean; }' is not assignable to parameter of type 'Partial<IndividualConfig>'.
  Object literal may only specify known properties, and 'disableTimeOut' does not exist in type 'Partial<IndividualConfig>'.`

**Comment by scttcper** [comment]
What version are you using

**Comment by filipemansano** [comment]
"ngx-bootstrap": "^2.0.0-beta.9"

**Comment by scttcper** [comment]
maybe do npm install again and make sure you really have it. Its for sure in there.

Or check the package.json `cat node_modules/ngx-toastr/package.json`

**Comment by filipemansano** [comment]
I removed it, and installed it again, it upgraded to version 8 and it worked! thanks!
