### ISSUE TITLE
Does not work on IE11

### ISSUE THREAD

**Issue by lazyspark** [scttcper/ngx-toastr#295]
Hi,

The examples at https://scttcper.github.io/ngx-toastr/ does not work on IE 11 (it shows loading message and page itself is not loaded) with following console error -

```

SCRIPT5022: Exception thrown and not caught
File: polyfills.24a61b06b1ef92a4c221.bundle.js, Line: 1, Column: 104056

```

Is this because of web animations polyfill?

Thanks.

**Comment by yarrgh** [comment]
IE11 needs polyfills. The demo site doesn't include the polyfills by default. There's a handful of polyfills that need to be uncommented (and one installed via npm). Not sure how many are necessary to get the demo site working in IE 11. I can play with this a open a PR

**Comment by lazyspark** [comment]
Thanks worked after enabling default IE11 polyfills as suggested by angular cli
