### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by klanglie** [scttcper/ngx-toastr#297]
I am working on a large project with many players. Politics is preventing me from upgrading to Angular 5 even though I have a branch that works fine. Anyhow, I am forced to use Angular 2.0.0 / TypeScript 2.0.5 for now. I would like to use this component along with animations. Are there any restrictions you know of that might prevent me from using it? I can understand if no-one has tried this in Angular 2.0.0. Thanks!

**Comment by scttcper** [comment]
You can try `ngx-toastr@4.4.1` as that would be the latest version that supports angular 2. The latest versions require 5
