### ISSUE TITLE
Utilize in Angular 4 application

### ISSUE THREAD

**Issue by shaikhspear16** [scttcper/ngx-toastr#301]
Hey,

We have an Angular 4 application and wish to utilize the toaster. What version of ngx-toastr is stable with Angular 4?

```
 "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
```

P.S: We will not be upgrading this application to Angular 5 any sooner to be consistent with other applications in our ecosystem. Hence, Angular 4.

**Comment by scttcper** [comment]
try `ngx-toastr@6.4.1-beta.0` I believe this was the last available angular 4 version.
