### ISSUE TITLE
Metadata version mismatch for module

### ISSUE THREAD

**Issue by jschneiders** [scttcper/ngx-toastr#303]
Someone had this error?
Metadata version mismatch for module /home/jschneiders/Dev/kondoup/kondoup-frontend-v2/node_modules/ngx-toastr/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/jschneiders/Dev/kondoup/kondoup-frontend-v2/src/app/app.module.ts, resolving symbol AppModule in /home/jschneiders/Dev/kondoup/kondoup-frontend-v2/src/app/app.module.ts, resolving symbol AppModule in /home/jschneiders/Dev/kondoup/kondoup-frontend-v2/src/app/app.module.ts

Here are the dependencies:
"dependencies": {
    "@angular/animations": "^5.0.3",
    "@angular/common": ">=4.0.0-beta <5.0.0",
    "@angular/compiler": ">=4.0.0-beta <5.0.0",
    "@angular/core": ">=4.0.0-beta <5.0.0",
    "@angular/forms": ">=4.0.0-beta <5.0.0",
    "@angular/http": ">=4.0.0-beta <5.0.0",
    "@angular/platform-browser": ">=4.0.0-beta <5.0.0",
    "@angular/platform-browser-dynamic": ">=4.0.0-beta <5.0.0",
    "@angular/router": ">=4.0.0-beta <5.0.0",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "line-awesome": "github:icons8/line-awesome",
    "lodash": "^4.17.4",
    "mdi": "^2.0.46",
    "ng2-handsontable": "^1.0.3",
    "ng2-materialize": "^1.7.2",
    "ngx-toastr": "^8.0.0",
    "rxjs": "^5.1.0",
    "save": "^2.3.2",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-beta.32.3",
    "@angular/compiler-cli": ">=4.0.0-beta <5.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0-beta.4",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.1.0"
  }

**Comment by scttcper** [comment]
On the latest version angular 5 is required and is why you're getting that error.

**Comment by jschneiders** [comment]
Wich version is for angular 4?

**Comment by jschneiders** [comment]
There is something strange going on. The webpack give me this error and, if I change a file and the webpack recompile it works fine.

**Comment by scttcper** [comment]
try `ngx-toastr@6.4.1-beta.0` I believe this was the last available angular 4 version.

**Comment by scttcper** [comment]
@calleja23 yes only 6.4.1.beta

**Comment by calleja23** [comment]
> @scttcper thanks!!
