### ISSUE TITLE
Can we implement a better isDuplicate(message) method?

### ISSUE THREAD

**Issue by burakkilic** [scttcper/ngx-toastr#306]
Hello,

I was checking the source code of Toastr and find out this isDuplicate method:

    isDuplicate(message) {
        for (let i = 0; i < this.toasts.length; i++) {
            if (this.toasts[i].message === message) {
                return true;
            }
        }
        return false;
    }

which prevents duplicate Toastr messages. 

But my concern is, sometimes we should be able to show the same message. For example

You have a new order!
You have a new feedback!

I know we can add some strings depending on the time, but can we make it something more advanced? Like an id to check, or a timestamp maybe?

**Comment by scttcper** [comment]
I don’t understand your use case. You have a new order and you have a new feedback are not duplicates?

**Comment by scttcper** [comment]
Unless you want to say "you have a new order" again but only if its been x seconds.

**Comment by burakkilic** [comment]
I mean, there is a new feedback, but it is not duplicate. I passed this problem by adding time with fractional seconds.

**Comment by yarrgh** [comment]
This defeats the purpose of turning on `preventDuplicates`. If you need duplicate messages to appear, keep `preventDuplicates` disabled.

**Comment by burakkilic** [comment]
Because of socket.io, sometimes messages are triggered multiple times in our system. That's why we use preventDuplicates. In some case, we need to show toaster with the same message multiple times. That was what I meant. But we can close the thread since I solved that adding the time at the end of the message.
