### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by rsilva1959** [scttcper/ngx-toastr#309]
ERROR in Error: Metadata version mismatch for module D:/OneDrive/.../.../.../node_modules/ngx-toastr/index.d.ts, found version 4, expected 3, resolving symbol ...

I'm using 
    angular: "^4.4.3",
    "ngx-toastr": "^8.0.0"

No errors with
    "ngx-toastr": "6.4.1-beta.0"

Pls help! Thanks.

**Comment by yarrgh** [comment]
Duplicate of #303
