### ISSUE TITLE
Include CSS at Component level to remove including CSS in Angular CLI

### ISSUE THREAD

**Issue by davidgumzchoi** [scttcper/ngx-toastr#312]
I would like to add an enhancement that removes Step 1 by adding the CSS to the component level to encapsulate and avoid the slight bloat of adding CSS to the angular-cli.json file and not having to worry about importing when using the ngx-toastr module. What are your thoughts?

**Comment by scttcper** [comment]
the main issue is the `toast-container` is not an angular component and would have to have a way to apply styles. Also, everyone that wants to slightly change color or size would need a way to do that or be forced to extend the component.

**Comment by davidgumzchoi** [comment]
I see, I suppose currently it's being used as a directive. What if we made the `toast-container` a component, to accept an input of a backgroundColor and textColor?

<toast-container [backgroundColor]="customColor" [textColor]="textColor"></toast-container>

Not sure what's a better method for users, but I just wanted to express my thoughts on how to improve your project. Thanks for getting back to me and letting me know your thoughts!

**Comment by scttcper** [comment]
Going to leave this as external css on this project.

**Comment by ChandraTerli** [comment]
ngx-toastr styles are not getting applied, any help?
this( <link rel="stylesheet" type="css" href="../node_modules/ngx-toastr/toastr.css"/>) is what I am referring in my index.html. I tried to refer the same in .CLI file and also tried to copy the into Styles.css and referred but still not working.

**Comment by ChandraTerli** [comment]
<link rel="stylesheet" type="css" href="../node_modules/ngx-toastr/toastr.css"/>

**Comment by ChandraTerli** [comment]
"../node_modules/ngx-toastr/toastr.css"

**Comment by scttcper** [comment]
@ChandraTerli https://github.com/scttcper/ngx-toastr#setup

**Comment by ChandraTerli** [comment]
I am using angular-cli and tries with below option but still style does not apply.
"styles": [
  "styles.scss",
  "../node_modules/ngx-toastr/toastr.css"
]

**Comment by Julesbrn** [comment]
I was having a similar issue.  I put the toastr.css in 
src/assets/css/toastr.css
and added
<link href="assets/css/toastr.css">
to the top of index.html. After that it seems to work. I don't know exactly what version, but I'm pretty sure I'm on angular5.

**Comment by ChandraTerli** [comment]
Thank you! I tried that but not sure why it does not work. I am using Angular 6.0.1

**Comment by scttcper** [comment]
just tried it using angular-cli 6

```ts
"styles": [
	"src/styles.css",
	"node_modules/ngx-toastr/toastr.css"
],
```

**Comment by ChandraTerli** [comment]
ok, I got it working now when  removed the type='css' from the link
<link rel="stylesheet" href="assets/toastr.css" />.
Thank you! again both of you. I really appreciate it.
