### ISSUE TITLE
No mixin named border-radius

### ISSUE THREAD

**Issue by AmrineA** [scttcper/ngx-toastr#318]
I'm attempting to use the bootstrap 4 styles. We have an angular-cli projects and inside the angular-cli.json file I've added the following to my styles.

`"styles": [
			"../node_modules/bootstrap/scss/bootstrap.scss",
			"../node_modules/ngx-toastr/toastr-bs4-alert.scss",`

For whatever reason, when I run `ng build` I end up getting the error message "No mixin named border-radius". I made sure to put them in the correct order, but for whatever reason, it does not want to build properly. Any ideas?

**Comment by scttcper** [comment]
I think with the variables I used from bootstrap. They have to both be imported into a single scss file in your project and then that gets loaded by angular-cli

**Comment by AmrineA** [comment]
Thank you. that appears to be the issue I'm having. It's not respecting the
order they're placed into the cli config file. Thanks!

**Comment by RezaRahmati** [comment]
I have same issue, would you please describe it more

**Comment by yarrgh** [comment]
In your `styles.scss` import bootstrap (or just bootstrap variables) then import the scss in this library.

example:
```scss
@import '~bootstrap/scss/variables';
// or
@import '~bootstrap/scss/bootstrap';

// then import toastr scss
@import '~ngx-toastr/toastr-bs4-alert.scss';
```

If you don't have styles.scss and instead just have styles.css, just rename it to `styles.scss`

**Comment by RezaRahmati** [comment]
Thanks for fast response
Adding `@import '~bootstrap/scss/bootstrap';` solved the issue

FYI Adding `functions` and `variables` will cause the below error as well
`Argument '$color' of 'darken($color, $amount)' must be a color`

**Comment by yarrgh** [comment]
That's right. If you don't want to bring in all of bootstrap, you'd need to bring in the mixins as well as the variables and functions

**Comment by Sapulu** [comment]
Just had the same error, but in my case it was caused by  `@use`:

styles.scss:
```
@use "bootstrap/scss/bootstrap";
@use "bootstrap-icons/font/bootstrap-icons";
```

After changing them to `@import` everything was fine.
