### ISSUE TITLE
TimeOut Expired Event Callback?

### ISSUE THREAD

**Issue by brianushman** [scttcper/ngx-toastr#325]
Good morning,

Is there an easy way to hook into the TimeOut expired event?  I'd like to be able to receive a notification if the user did not manually dismiss the toast but instead let it dismiss from letting the timer run out.

Thanks!

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr#toastr-service-methods-return

```
  /** triggered when toast is destroyed */
  onHidden: Observable<any>;
```

**Comment by scttcper** [comment]
I guess you'd have to subscribe to onTap as well

**Comment by brianushman** [comment]
Thanks for the feedback!

**Comment by akash-potdar7** [comment]
how to make use of this in the Custom Toast?
