### ISSUE TITLE
Using toast in ErrorHandler not working (per directions in FAQ)

### ISSUE THREAD

**Issue by crhistianr** [scttcper/ngx-toastr#327]
ngx toast version: 8.1.1;
angular version: 5.0.0;
rxjs version: 5.5.2

I've verified toastr works in the app, just can't seem to get it to work as part of my custom error class that extends `ErrorHandler`.

My class is defined as:

```javascript 
import { ErrorHandler, Inject, Injector} from '@angular/core';
import { ToastrService } from 'ngx-toastr';

export class AppErrorHandler implements ErrorHandler {
    constructor(@Inject(Injector) private injector: Injector) { }

    private get toastrService(): ToastrService {
        return this.injector.get(ToastrService);
    }

    public handleError(error: any): void {
        this.toastrService.error('Show me an error message');
        throw error;
    }
}
```

and then in root module:

```javascript
import { AppErrorHandler } from './config/error-handling.config';
@NgModule({
  // ... other imports, declarations, etc.
  providers: [
    { provide: ErrorHandler, useClass: AppErrorHandler },
    // ... other providers
  ]
})
export class AppModule {}

```

In my component I'm calling a http method with some invalid parameters and then: `throw error` in the error handler.

```
.subscribe(
response => { console.log(response) }',
error => { throw error; }
)
```

I can see my custom error handler class is called but no toast appears. The instructions in the FAQ seem to be a response to ngx-toastr v5.2.4, is there possibly something that was introduced that changes how this should be done?

**Comment by yarrgh** [comment]
It should work. You will want to turn on `onActivateTick` for that toast so that change detection runs on it.

This plunker is using ngx-toastr 8.1.1:
https://plnkr.co/edit/0pWbqD?p=preview

**Comment by crhistianr** [comment]
That definitely did the trick! Appreciate your help :)

**Comment by faiaz000** [comment]
well i faced the same problem the applied the code  as above. But the toster message shows only after i click twice

**Comment by michelepatrassi** [comment]
@yarrgh thanks for your solution! I'll add this alternative which is more explicit for me

```
import { NgZone } from '@angular/core';

constructor(private injector: Injector, private zone: NgZone) {}

handleError(e: any) {
  this.zone.run(() => this.toastr.error('Something went wrong!'));
}

```

**Comment by williamdes** [comment]
See: https://github.com/scttcper/ngx-toastr/issues/804 for cyclic dependency issues with Angular 9

**Comment by Prinsn** [comment]
Just making note that this issue is what helped me resolve it in my case.
