### ISSUE TITLE
ERROR TypeError: Cannot read property 'onAction' of null

### ISSUE THREAD

**Issue by kaffeeserver** [scttcper/ngx-toastr#331]
Hello,

as suggested in https://github.com/scttcper/ngx-toastr/issues/174 I tried the following code to call a function after clicking on my custom toastr component::

```
// component that uses the toastr
const mm = this.toastrService.show('yas')
mm.onAction.subscribe((action) => console.log(action));
```

and 

```
// custom toastr component
click() {
     this.toastPackage.triggerAction('confirmed');
}
```

This works for most of the time but after a page reload (sometimes with browser cache reset) for example mm is null and that throws the following error:

`ERROR TypeError: Cannot read property 'onAction' of null`

The toastr message will appear yet andif clicked the callback will be executed.

Can you please help?

By the way: nice work :+1: 

Best regards
Christoph

**Comment by scttcper** [comment]
are you using preventDuplicates?

**Comment by kaffeeserver** [comment]
Yes I do. I'll give it a try without this option later this evening. Thank
you.

Am 05.02.2018 5:38 nachm. schrieb "Scott Cooper" <notifications@github.com>:

**Comment by kaffeeserver** [comment]
Hello,

it seems to work fine if I dont use preventDuplicates.

Thank you very much!

Christoph

**Comment by scttcper** [comment]
preventDuplicates returns null if a duplicate is prevented.
