### ISSUE TITLE
Docs on usage

### ISSUE THREAD

**Issue by jglisson** [scttcper/ngx-toastr#338]
Do you have any docs that describe the various options available when calling the toastr (from TypeScript)?

https://scttcper.github.io/ngx-toastr/

I'd like to use a few of the options you have in this sample.

Thanks!

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr#options ?

**Comment by jglisson** [comment]
Thanks...I had seen this. I was wondering more about the class options available to pass into the object. For instance, { positionClass: 'toast-top-right' }. What are the other options? I found what I needed by inspecting the toastr.css file.
