### ISSUE TITLE
Multiple icons per display.

### ISSUE THREAD

**Issue by itsdax** [scttcper/ngx-toastr#346]
I'm getting mutiple icons appearing for my toastr. 

I have Font awesome 5 included with my project. Could that be an issue?

![alt text](https://i.imgur.com/CFcYjnW.png)
![alt text](https://i.imgur.com/tGAy4l1.png)
![alt text](https://i.imgur.com/5sRroT3.png)

![alt text](https://i.imgur.com/2hhdN2A.png)

**Comment by itsdax** [comment]
Found issue - conflicting css from previous template. Nothing to do with the library itself

**Comment by ssmore6** [comment]
Hi, I'm having the same issue. How did you resolve this?
