### ISSUE TITLE
NullInjectorError: No provider for ToastsManager!

### ISSUE THREAD

**Issue by mediasoftpro** [scttcper/ngx-toastr#368]
Hello, i integrated ngx-toastr in my angular 5 app utilizing angular cli 1.7 as mentioned in installation instruction but its not working. 

i: import { ToastrModule } from 'ngx-toastr';

ii:  ToastrModule.forRoot(),

in toaster service

const params = {
       timeOut: 3000,
       closeButton: true,
    };

    if (css === 'bg-success') {
        this.toastrService.success(text, title, params);
    } else if (css === 'bg-error') {
        this.toastrService.error(text, title, params);
    } else {
        this.toastrService.info(text, title, params);
    }

but my application broken with error

Error: StaticInjectorError(AppModule)[AppComponent -> ToastsManager]: 
  StaticInjectorError(Platform: core)[AppComponent -> ToastsManager]: 
    NullInjectorError: No provider for ToastsManager!
Stack trace:
_NullInjector.prototype.get@webpack-internal:///./node_modules/@angular/core/esm5/core.js:1218:19
resolveToken@webpack-internal:///./node_modules/@angular/core/esm5/core.js:1516:17
tryResolveToken@webpack-internal:///./node_modules/@angular/core/esm5/core.js:1458:16
StaticInjector.prototype.get@webpack-internal:///./node_modules/@angular/core/esm5/core.js:1326:20
resolveToken@webpack-internal:///./node_modules/@angular/core/esm5/core.js:1516:17
tryResolveToken@webpack-internal:///./node_modules/@angular/core/esm5/core.js:1458:16
StaticInjector.prototype.get@webpack-internal:///./node_modules/@angular/core/esm5/core.js:1326:20
resolveNgModuleDep@webpack-internal:///./node_modules/@angular/core/esm5/core.js:11066:12
.....

Can someone help me what will be the cause of issue.

**Comment by yarrgh** [comment]
ngx-toastr doesn't have a `ToastsManager`. This isn't an issue with ngx-toastr.

My guess is that you have an old implementation of ToastsManager that was only partially removed from your app. Your AppComponent still wants it injected and causing the error.

**Comment by mediasoftpro** [comment]
strange, i uninstall package that i have doubt 'npm uninstall ng2-toastr/ng2-toastr' , still receiving same error event there is no Toasts related other component that may conflict but i am investigating.

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr#faq #1

**Comment by mediasoftpro** [comment]
Thanks for your quick support. my issue resolved. :)
