### ISSUE TITLE
Using Toastr with Ionic 3

### ISSUE THREAD

**Issue by vuk** [scttcper/ngx-toastr#371]
I'm trying to use Toastr with Ionic 3, and building development build works perfectly, but when I try to build application with --prod flag, I get this error 

```
    sass: node_modules/ngx-toastr/toastr-bs4-alert.scss, line: 63 
            Undefined variable: "$alert-border-radius". 
```

Any idea why this happens. I don't want to include whole Bootstrap just to use Toastr, and when I empty the toastr-bs4-alert.scss build passes fine

**Comment by scttcper** [comment]
in order to use it without bootstrap it would have to be compiled w/ defaults and copied in or you can import only the functions and variables before __toastr-bs4-alert.scss__

```scss
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
```

**Comment by vuk** [comment]
It worked. Just had to use 

```
@import "../../node_modules/bootstrap/scss/functions";
@import "../../node_modules/bootstrap/scss/variables";
```

**Comment by ziishaned** [comment]
For me I have to import `_border-radius.scss` also from `mixins` directory.

```scss
@import "~bootstrap/scss/mixins/_border-radius.scss";
@import "~bootstrap/scss/_functions.scss";
@import "~bootstrap/scss/_variables.scss";
```
