### ISSUE TITLE
undefined when trying to acces .toastRef.componentInstance

### ISSUE THREAD

**Issue by Johannes0501** [scttcper/ngx-toastr#374]
Hi, Im getting an undefined when trying to access  activeToast.toastRef.componentInstance

    const a = this.toasterService.success('Your case was successfully created', 'Case created', {
      positionClass: 'toast-bottom-right'
    });

    console.log(a.toastRef.componentInstance);

on .toastRef i get
_overlayRef: OverlayRef, _afterClosed: Subject, _activate: Subject, _manualClose: Subject

Any idea whats going wrong?

**Comment by scttcper** [comment]
do you have any other settings? are you using maxOpened?

**Comment by Johannes0501** [comment]
Hey, no just default settings, i only add the positionClass

**Comment by yarrgh** [comment]
toastRef doesn't have a componentInstance property. That's why it's undefined

**Comment by Johannes0501** [comment]
in the file toast-injector.d.ts 
there is following line 
/** The instance of component opened into the toast. */
    componentInstance: T;

what im trying to do is pass a variable to my customToaster that has a link with an id(the variable im passing)

**Comment by yarrgh** [comment]
Sorry I did a quick look through the code on my phone and didn't see the property. It's there but isn't used/assigned anywhere from what I can see. Again looking on my phone so I could be missing something. @scttcper can you confirm?
