### ISSUE TITLE
maxOpened not working

### ISSUE THREAD

**Issue by HobNobblin** [scttcper/ngx-toastr#380]
From the latest npm package (8.3.0) it looks like the maxOpened parameter is not yet working/implemented.

**Comment by scttcper** [comment]
seems fine to me. how are you trying to use it?

**Comment by HobNobblin** [comment]
It works from the code in Git but when using the npm package the code for maxOpened is missing.  I'm trying from both the global and local settings

**Comment by yarrgh** [comment]
I've just downloaded the latest npm package (8.3.1) and can confirm that it is indeed there.

```ts
@NgModule({
  imports: [
    ToastrModule.forRoot({
      maxOpened: 2
    }),
  ]
})
```

**Comment by HobNobblin** [comment]
I see it was just updated to 8.3.1 about a half hour ago...nice
However, though I've implemented it in my app.module as such:

```
ToastrModule.forRoot({
    timeOut: 5000,
    positionClass: 'toast-bottom-full-width',
    preventDuplicates: true,
    tapToDismiss: true,
    maxOpened: 1
})
```

I'm still getting stacked notifications.

**Comment by yarrgh** [comment]
Ah yes, now I see it. Interesting how the demo works.

**Comment by yarrgh** [comment]
What's interesting is that it shows up, but nothing happens with the toasts that go over the maxOpened limit. The progress bars don't animate until it should show

**Comment by yarrgh** [comment]
It's a styling issue. You can duplicate this on the demo by launching the toast without animations. Do you, by chance, not have `BrowserAnimationsModule` imported into your app?

If not, then the animations don't work and the style doesn't get applied, because of that.

**Comment by yarrgh** [comment]
The Toast without animations never sets the style to `display: hidden` when it is inactive and thus shows regardless of if the limit was reached

**Comment by HobNobblin** [comment]
Yes, I have BrowserAnimationsModule imported.

**Comment by scttcper** [comment]
was it by chance limiting it to 2 toasts? i think i made the mistake of using `>=` instead of `>` which i've changed in 8.3.2

**Comment by HobNobblin** [comment]
It's not.  If I stack up 4 all 4 will show when configured for 1

**Comment by HobNobblin** [comment]
Updated to 8.3.2.  It's all working now.  Thank you!

**Comment by b3hz4d** [comment]
I'm using version 8.8.0 and maxOpened not working!
And I'm using angular 5.2.9
