### ISSUE TITLE
Global Setting to clear modal on new incoming toastr?

### ISSUE THREAD

**Issue by seanmavley** [scttcper/ngx-toastr#397]
I know of the `toastr.clear()`, which clears all toasts.

However, I wanted to find out if there's any way to add a global setting, something like `{ clearOnNew: true }` which would close any toasts before any new toast shows.

Currently I clear them manually which is fine. Was looking for a global setting.

**Comment by scttcper** [comment]
![screen shot 2018-04-05 at 9 55 17 am](https://user-images.githubusercontent.com/1400464/38380065-77f82734-38b7-11e8-87bf-c8f4dd750f30.png)

you can setup the demo to do this and with settings

**Comment by seanmavley** [comment]
Perfect!
