### ISSUE TITLE
Error on lazy loaded module that ToastrModule has already been loaded but it hasn't.

### ISSUE THREAD

**Issue by crhistianramirez** [scttcper/ngx-toastr#400]
I get the following error:
Error: ToastrModule is already loaded. It should only be imported in your application's main module.

I did a ctrl-f on my project and confirmed its only getting loaded in my shared module. When I hit the lazy module the error pops up. 

Is this happening because I'm loading it in a shared module instead of app.module.ts? Should that matter? I bundled it up with my shared module so I wouldn't have to pollute something like app.module.ts

**Comment by tomgruszowski** [comment]
[Same as issue 415](https://github.com/scttcper/ngx-toastr/issues/415)

**Comment by yarrgh** [comment]
Closing as this is a duplicate.
