### ISSUE TITLE
Question: Boostrap4 

### ISSUE THREAD

**Issue by rafaelvicio** [scttcper/ngx-toastr#414]
How do I activate the layout of boostrap4 in my toast?

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr#setup

**Comment by rafaelvicio** [comment]
i'm use this:

```
"styles": [
  "styles.scss",
  "../node_modules/ngx-toastr/toastr.css"
]
```

So how? Or just using scss?
