### ISSUE TITLE
Reset Timeout on duplicate toast (preventDuplicate = true)

### ISSUE THREAD

**Issue by dinusuresh** [scttcper/ngx-toastr#416]
Currently, when a toast is active and a duplicate toast is invoked, the active toast's timeout does not reset. I would like to reset the timeout to the global value when a duplicate toast is invoked.

I would appreciate if this is considered to be a feature request. Or I would appreciate help on how I can achieve this. Thanks

**Comment by akash-potdar7** [comment]
@dinusuresh 
A very must requirement that you've pointed out. Even I came across this requirement.
And also do you know how to club two or more errors into a similar toast over time, like without needing to show up a new toast. Just populating into the same toast.

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr/releases/tag/v8.9.0

**Comment by dinusuresh** [comment]
@akash-potdar7
Now that you can reset timeout on duplicate, on condition `preventDuplicates=true`, you can append messages to the existing toast. However, this would be sensible if the toasts are all the same type (all errors or all success and like)

**Comment by dinusuresh** [comment]
@akash-potdar7 
Please check MikeAlexMartinez comment in https://github.com/scttcper/ngx-toastr/issues/493 (its the first comment in the issue)

**Comment by akash-potdar7** [comment]
Great, @dinusuresh : Let me try that out. Seems to be an ideal solution.
