### ISSUE TITLE
Change animation without writing a new component?

### ISSUE THREAD

**Issue by jherman** [scttcper/ngx-toastr#417]
Is this possible?  In the demo, the pink toast has a great animation but I don't want to bring in the whole component and I would still like to be able to use calls to `.success`, `.error`, etc.  Can anyone point to the right direction, or better yet, give me an example?  It would be greatly appreciated.

**Comment by jherman** [comment]
After messing around with the pink toast example, I was able to get this to work. Closing.

**Comment by imolorhe** [comment]
@jherman How did you achieve this? I also need to change the animation without writing a new component. It would also be great to document it.

**Comment by pcutler9** [comment]
this would be helpful, so i wouldn't have to write a custom component.
I'm able to replace the show animation, or at least modify it a bit, but the close animation seems to be elusive.

for the active:
#toast-container .toast {
  animation-duration: 0.75s;
  -webkit-animation-name: bounceIn;
  animation-name: bounceIn;
}

**Comment by Asmaarali** [comment]
.toast {
  animation: show_toast 0.3s ease forwards;
}
@keyframes show_toast {
  0% {
    transform: translateX(100%);
  }
  40% {
    transform: translateX(-5%);
  }
  80% {
    transform: translateX(0%);
  }
  100% {
    transform: translateX(-10px);
  }
}
