### ISSUE TITLE
SVG Icons not Displaying in IE

### ISSUE THREAD

**Issue by deisterhold** [scttcper/ngx-toastr#423]
When using the Bootstrap 4 style's the SVG images aren't displayed in Internet Explorer.
I believe it's an issue with the `svg-encode($svg)` function not having `charset=utf8` specified.

**Comment by deisterhold** [comment]
Here's was worked for me to get the icon to display, however it is displayed really small.
```
@function svg-factory($fill-color, $viewbox, $path) {
  // opacity is 0.9999 otherwise it uses a hex equivelent
  // firefox requires fill rgb
  @return '%3Csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'' + $viewbox + '\'%3E%3Cpath fill=\'' + rgba($fill-color, 0.999999) + '\' d=\'' + $path + '\'/%3E%3C/svg%3E';
}
@function svg-encode($svg) {
  @return 'data:image/svg+xml,' + $svg;
}
```

**Comment by ednjv** [comment]
I actually had the same problem, in my case I'm using sass, so I'm including the `toastr-bs4-alert.scss` file which seems to be outdated, and as you say it needs the `charset=utf8` and seems like also the width and height.

Anyway I saw the `toastr.css` file found in the root of the package and copied the `background-image` value and used it on the classes I need, e.g:

```
.toast-success {
  background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512' width='512' height='512'%3E%3Cpath fill='rgb(255,255,255)' d='M173.898 439.404l-166.4-166.4c-9.997-9.997-9.997-26.206 0-36.204l36.203-36.204c9.997-9.998 26.207-9.998 36.204 0L192 312.69 432.095 72.596c9.997-9.997 26.207-9.997 36.204 0l36.203 36.204c9.997 9.997 9.997 26.206 0 36.204l-294.4 294.401c-9.998 9.997-26.207 9.997-36.204-.001z'/%3E%3C/svg%3E");
}
```

As you can see the value is specified correctly in the `toastr.css` file but not in the `toastr-bs4-alert.scss` file
