### ISSUE TITLE
Create custom toast type

### ISSUE THREAD

**Issue by nikftw11** [scttcper/ngx-toastr#433]
I'm just wondering if it's possible to create a custom toast type? I want to have another toast type called 'Loading' to display when I'm doing some kind of loading from my backend. The icon would be an animated loading spinner.

Thank you :)

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr#using-a-custom-toast

**Comment by nikftw11** [comment]
Thanks, I don't want to get rid of the existing info/success/warning/error toasts though. Just wanted a new type, where I could call this.toastService.loading() or something like that.

**Comment by scttcper** [comment]
There's a `show` as well. Can pass your one off toast as part of the individual config.

https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toastr.service.ts#L68

**Comment by nikftw11** [comment]
Thanks for your help! For some reason I thought 'type' was required and could only be one of those listed... my bad! Thanks again.
