### ISSUE TITLE
Using in ng 5.2.10 - get msg in dbg console: ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by geetee24** [scttcper/ngx-toastr#434]
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'className: undefined'. Current value: 'className: toast-success toast'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?
    at viewDebugError (core.js:9817)

Any idea why this is happening when showing my first toast?

**Comment by yarrgh** [comment]
This is a duplicate of #160. Please refer to that issue. This is a known issue with angular that only had work arounds
