### ISSUE TITLE
Screenreader Accessibility

### ISSUE THREAD

**Issue by mitschmidt** [scttcper/ngx-toastr#444]
Thanks for this functional and lightweight toaster module, it works just fine in my project.

However, as the client came up with quite a lot of **accessibility requirements** (one of those being screenreader functionality for blind people, in this case JAWS) I was wondering if there is any option to wrap the toaster in of those aria-live regions that announce a change to **screenreaders**? 

It would be very useful to have this option, as right now JAWS does not capture the toasts at all. Several workarounds only lead to nondeterministic behavior.

Obviously this is a special case and rather low priority, but it might be nice option to have in the future.

**Comment by scttcper** [comment]
do you have a link or more details on what tags it would be?

**Comment by CodyHinze** [comment]
This feature appears to already exist and is functioning correctly on toast messages using NVDA and ChromVox. I did not test this with JAWS but should function correctly based on support for the aria-live region attribute. 

The following code is included in each of the component templates: `role="alertdialog" aria-live="polite"` & `role="alert" aria-live="polite"`.

**Comment by HadiAyoub** [comment]
@scttcper hoping this can be opened up again. Just had a user interview with a vision-impaired user. She is using JAWS on Chrome, the toasts weren't being read. I can look into why that is and what changes might need to be made for JAWS support. Can confirm that they were being read with ChromeVox and apple voice over though.

**Comment by gamoreli** [comment]
any updates?
