### ISSUE TITLE
Css and postionClass

### ISSUE THREAD

**Issue by Muhanady** [scttcper/ngx-toastr#445]
Hi there;
i was able to make toastr work, but for some how its not using the css file! 
am using angular 6
```
  "styles": [
              "src/styles.css",
              "node_modules/ngx-toastr/toastr.css"
            ],
```
beside that am not able to change the classposition globally!
```
 imports: [
        BrowserAnimationsModule,
        ToastrModule.forRoot({
            timeOut: 10000,
            positionClass: 'toast-top-right',
            preventDuplicates: true
            
        }), 
```
any idea about this?!
Note: even on individual am not able to set the position even

**Comment by Muhanady** [comment]
am using angular 6 with asp.net core. therefor i found out that angular.js have got nothing to do and with css. after adding a new folder under wwwroot/dis/ folder and added the css inside it i add a link to shared/_Layout.cshtml file the toastr worked well. since the project is asp.net core the main responsible of files is asp.net therefor angular.json have nothing to do

**Comment by scttcper** [comment]
copy and paste the css from the repo to your global styles in some form
