### ISSUE TITLE
An error occurred while running "ng build --prod --env=prod --aot=true"

### ISSUE THREAD

**Issue by JiaoHongwei** [scttcper/ngx-toastr#456]
- An error occurred while running "ng build --prod --env=prod --aot=true"

`Angular CLI: 1.5.0
Node: 8.9.3
OS: win32 x64
Angular: 5.0.2
`
> ERROR in ./node_modules/rxjs/observable/BoundNodeCallbackObservable.js
Date: Module build failed: TypeError: Cannot read property 'type' of undefined
…
 @ ./node_modules/rxjs/add/observable/bindCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./node_modules/ngx-toastr/fesm5/ngx-toastr.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts

[Reference question](https://github.com/angular/angular/issues/20095)

Look for import { Subject } from 'rxjs'   in 'ngx-toastr/fesm5/ngx-toastr.js' and replace it with import { Subject } from 'rxjs/Subject'

**Comment by JiaoHongwei** [comment]
Upgrading to TypeScript 2.6.1 also solved my issue. Thank you.
**For latest release
npm install typescript@latest --save

**Comment by yarrgh** [comment]
You can also use `rxjs-compat` for compatibility with rxjs < 6.0.0
