### ISSUE TITLE
Toasts are horizontally aligned 

### ISSUE THREAD

**Issue by Titoch** [scttcper/ngx-toastr#465]
Hello,
Trying to use this component in my Ionic project, I see that the toaster are not aligned vertically as in the demo but are horizontally aligned.
When I has a new toast with newestontop I can see that a margin is added above the previous toast, but new one is displayed on the left or right side.

This issue is visible on ngx-toastr but not in in ng2-toastr. I can use ng2-toastr, but I would prefer use ngx-toastr.

**Comment by yarrgh** [comment]
I haven't used Ionic and am unfamiliar with what may be causing the issue. If anyone has experience with Ionic and is willing to help, it would be appreciated.

**Comment by scttcper** [comment]
make sure you don't have another css rule that conflicts with ours. will reopen if there's an example we can look at.

**Comment by Titoch** [comment]
Hello.
I've just found the reason of this issue and corrected it.
In Ionic the display of toast-container is set to 'flex'.
I forced it to 'block' via CSS and then the toasters are now vertically aligned like in you demo.

.toast-container  {
  display : block;
}
