### ISSUE TITLE
Change Icon inside of individualOptions

### ISSUE THREAD

**Issue by sandroweb** [scttcper/ngx-toastr#486]
I can't change the icon only in a modal? Only in presets of GlobalOoptions?

**Comment by scttcper** [comment]
try the toastClass individual config?

**Comment by yarrgh** [comment]
I haven't tested this because I'm not in a position to do so right now but you could do something like this:

```ts
// root app NgModule
imports: [
  ToastrModule.forRoot({
    iconClasses: {
      my-custom: 'my-custom'
   }
  }),
],

// somewhere in component/service
this.toastrService.show('my-custom', 'Display my custom icon', 'Toast title');
```

Then don't forget to add the `my-custom` class to your css to override the icon and the background color that you want it to have.

**Comment by sandroweb** [comment]
Thank you people!
