### ISSUE TITLE
Update existing toast that has been displayed

### ISSUE THREAD

**Issue by alinaalam** [scttcper/ngx-toastr#493]
Let's say I have objects and I am maintaining their states. Whenever state changes, I display a toast. Currently, a new toast is displayed every time something happens. Let's say we have an object A whose state changes from stop to start. What I want is to display a toast telling about the state of Object A which is stop and then when the state changes, if that toast is still on the screen, simply rewrite its content and if it's not then show a new toast in its place. I want to be able to somehow preserve the reference of the toast and at the same time want to be able to see whether it's being displayed on the screen or not. 

I have used 'preventDuplicates' flag, but it only works if a toast is exactly same, it doesn't work if there are changes in the content

I am using: **6.4.1-beta.0** with **Angular 4**

**Comment by MikeAlexMartinez** [comment]
When you create a toast you can access the toast component instance using the object that is returned to you. In order to use the this preventDuplicates should be disabled.

e.g.

```
const toast = this.toastr.success('Something just happened');
const toastComponent = toast.toastRef.componentInstance;
setTimeout(() => 
   toastComponent.message = 'Toast message has changed'
, 3000);
```
Hopefully this helps you get started.
