### ISSUE TITLE
Font color using bootstrap 4 styling

### ISSUE THREAD

**Issue by polgiron** [scttcper/ngx-toastr#498]
Hey,

In my styles.scss I'm importing bootstrap.scss, toastr.css and then toastr-bs4-alert.
I have a little issue with styling priorities, the font color is white and should be green.

Apparently `.toast-container .toast { color: #fff }` is taking the lead on `.toast-success { color: #155724; }`.

Cheers!
Paul

**Comment by yarrgh** [comment]
What happens if you don't import toastr.css?

If you're using the toastr-bs4-alert, you shouldn't import toastr.css as well. You either use `toastr.css` or `toastr-bs4-alert`  but not both.

**Comment by polgiron** [comment]
Yes sorry I didn't realise it was one or the other.
The font color is right now, loading only the bs4 file.

I get this issue about the closing button now: https://github.com/scttcper/ngx-toastr/issues/427

**Comment by yarrgh** [comment]
Closing this issue since the original issue is not resolved. We'll track the button issue in the other issue (which now has a workaround until the fix can be published)
