### ISSUE TITLE
preventDuplicates not working properly

### ISSUE THREAD

**Issue by meta72** [scttcper/ngx-toastr#501]
When I check `preventDuplicates` and `disableTimeouts` in the demo app, then spam lots of toasts with the *Open Toast* button, I get multiple duplicates of "Title only 👊" toasts.

I guess it's the combination of text and emoji in the title, since the "😃 / Supports Emoji" toast only appears once.

**Comment by scttcper** [comment]
prevent duplicates checks the message and not the title @yarrgh 
there does always seem to be questions about this maybe we can make it more clear.
