### ISSUE TITLE
It's possible to define a Asynchronous action to dismiss the toast

### ISSUE THREAD

**Issue by JulioWar** [scttcper/ngx-toastr#504]
Hello,

I was working with`ng2-toastr` before and this was possible:
```typescript
this.toastr.warning(
            '<i class="fa fa-spinner fa-spin"></i> Descargando',
            'Alerta',
            {
              dismiss: 'controlled',
              enableHTML: true
            })
            .then((toast: Toast) => {
              // asynchronous action
              setTimeout(() => {
                  this.toastr.dismissToast(toast);
              }, 3000);
            });
```

**How can I do that with this library?**

**Comment by yarrgh** [comment]
If you're just wanting to dismiss the toast after a specific amount of time, it's by far easier to set a timeout to dismiss the toast. You can do this by passing a config object and setting the timeout.

```ts
this.toastr.success('message', 'title', { timeOut: 5000});
```

**Comment by JulioWar** [comment]
Hello @yarrgh 

Yes I know that, but If I want to create a request instead of a timeout? like this:

```typescript
this.toastr.warning(
            '<i class="fa fa-spinner fa-spin"></i> Descargando',
            'Alerta',
            {
              dismiss: 'controlled',
              enableHTML: true
            })
            .then((toast: Toast) => {
              // asynchronous action
             this.http.get('url').subscribe(() => {
                 this.toastr.dismissToast(toast);
             });
            });
```

**Comment by yarrgh** [comment]
When you open a toast you get a reference to ToastRef (if you have prevent duplicates enabled it can return null if a duplicate is detected). Using ToastRef you can close a toast. I suggest disabling the timeOut so that it doesn't close before you want it to

```ts
const toastRef = this.toastrService.success('message', 'title', { disableTimeOut: true });

this.http.get<any>(url).subscribe(x => {
    toastRef.close();
});
```

**Comment by JulioWar** [comment]
Ok Thanks @yarrgh , That's what I want

**Comment by yarrgh** [comment]
Sorry. I made a mistake. It actually returns ActiveToast (which has a reference to ToastRef)

You should actually tell toastrService to remove the Toast.

`this.toastrService.remove(activeToast.toastId);`

**Comment by JulioWar** [comment]
I'm gonna try it,thanks

**Comment by JulioWar** [comment]
I ended up  doing this: 
```typescript
const toast: ActiveToast<any> = this.toastrService.success('message', 'title', { disableTimeOut: true });

this.http.get<any>(url).subscribe(x => {
    // just to preserve the animation when it's removed
    toast.toastRef.manualClose();
});
```

Thanks for the help @yarrgh
