### ISSUE TITLE
IE 11 ease-in animation

### ISSUE THREAD

**Issue by supetronix** [scttcper/ngx-toastr#512]
Angular 6 (latest)
BrowserAnimationModule included
regular style toast
latest version of ngx-toastr
--------------

Hi,

Your demo site has nice "ease-in" animation, as tested on FireFox. I tried your sample code from GitHub website, all works fine, except that there is no "ease-in" animation on IE11. I can't run your sample website because of proxy issues at work so just curious if that is a known limitation for IE? Or am I missing something?

I previously used "angular2-notification" and it had proper ease-in animation on IE so it is possible that I am making some mistake.

Thanks

**Comment by scttcper** [comment]
i think this was a pollyfill issue. Looks to be working now

**Comment by Skr1p** [comment]
Hello, 
the Toastr-Demo stil does not work in IE11 for me. When clicking 'Open Toast' for the first time a toast shows up but after that no more toasts show up when clicking the button again.
Meanwhile  "ERROR TypeError: Object doesn't support property or method 'keys'" shows up multiple times in the console.
