### ISSUE TITLE
First toast bugged

### ISSUE THREAD

**Issue by riouf** [scttcper/ngx-toastr#517]
Hello,

I've try to use your module on my own project and I encounter a problem : the first toast generate seems to be bugged. His content is not display before a user mouseHover. The others are well formed and properly working.

I've believe a problem in my SCSS/template project, so i've try it on stackblitz : same error encounter...

![image](https://user-images.githubusercontent.com/41961051/43570193-f8fa21ae-9639-11e8-8a2f-0dac5a7c0fb7.png)

Concerning the code, you can see it on the stackblitz, it's the same of the example.

Best regards.

**Comment by yarrgh** [comment]
What's the url for the stackblitz

**Comment by babaru** [comment]
I have the same issue.

**Comment by babaru** [comment]
@riouf Adding 'BrowserAnimationsModule' to the imports part of app.module.ts can resolve this issue.

**Comment by riouf** [comment]
@babaru thanks for your answer. It works ! 👍
