### ISSUE TITLE
 argument `$color` error ionic3

### ISSUE THREAD

**Issue by MarwaAbuEssa** [scttcper/ngx-toastr#523]
hi,
i'm using latest version of ngx-toastr v 8.10.0 and when i build my ionic project  in production using the following command :   _**ionic build --prod**_ i got the following error 

`/node_modules/ngx-toastr/toastr-bs4-alert.scss, line: 151
            argument `$color` of `rgba($color, $alpha)` must be a color Backtrace:
            node_modules/ngx-toastr/toastr-bs4-alert.scss:151, in function `rgba`
            node_modules/ngx-toastr/toastr-bs4-alert.scss:151, in function `svg-factory`
            node_modules/ngx-toastr/toastr-bs4-alert.scss:159
     L150:      "' width='" + $width + "' height='" + $height + "'%3E%3Cpath fill='" +
     L151:      rgba($fill-color, 0.999999) + "' d='" + $path + "'/%3E%3C/svg%3E";`

(rgba highlighted with red color)
any help is appreciated 

regards,
Marwa

**Comment by scttcper** [comment]
how are you including toastr-bs4-alert.scss in your project

**Comment by MarwaAbuEssa** [comment]
i had installed ngx-toastr  via npm and imports it as following
import { ToastrModule, ToastContainerModule } from 'ngx-toastr';
then import the modules 
  ToastrModule.forRoot(), 
   ToastContainerModule

but not including any .scss files

**Comment by MarwaAbuEssa** [comment]
i had to mention that there is no problem when running using ionic serve but i can't build it to production

**Comment by scttcper** [comment]
if you aren't directly importing it, it shouldn't be included in build. Check with ionic settings to ignore directorys or not grab everything in node_modules.
