### ISSUE TITLE
preventDuplicates will prevent Error toasts if Warnings with the same message exist

### ISSUE THREAD

**Issue by yutamago** [scttcper/ngx-toastr#525]
Steps to reproduce:
1. Set preventDuplicates = true
2. Create a warning toast like "Server did not respond. Please try again."
3. Create an error toast with the same message
4. Error toast will not appear.

**Comment by rkettelerij** [comment]
This is by design IMHO. Prevent duplicates just means: don't ever show a toast with a duplicate message, regardless of the type of notification (info/warning/error/etc).

**Comment by scttcper** [comment]
the duplicates use the messages for now
