### ISSUE TITLE
I've tried everything but it's not working..

### ISSUE THREAD

**Issue by Juniornativa** [scttcper/ngx-toastr#536]
I'm using Angular version 6.1.1, everything looks fine, no errors output but the toast just is not showing, not even when inside a button click event...

App Module import
BrowserAnimationsModule,
ToastrModule.forRoot(),

App component
onShowToast() {
    console.log('show toast hitted');
    this.toastrService.error('test test test test test test test test test test test', 'Test', {
      timeOut: 1000000,
      closeButton: true,
      positionClass: 'toast-top-right'
    });
  }

I'm i making some mistake? i'm about to give up!

**Comment by yarrgh** [comment]
Did you add the css inside your project mentioned in the setup section of the readme?

**Comment by scttcper** [comment]
Only need one of tower-bs4-alert or toastr.css. Make sure you have the browser animations module

**Comment by Juniornativa** [comment]
Hi Scttcper, thank you all very much, there was really a problem with those css imports... Now it's working beautifully!
