### ISSUE TITLE
Production build issue

### ISSUE THREAD

**Issue by razeelmohammed** [scttcper/ngx-toastr#542]
Getting the below error while running the production build.

ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'ToastrModule' was called.

![capture](https://user-images.githubusercontent.com/3529432/44139570-7dc4c468-a088-11e8-8a9f-0160db07cdbe.JPG)

**Comment by vincent-cm** [comment]
same issue after upgrading to v9

**Comment by razeelmohammed** [comment]
@vincent-cm yes exactly

**Comment by Ristaaf** [comment]
According to this issue: https://github.com/angular/angular/issues/23609

It is not allowed to do anything apart from the return statement in a forRoot function, then you will get the Function calls are not supported problem. A const is what was added recently in the toastr.module.ts file in the forRoot function, this causes this issue. Possible workaround is to define a const toastr: ModulesWithProviders = ToastrModule.forRoot... and then import that constant in the decorator when using ToastrModule.forRoor

**Comment by thigrand** [comment]
I get the same bug in 9.1.1
