### ISSUE TITLE
gh-pages broken

### ISSUE THREAD

**Issue by jpmckearin** [scttcper/ngx-toastr#543]
I see that `gh-pages` was updated 4 hours ago. The examples no longer work.

![image](https://user-images.githubusercontent.com/6679168/44169617-a1842580-a09a-11e8-8e5d-16b388767c89.png)

**Comment by gregor-srdic** [comment]
also using the latest version of this module in my app produces this error

**Comment by yarrgh** [comment]
Yes, it only happens on a production build. I think that the code to assign the component is getting optimized away.

**Comment by scttcper** [comment]
i hate ngmodules

**Comment by yarrgh** [comment]
I'm hoping that if we move the code that merges the config into a factory function that it won't get optimized away. Trying to test it right now

**Comment by gregor-srdic** [comment]
still doesn't work for me 
```ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'success' of undefined```
