### ISSUE TITLE
Error ngx-toastr in prod version

### ISSUE THREAD

**Issue by cdchn1989** [scttcper/ngx-toastr#549]
Hi guys I have a very interesting issue, I'm using angular 6

In develop mode toastr works fine but when run ng build --prod show me this error

Cannot read property 'warning' of undefined
    at t.warning (main.21ef52a236633030a1be.js:1)
    at t.openMovimiento (main.21ef52a236633030a1be.js:1)
    at Object.handleEvent (main.21ef52a236633030a1be.js:1)
    at Object.handleEvent (main.21ef52a236633030a1be.js:1)
    at Object.handleEvent (main.21ef52a236633030a1be.js:1)
    at ai (main.21ef52a236633030a1be.js:1)
    at main.21ef52a236633030a1be.js:1
    at HTMLButtonElement.<anonymous> (main.21ef52a236633030a1be.js:1)
    at e.invokeTask (polyfills.7a0e6866a34e280f48e7.js:1)
    at Object.onInvokeTask (main.21ef52a236633030a1be.js:1)

Really I have no idea what I do wrong

My packaje.json file

{
  "name": "master",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.2",
    "@angular/cdk": "^6.4.5",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/forms": "^6.0.2",
    "@angular/http": "^6.0.2",
    "@angular/material": "^6.4.5",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/router": "^6.0.2",
    "@ng-select/ng-select": "^2.4.3",
    "core-js": "^2.5.4",
    "ngx-toastr": "^9.0.2",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.2",
    "@angular-devkit/build-angular": "~0.6.3",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.3",
    "@angular/language-service": "^6.0.2",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }
}

My angular json file 

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "master": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/master",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css",
              "node_modules/ngx-toastr/toastr.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "master:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "master:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "master:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.css"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "master-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "master:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "master"
}

![error_dev](https://user-images.githubusercontent.com/22404761/44487155-cafcfe00-a612-11e8-8387-ab16d6ca4cd4.PNG)
![error_prod](https://user-images.githubusercontent.com/22404761/44487156-cafcfe00-a612-11e8-8a63-d952e6eaf270.PNG)

**Comment by yarrgh** [comment]
I'm not able to duplicate this. I'd need to see the code to see what's happening. My guess is that the `ToastrService` that you're trying to use is not getting injected properly (why it is 'undefined').

**Comment by cdchn1989** [comment]
Hi thanks for the quickly response, remember you this issue is just in prod version, in dev mode wokr perfectly.

I inyect the module at

import { ToastrModule } from 'ngx-toastr';
imports: [ToastrModule.forRoot()]

In my component use this at

import {ToastrService} from 'ngx-toastr';
  constructor(
    public dialogRef: MatDialogRef<ModalTaza>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    public _pattern_service :PatternService,
    private _taza_service:TazaService,
    private _date_service:DateService,
    private _toastr:ToastrService,
    private _globals:Globals
  ){
  this._toastr.success('Some message','Success');
}

Best Regards

**Comment by yarrgh** [comment]
I've tested with both dev and production builds but cannot duplicate this (with ngx-toastr 9.0.2). I'm obviously doing something different than you. Which module are you importing `ToastrModule.forRoot()`. Is it lazy loaded?

**Comment by cdchn1989** [comment]
In dev mode all work good, quickly  

this is my app.module.ts

import { AppComponent } from './app.component';
import { BrowserModule } from '@angular/platform-browser';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import {MatProgressSpinnerModule,MatIconModule,MatCardModule,MatButtonModule,MatTableModule,MatProgressBarModule,MatDialogModule,MatDatepickerModule,
  MatNativeDateModule,MatInputModule,MatTooltipModule} from '@angular/material';
import { ToastrModule } from 'ngx-toastr';
import { NgSelectModule } from '@ng-select/ng-select';

import { routing, appRoutingProviders } from './routing';

//---------owner components-----------------------------//
import {tazaComponent} from './components/taza.component';
import {alumnoComponent} from './components/alumno.component';
import {matriculaComponent} from './components/matricula.component';
import {estadoComponent} from './components/estado.component';
import {ModalTaza} from './components/modal-taza.component';
import {ModalAlumno} from './components/modal-alumno.component';
import {ModalMatricula} from './components/modal-matricula.component';
import {ModalMovimiento} from './components/modal-movimiento.component';

//---------owner services---------------//
import {TazaService} from './services/taza.service';
import {AlumnoService} from './services/alumno.service';
import {MatriculaService} from './services/matricula.service';
import {PatternService} from './services/pattern.service';
import {MasterService} from './services/master.service';
import {EstadoService} from './services/estado.service';
import {DateService} from './services/date.service';
import { ApiRoute } from "./models/apiRoute";
import {Globals} from './services/global';

@NgModule({
  declarations: [
    AppComponent,tazaComponent,ModalTaza,alumnoComponent,ModalAlumno,matriculaComponent,ModalMatricula,estadoComponent,ModalMovimiento
  ],
  imports: [
    BrowserModule,CommonModule,BrowserAnimationsModule,MatProgressSpinnerModule,MatIconModule,routing,appRoutingProviders,MatCardModule,MatButtonModule,
    MatProgressBarModule,MatDialogModule,MatTableModule,HttpClientModule,ToastrModule.forRoot(),MatDatepickerModule,MatNativeDateModule,MatInputModule,FormsModule,
    NgSelectModule,MatTooltipModule
  ],
  entryComponents:[tazaComponent,ModalTaza,alumnoComponent,ModalAlumno,ModalMatricula,matriculaComponent,estadoComponent,ModalMovimiento],
  providers: [ApiRoute,TazaService,PatternService,DateService,AlumnoService,Globals,MatriculaService,MasterService,EstadoService],
  bootstrap: [AppComponent]
})
export class AppModule { }

This is an one of many components

import {Component, Inject} from '@angular/core';
import {MatDialog, MatDialogRef, MAT_DIALOG_DATA} from '@angular/material';
import {TazaService} from '../services/taza.service';
import {Taza} from  '../models/taza.model';
import {ToastrService} from 'ngx-toastr';
import {PatternService} from '../services/pattern.service';
import {DateService} from '../services/date.service';
import {Globals} from '../services/global';

@Component({
  selector: 'modal-taza',
  templateUrl: '../views/modal-taza.component.html',
})
export class ModalTaza {
  public taza:Taza;
  public date:Date;
  public patternNumber:any;
  constructor(
    public dialogRef: MatDialogRef<ModalTaza>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    public _pattern_service :PatternService,
    private _taza_service:TazaService,
    private _date_service:DateService,
    private _toastr:ToastrService,
    private _globals:Globals
  ){
    this.taza = new Taza(null,null);
    this.patternNumber = this._pattern_service.patternNumber;
    if(this.data.cm !=='cr'){
      this.taza.fecha = this.data.obj.fecha;
      this.date = this._date_service.get_date_from_string(this.taza.fecha);
      this.taza.factor = this.data.obj.factor;
    }
  }

  isNumber(_item){
    return this._pattern_service.isNumber(_item);
  }

  isDate(_item){
    return this._pattern_service.isDate(_item);
  }

  validateTaza(){
    if(this.isNumber(this.taza.factor) && this.isDate(this.date)){
      return true;
    }else{
      return false;
    }
  }

  onNoClick(){
    this.dialogRef.close();
  }

  update_taza(){
    this.taza.fecha = this._date_service.get_string_from_date(this.date);
    this._taza_service.update_taza(this.taza).subscribe(
      (result:any)=>{
        if(result.success){
          this._toastr.success(result.success,'Exito');
          this.data.flag = true;
          if(this.taza.fecha == this._date_service.get_string_from_date((new Date))){
            this._globals.taza_cambio =this.taza.factor;
          }
          this.dialogRef.close(this.data);
        }else{
          if(result.error){
            this._toastr.error(result.error,'Error');
          }else{
            this._toastr.error('Error al procesar taza','Error');
          }
        }
      },(error:any)=>{
        this._toastr.error('Error al procesar taza RJ','Error');
      },()=>{

      }
    );
  }

}

**Comment by yarrgh** [comment]
The problem with your code examples is that you've yet to show the component having the issue calling the `warning()` function that you initially mentioned in your error message. My question, in the `ModalTaza` component, do the success/error toasts work properly?

**Comment by cdchn1989** [comment]
Hi no,not works anything about toastr

**Comment by yarrgh** [comment]
I honestly can't see why it would work for me and not for you. Maybe someone else will have some idea about what is happening.

**Comment by SebasG22** [comment]
@cdchn1989 please share stackblitz to check what's going on

**Comment by teamsatish** [comment]
Following div is not inserted by Toastr in ng serve --prod. OR ng build --prod.
If I manually write this line in index.html. Then it gets removed automatically.
`
div.overlay-container > div#toast-container.toast-top-right toast-container
`

`
{
  "name": "admin-angular",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.6",
    "@angular/common": "^6.1.6",
    "@angular/compiler": "^6.1.6",
    "@angular/compiler-cli": "^6.1.6",
    "@angular/core": "^6.1.6",
    "@angular/forms": "^6.1.6",
    "@angular/http": "^6.1.6",
    "@angular/platform-browser": "^6.1.6",
    "@angular/platform-browser-dynamic": "^6.1.6",
    "@angular/router": "^6.1.6",
    "@ng-bootstrap/ng-bootstrap": "^1.1.2",
    "@swimlane/ngx-datatable": "^13.1.0",
    "angular-calendar": "^0.22.1",
    "bootstrap": "^4.1.3",
    "chart.js": "^2.7.1",
    "chartist": "^0.11.0",
    "core-js": "^2.5.7",
    "jasmine": "^3.2.0",
    "jquery": "^3.2.1",
    "jquery-slimscroll": "^1.3.8",
    "ng-chartist": "^1.1.1",
    "ng2-charts": "^1.6.0",
    "ng2-dragula": "^1.5.0",
    "ng2-file-upload": "^1.3.0",
    "ng2-smart-table": "^1.2.2",
    "ng2-toastr": "^4.1.2",
    "ngx-perfect-scrollbar": "^5.0.0",
    "ngx-quill": "^3.4.0",
    "ngx-toastr": "^9.0.2",
    "pace-js": "^1.0.2",
    "popper.js": "^1.14.4",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.3.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.8",
    "@angular/language-service": "^6.1.6",
    "@types/chartist": "^0.9.42",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.3.6",
    "@types/node": "^6.0.117",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng2-completer": "^2.0.8",
    "protractor": "^5.4.0",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "^2.7.2"
  }
}
`

**Comment by mal90** [comment]
Had the same issue in 8.1.0 version , But once update to the latest version (9.1.1) , issue was resolved.
