### ISSUE TITLE
Using A Custom Toast

### ISSUE THREAD

**Issue by makeAdance** [scttcper/ngx-toastr#552]
Hi,

I tried to use the ngx-toastr with a custom toast as described in the section "Using A Custom Toast" at https://github.com/scttcper/ngx-toastr. Unfortunately I get an error which I do not know how to solve. Therefore I would need further help. Thanks upfront.

The custom component looks like this:

```
import { Component } from '@angular/core';
import { Toast, ToastPackage, ToastrService } from "ngx-toastr";

@Component({
  selector: 'ngc-toast',
  templateUrl: './toast.component.html',
  styleUrls: ['./toast.component.scss']
})
export class ToastComponent extends Toast {

  constructor(
    protected toastrService: ToastrService,
    public toastPackage: ToastPackage
  ) {
    super(toastrService, toastPackage);
  }
  
}
```

The error message says something like this:
ToastComponent_Host.ngfactory.js? [sm]:1 ERROR Error: Found the synthetic property @flyInOut. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

The point is: I included the mentioned modules. I even tried both of them. I do not know what I am missing here. Do I need to provide animations like in the example shown on this page or how can I solve the issue. I would appreciate an answer. Thanks.

**Comment by makeAdance** [comment]
I looks like that I really have to define the animations, and that I can not use urls. I seems that I have to insert the template and the styles directly. So my problem is solved, but if someone could explain why this is the case I would appreciate it. Thanks.

**Comment by yarrgh** [comment]
Decorators cannot be inherited, unfortunately.
