### ISSUE TITLE
ToastConfig isn't resolved

### ISSUE THREAD

**Issue by wa1gon** [scttcper/ngx-toastr#557]
I am getting this error when trying to injected ToastrService into another service.

AppComponent_Host.ngfactory.js? [sm]:1 ERROR Error: StaticInjectorError(AppModule)[InjectionToken ToastConfig]: 
  StaticInjectorError(Platform: core)[InjectionToken ToastConfig]: 
    NullInjectorError: No provider for InjectionToken ToastConfig!
    at NullInjector.get (core.js:1233)
    at resolveToken (core.js:1540)

What am I missing?

**Comment by aslubsky** [comment]
+1
ngx-toastr@9.0.2
angular@6.1.6

**Comment by GreatHawkeye** [comment]
Having the same issue here

**Comment by wa1gon** [comment]
Sorry missed import forRoot()

**Comment by Josh1billion** [comment]
To elaborate for anyone having the same issue,
add
`ToastrModule.forRoot(),`
to your `imports` array in your app.module.ts file.

**Comment by dottodot** [comment]
I'm having the problem and already have `ToastrModule.forRoot()`

The strange thing is it's working elsewhere in my project there's just one lazy loaded module and component where I get the error so a bit baffled.
