### ISSUE TITLE
Notifications invisible in Safari

### ISSUE THREAD

**Issue by HOMOTRISTIS** [scttcper/ngx-toastr#558]
Notifications works fine in any browser except safari(both mobile and macbook).
The container appears in the DOM and its contents too, but neither the z-index nor anything else makes it visible.

**Comment by HOMOTRISTIS** [comment]
problem was in angular animation

**Comment by matbalazsi** [comment]
I am having the same issue, but importing **@angular/platform-browser/animations** to the module and **import 'web-animations-js';**  to polyfills. Do you have any suggestions per how you solved this? Thanks!

**Comment by bfan1256** [comment]
Yes @HOMOTRISTIS , could you please provide some more information on how you fixed this? It seems to be working on safari computer, but it doesn't seem to be working on some safari mobiles right now...

**Comment by HOMOTRISTIS** [comment]
@bfan1256 - solution - mobile safari does not support frame-by-frame animation, I had to give it up
