### ISSUE TITLE
Pink and Notyf custom toasts not working in Edge

### ISSUE THREAD

**Issue by jacques-hoventer** [scttcper/ngx-toastr#560]
Check the demo site in Edge 42.17134.1.0 and click on either Pink or Notyf you'll notice neither of them work. 

https://scttcper.github.io/ngx-toastr/

I had created a component that extends Toast, as recommended in one of these threads, and came to the same issue where it works in Chrome but not in Edge. Exceptions are intermittent with one of them being "can't find message of null or undefined".

**Comment by scttcper** [comment]
Probably depends on your custom toast code? Custom toasts seem to be working for me in edge.
