### ISSUE TITLE
issues running ngx-toastr in Server Side Render

### ISSUE THREAD

**Issue by IngAjVillalon** [scttcper/ngx-toastr#562]
Hello, first of all, **congratulations for your excellent work developing ngx-toastr.**
The problem that I come to report is **when I use the ngx-toastr module with Angularfire and Universal.**
I made my application in Angular 6, I followed your instructions for installation and use. Everything works perfectly when I try the application with `ng serve`. In the same way, everything works well with the application when I run `ng build --prod`.
But my problem comes when I follow the steps to achieve the **server side render with Angularfire and Universal**.
I follow the steps described in:
https://github.com/angular/angularfire2/blob/dfaaac880d2829a893d471a2ee3811b79fcfaff3/docs/universal/getting-started.md
I get the application compile and run without errors BUT THE BEHAVIOR OF ngx-toastr RUNNING ON THE SERVER IS UNEXPECTED.
The first thing I saw is that the animations do not work in the same way as when I run the angular server with ng serve; but that is not important, that can be ignored; But WHAT I SEE AS ​​A PROBLEM IS THAT SOME TOAST DOES NOT DISMISS BYPASSING THE TIMEOUT, NEITHER DISMISS WITH TAP ON THE TOAST TO DISMISS.

I have prepared a repository so that you can verify what I say:
https://github.com/IngAjVillalon/Angular-Universal-6-Server-Side-Render
The steps you must follow are:
Clone this repository
`npm install`
`npm run build && npm run serve: ssr`

You can see what I mentioned earlier.

Could you please help me to make ngx-toastr run well on the server side?

**Comment by scttcper** [comment]
Thanks for the repo and i'll try to take a deeper look at it soon to see if we can do anything. I would avoid drawing toasts during route changes or on application init. You might also try number 1 in the FAQ https://github.com/scttcper/ngx-toastr#faq

**Comment by yarrgh** [comment]
What happens if you set `onActivateTick` to true when displaying the toasts from the server?

**Comment by IngAjVillalon** [comment]
Hi  @yarrgh, thank you very much for your suggestion.
I did what you tell me, and NO, it still does not close the first toast that comes out on the server.
@yarrgh, you can be free to clone the repository and we will make a help sheet with the requirements that those who will upload their application to the server using toastr need.
All follow in touch.
Greetings.

**Comment by anymos** [comment]
Hi there, and happy new year. I have the same issue.

I believe that a config option that would make the toast ignored when running on the server would be awesome.

Would it be something that you could add easily?

**Comment by NodeSwapCeo** [comment]
ok time to fork I guess

**Comment by rsornellas** [comment]
Any solution?

**Comment by osamaawadalla** [comment]
Same problem!
Is there any solution?

**Comment by ngBugHunter** [comment]
Any update on this ?

**Comment by henriquefockink** [comment]
If anyone still having this problem, I used a service to workaround it:

`export class NotifyService {
  constructor(@Inject(PLATFORM_ID) private _platformId: Object) {}

  private _toastrService = inject(ToastrService);

  success(message: string, title?: string, override?: Partial<IndividualConfig<any>>) {
    if (isPlatformBrowser(this._platformId)) this._toastrService.success(message, title, override);
  }`

Using this IF resolved my problem.

**Comment by Apurva-Shethia** [comment]
Hi there, 
I wanted to know if I can run toasts in ssr mode? 
The toasts are working fine if I do regular angular serve, but when I run it via server mode using ssr, there is no effect, no toast shown. Can someone please help?
Here are my environment details:
node: v18.20.4
npm: 10.7.0
angular: 18.2.11
Please forgive me if there is any communication gap.
