### ISSUE TITLE
Where can I find source code of demo project

### ISSUE THREAD

**Issue by RezaRahmati** [scttcper/ngx-toastr#565]
Hey

I am using ng-toastr, and I wast to hide all toasts, I see there is functionality in demo for that and there is no method in the service for that, I wanted to see how is it implemented. Where can I find the source code for the demo? 

Demo url: https://scttcper.github.io/ngx-toastr/

**Comment by yarrgh** [comment]
https://github.com/scttcper/ngx-toastr/tree/master/src/app

**Comment by RezaRahmati** [comment]
Thanks
