### ISSUE TITLE
Bootstrap styling without scss ?

### ISSUE THREAD

**Issue by grunk** [scttcper/ngx-toastr#571]
Hi,
is there a way to use bootstrap styling without scss ?

I have an app using bootstrap but it is simply included via a link tag in index.html

Using toastr by including it's css in angular.json works fine : 
```
"styles": [
  "styles.css",
  "node_modules/ngx-toastr/toastr.css" 
]
```
i'm looking to something similar for bootstrap. (i'm using toastr 9.1.0)

Thanks

**Comment by scttcper** [comment]
Other than compiling it and then copy and pasting it in, no other way.
