### ISSUE TITLE
Toastr break when used with AngularJS Toastr

### ISSUE THREAD

**Issue by dkosasih** [scttcper/ngx-toastr#572]
**Issue:** 
Toastr keep _paneElements and just check whether or not the div has been created but doesn't then if div still exists.
While AngularJS Toastr comes in play, it destroy the element after it's done and stop Toastr to display.

Proposed solution:
Check if the element still exists as well before returning the array.
https://github.com/scttcper/ngx-toastr/blob/master/src/lib/overlay/overlay.ts#L58
to something like
```
if (!this._paneElements[positionClass] || !document.getElementById(this._paneElements[positionClass].id))
```

Happy to create a PR. Let me know.

**Comment by yarrgh** [comment]
This library isn't meant to work along side AngularJS Toastr
