### ISSUE TITLE
display toastr on angular material modal

### ISSUE THREAD

**Issue by kumaroswal** [scttcper/ngx-toastr#577]
I am using the toastr at 2 places within my application.
On the regular page it displays well on top right corner.
On a angular material modal I need it to display on the modal itself.
I dont want to change the global setting.
How can I make it display on the modal with an individual setting?

**Comment by kumaroswal** [comment]
My app module code - 
```
import { ToastrModule, ToastContainerModule  } from 'ngx-toastr';
@NgModule({
    imports: [ToastrModule.forRoot(),
ToastContainerModule]
```

Individual .ts code
```
import { ToastrService, ToastContainerDirective } from 'ngx-toastr';
ngOnInit() {this._toastr.overlayContainer = this.toastContainer;}
foo() {
 this._toastr.error(error.Message,'Major error', {
                                positionClass: 'inline'
                              });
}
```

.html code
`<div toastContainer></div>`

**Comment by kumaroswal** [comment]
Well even tried it by changing the global parameter.
Still doesnt show up on the modal.

**Comment by samgevorgyan** [comment]
The same problem form me

**Comment by samgevorgyan** [comment]
I just changed    static: false, and put my overlayContainer in setTimeout 

` 
@ViewChild(ToastContainerDirective, { static: false })
  toastContainer: ToastContainerDirective;
ngOnInit() {
    console.log("fromRoot", fromRoot);

    setTimeout(() => {
      this.toastr.overlayContainer = this.toastContainer;
      console.log("toastContainer", this.toastContainer);
    }, 100);
} 


`

**Comment by samgevorgyan** [comment]
If you open  material dialog in Lazy loaded module, then you have to add  "ToastContainerModule" in the imports section  in that module also

**Comment by masterfaka** [comment]
I've tried.. but still doesn't work. same case scenario here.
