### ISSUE TITLE
How to disable only extended Timeout?

### ISSUE THREAD

**Issue by micherpl** [scttcper/ngx-toastr#578]
Is it possible to disable only extended Timeout? The aim is to display Toastr for certain time (set in timeOut property), no matter if your mouse hover the specific Toastr or not. For now I can set extended Timeout for 0 (never expires, when mouseover) or some static value and I cannot disable it. Maybe it is good idea to implement this functionality if there is no easy way to achieve this .

**Comment by yarrgh** [comment]
I don't see an easy way of implementing with the current config/behavior. In order achieve this you'd need a way to disable the onhover behavior from triggering. Right now this isn't possible.

Willing to consider a PR if anyone is willing to create one.

**Comment by micherpl** [comment]
Luckily there is quite easy workaround. Example below shows toast that closes after 5000 milliseconds no matter if your mouse hover this toastr or not
```
const errorToastr = this.toastrService.error('everything is broken', 'Major Error', {
     timeOut: 5000,
     extendedTimeOut: 0
});

errorToastr.onShown.subscribe(() => {
            setTimeout(() => {
                errorToastr.toastRef.manualClose()
            }, 5000);
        });
```

**Comment by scttcper** [comment]
@micherpl 👍 nice

**Comment by Hassan-Moin** [comment]
> I don't think this issue was actually resolved. The original poster wanted a way to only use the timeout feature and not have the timeout be affected by hovering. For example, when a toastr message with a timeout of 5 seconds appears, it would stay on screen for 5 seconds even if the user hovers over it. When I used the disableTimeout feature on extendedTimeOut, instead of being unaffected by the hover, it stays on the screen indefinitely when after the hover.

It does what the original question wanted.

If you want to disable `extendedTimeOut` only, Just add this in the toaster config
`disableTimeOut: 'extendedTimeOut'`

if you want to disable timeout then
`disableTimeOut: 'timeOut'`

If you want to disable both then
`disableTimeOut: true`

**Comment by kapil26021994** [comment]
hi @Hassan-Moin  if i set disableTimeOut: true progress bar not working
