### ISSUE TITLE
@angular/http dependency

### ISSUE THREAD

**Issue by bohap** [scttcper/ngx-toastr#580]
Why @angular/http is listed in dependencies?
**@angular/http** is deprecated and **@angular/common/http** is recommended for using, and also I don't see that HttpClient is used anywhere in this lib.

**Comment by yarrgh** [comment]
The library doesn't:

https://github.com/scttcper/ngx-toastr/blob/master/src/lib/package.json

If you're taking about the demo app, that's because angular-cli added it automatically when the coffee was generated. It's not used anywhere. It just never got removed.

**Comment by scttcper** [comment]
because angular librarys are easier to publish with another package.json you might try asking npm `npm info ngx-toastr peerDependencies dependencies`
