### ISSUE TITLE
timeout not working

### ISSUE THREAD

**Issue by wsh92** [scttcper/ngx-toastr#582]

**Comment by yarrgh** [comment]
Are you implementing the timeout functionality in your custom component(s)? If not checkout the Toast component to see how it is handling the timeout functionality.

When the component activates, on line 120 we set a timeout to remove the toast based on the timeout passed in the config:
https://github.com/scttcper/ngx-toastr/blob/036be5ef74b34e61d72823d7e52adced662832ac/src/lib/toastr/toast.component.ts#L117-L126

Next handle the mouse events accordingly. This includes removing the timeout on line 191 to pause the timeout. And on line 208 we resume the timeout using the extended timeout:
https://github.com/scttcper/ngx-toastr/blob/036be5ef74b34e61d72823d7e52adced662832ac/src/lib/toastr/toast.component.ts#L186-L215

**Comment by wsh92** [comment]
@yarrgh Thanks for the info.  
I did not implement my own timeout in custom notification component, but after adding these two lines in **constructor and ngOnit**, timeout functionality is working as expected.
In custom-component Constructor
```
 constructor(protected toastrService: ToastrService,
    public toastPackage: ToastPackage,private changeDetectorRef: ChangeDetectorRef) {
      **super(toastrService, toastPackage);**
     }
```

```
 ngOnInit() {
    this.changeDetectorRef.detectChanges(); //add this because conent is not updating in custom notification
  }
```

**Comment by raviagheda** [comment]
I override the mouse events as I don't need them for my implementation.  
this setup worked for me, in case It might help someone :) 

```
@HostListener('mouseenter')
stickAround(): void {
	return;
}

@HostListener('mouseleave')
delayedHideToast() {
	return;
}
```

**Comment by tahirhsnli** [comment]
Hello, I added these codes you wrote but it still didn't work

**Comment by tahirhsnli** [comment]
@trevor-hackett Hello, I added these codes you wrote but it still didn't work
