### ISSUE TITLE
Angular 7 --prod build warnings and run time errors

### ISSUE THREAD

**Issue by smande00** [scttcper/ngx-toastr#583]
After upgrading to Angular 7 (and using ngx-toastr 9.1.1), I get build warnings when using the --prod flag for ng build.  The warning is "export 'ToastrComponentlessModule' (imported as 'i1') was not found in 'ngx-toastr'".

Additionally I get StaticInjectionErrors in the console at run time. 

I'm importing using 
import { ToastrModule } from 'ngx-toastr';
and
 ToastrModule.forRoot() in the app module imports.

The component is using :
import { ToastrService } from 'ngx-toastr'; 
and injecting the ToastrService.

**Comment by smande00** [comment]
Apologies for the delay in responding - TS version is 3.1.3

**Comment by yarrgh** [comment]
I'd try making sure that ngx-toastr 9.1.1 was installed correctly.

I've just testing with a blank `@angular/cli: 7.1.1` project and added ngx-toastr. Running `ng build --prod` yielded no errors or warnings. I then took the dist folder files and spun up a quick http server: `cd dist/just-testing` and `http-server .` App launched and toast showed as expected.

**Comment by stasgaonkar** [comment]
I am getting the similar error - any further updates?

**Comment by Przemek625** [comment]
For me 'ngx-toastr' does not work in production. It works fine on localhost. Any idea why it might happen???

**Comment by yarrgh** [comment]
How and where are you using the toasts? I can't seem to duplicate this. Having a repo where this can be duplicated would be very helpful.

**Comment by coolrb** [comment]
I am too getting this error after upgrade to 9.1.1. It only happens for prod build. Any solution?

**Comment by PeterHewat** [comment]
I am having the same problem.
My environment:
```
ngx-toastr: 11.2.1
Angular CLI: 9.0.0-rc.8
Node: 12.14.0
NPM: 6.13.4
OS: win32 x64
```
Steps to reproduce:
```
npm ci
ng build --prod
```
I get the following warning:

`WARNING in Entry point 'ngx-toastr' contains deep imports into '.../node_modules/@angular/compiler/src/core'. This is probably not a problem, but may cause the compilation of entry points to be out of order.`

If I build without an `npm ci` before, I do not get this warning.

**Comment by beeman** [comment]
I'm having the same issue. I got a repo with the reproduction [here](https://github.com/beeman/kikstart-ui-starter) and the output of the GitHub action where it fails can be found [here](https://github.com/beeman/kikstart-ui-starter/runs/397338619).

```
Angular CLI: 9.0.0-rc.9
Node: 12.12.0
OS: darwin x64

Angular: 9.0.0-rc.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.9
@angular-devkit/build-angular     0.900.0-rc.9
@angular-devkit/build-optimizer   0.900.0-rc.9
@angular-devkit/build-webpack     0.900.0-rc.9
@angular-devkit/core              9.0.0-rc.9
@angular-devkit/schematics        9.0.0-rc.9
@ngtools/webpack                  9.0.0-rc.9
@schematics/angular               9.0.0-rc.9
@schematics/update                0.900.0-rc.9
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
```
