### ISSUE TITLE
Support for HTML with Event handling?

### ISSUE THREAD

**Issue by master83** [scttcper/ngx-toastr#586]
Looks like current version doesn't support HTML with event handling. Is there any alternate of doing it? I have HTML snippet which has a link in it. HTML renders fine, but link does not work. I have tried with DOMSanitize but no luck. Any help in this regards will be appreciated. Thanks!

My snippet looks like this

`<div>Hello<a onClick="download()">Download Report</a></div>`

**Comment by scttcper** [comment]
make a custom component, html like that not really allowed in angular
