### ISSUE TITLE
Custom close button class option

### ISSUE THREAD

**Issue by Necroskillz** [scttcper/ngx-toastr#587]
Our css people :) would like to put a class on the close button to use an icon from our predefined iconset - this would require to have another option in the toast config.

I could submit a PR for this if you are ok with this feature.

**Comment by yarrgh** [comment]
You might be better off duplicating our `Toast` component and adding the class to the button as needed and then updating the config to change the component that is used for the toasts.

The reason being is that this is such an edge case that I don't see it as being worth adding as a feature. If the demand increases we can take another look into adding it.

**Comment by Necroskillz** [comment]
The reason I didn't want to duplicate the whole component, is that it's pretty complicated (~250 lines of code) and I would need to keep it synchronized between updates of ngx-toastr versions. Imo this is too high of a cost for changing one class.

**Comment by yarrgh** [comment]
You could extend the `Toast` component so that you don't have to keep the logic up to date. You'll still need to copy the animations and html over and customize the close button as needed.

**Comment by yarrgh** [comment]
I'd suggest just overriding the css to change the icon but the "x" is hardcoded in the html:

https://github.com/scttcper/ngx-toastr/blob/783a1f23604f3fa1eceb3662beee69c473a568ab/src/lib/toastr/toast.component.ts#L23-L25

**Comment by yarrgh** [comment]
If you still feel like this should be an option, go ahead and open a PR. I'm sure we can reconsider if we see a PR
