### ISSUE TITLE
zone.js:2969 GET http://localhost:4200/node_modules/ngx-toastr/toastr.css 404 (Not Found)

### ISSUE THREAD

**Issue by SmitaBera** [scttcper/ngx-toastr#591]
I have used 
<link href="node_modules/ngx-toastr/toastr.css" rel="stylesheet" />
<script src="node_modules/ngx-toastr/bundles/ngx-toastr.umd.js"></script>
in my HTML component.
I have also defined it in angular.json
"styles": [
              "src/styles.css",
              "./node_modules/bootstrap/dist/css/bootstrap.min.css",
              "node_modules/ngx-toastr/toastr.css" 
I am unable to solve the issue.

I am getting two errors:
zone.js:2969 GET http://localhost:4200/node_modules/ngx-toastr/toastr.css 404 (Not Found)
main.ts:12 Failed to load node_modules/ngx-toastr/toastr.css

Please help me out

**Comment by scttcper** [comment]
https://unpkg.com/ngx-toastr@9.1.1/ its in there make sure its there on your filesystem and that angular-cli can find it

**Comment by yarrgh** [comment]
The index.html cannot access the node_modules folder (or anything in it) when using the Angular CLI. You'll either need to move it manually to your assets folder or include it in your `angular.json` config so that it gets bundled with your app on build.
