### ISSUE TITLE
toastr position changed after upgrading project from Angular 5 to Angular 7 !!

### ISSUE THREAD

**Issue by divyang7777** [scttcper/ngx-toastr#592]
we shifted our project to Angular 7 and found out that the ngx-toastr lost their place from top-right and are lying bottom at the end of the site ... got stuck here tryed changing the classes and all but couldn't find any solution ... what to do ?
![screenshot from 2018-12-03 19-09-18](https://user-images.githubusercontent.com/16624336/49377000-f70a3e00-f72e-11e8-97d4-65900bab7e03.png)

**Comment by scttcper** [comment]
make sure the css is being loaded

**Comment by yarrgh** [comment]
Location/styling is purely based off of the css classes.

Angular-cli v6 dramatically changed the `angular-cli.json` (now known as `angular.json`). In the upgrade, your css most likely got removed or is no longer in the correct location. You'll need to add the css back into `angular.json` or move it to the correct location.

**Comment by divyang7777** [comment]
@scttcper and @yarrgh ... ya as you both said above it was the matter of css misplacement in angular.json ... now i did was add the appropriate path of the css ... like mentioned in https://www.npmjs.com/package/ngx-toastr and shown in the image below ... still not successful !
![screenshot from 2018-12-04 12-07-27](https://user-images.githubusercontent.com/16624336/49423346-31222100-f7bd-11e8-9beb-a78312f13856.png)

**Comment by yarrgh** [comment]
Did you restart Angular-cli after making that change?

**Comment by divyang7777** [comment]
ya @yarrgh i did restart and reserved still not solved !

**Comment by divyang7777** [comment]
@yarrgh ... sorry and thanks it got solved :)
