### ISSUE TITLE
Toastr doesn't disappear when user navigates to the previous page

### ISSUE THREAD

**Issue by annaolsh** [scttcper/ngx-toastr#593]
When i display a toastr with a disabled time out, like this:
`this.alertService.error(data['message'], 'Error', {disableTimeOut: true, positionClass: 'toast-center-center', tapToDismiss: false});`
It's displayed correctly on the screen. But if i click 'back' browser navigation button, the toastr does not disappear.  As a result, previous page with a correct data has toastr error from the different page. 
If as a next step, i use 'forward' browser navigation button to go back to the page that has error, I see the same old toastr.  And if that page still has an error, i see a new toastr with the same error message on top of the old one.

**Comment by scttcper** [comment]
you've disabled timeout so it will display forever. You should manually close the toast using `toastrService.clear(yourToastId)` on page navigate if thats what you want.

**Comment by ebem** [comment]
@scttcper  toastrService.clear() was looking for this, thanks!
