### ISSUE TITLE
How to add a custom class without replacing 'toast'?

### ISSUE THREAD

**Issue by electric-ladyland** [scttcper/ngx-toastr#594]
Sorry if this is answered somewhere, but I want to add some custom styles to an individual toast popup (e.g. increase width). I see the `toastClass` config option - but this replaces the `toast` class which has essential styles applied to it (from bootstrap styles). 

Is the only way to copy all the styles attached to `.toast` into my own custom class?

**Comment by electric-ladyland** [comment]
@yarrgh Thanks, but that would apply to all my toasts. I'm wondering if I can target one specific toast (that is displaying HTML content) without affecting other toasts and without having to copy all the styles that are attached to the toast class.

**Comment by hunj** [comment]
Bump

**Comment by keljoundi** [comment]
I 2nd this. it would be very convenient to simply **add** styling in addition to the defaults. Copying all styles to a custom class still introduces errors for me such as the onTap and onAction events no longer firing

**Comment by Unitarian** [comment]
This is a much-needed feature.
I need to show popups of different colours and one way to do that is, extend Toast component like in pink toast example but in my case, I would have to create 10 different custom components.

if there is any other way please let me know.

Thank you

**Comment by scttcper** [comment]
put 'yourclass toast' for toastClass?

**Comment by Unitarian** [comment]
@scttcper Thank you for the quick reply.

I tried adding my class with the property of `background-color` and `toast` class but it shows a toast with transparent background with no padding also `close `button and onTap action are not working.

However, if I use `toastClass: `my-class ngx-toastr`` it gives me a black toast but the rest of the properties are what I want. 

Can you please suggest how can I use it in the correct manner.

Thank you very much in advance :)

**Comment by scttcper** [comment]
i had success by being more specific with the classes. could also try !important.
```css
.yourclass.toast-success {
  background-color: blue;
}
```

**Comment by Unitarian** [comment]
Thank you very much 👍 

I have this working with the css you provided and then specifying `toastClass: 'ngx-toastr toast-success yourclass'`

As you can see I had to use both `ngx-toasts` and `toast-success` to make it work.

One more quick question, please. 

I have to put my class in styles.css. I would want to move it to the component level css file, its the place I am calling `toasterService.show()` from. Is it possible to do so?

Once again thank you for the help!

**Comment by scttcper** [comment]
the toast is not inside the context of your component so scoped css would not be applied. custom toasts would be the closest you could get but would still require global positioning styles

**Comment by axell9641** [comment]
Is there any way I can change the position of the toastr from within a component? I see the toastClass gets applied to the content, not the container.

**Comment by sami-colon** [comment]
> i had success by being more specific with the classes. could also try !important.
> 
> ```css
> .yourclass.toast-success {
>   background-color: blue;
> }
> ```

This worked like charm.

**Comment by lvilca-tekton** [comment]
I can't get this to work, I am trying this in my .ts file
I have imported the toastrService to it, then I use
```
this._toastrService.success('test','test',{toastClass:'yourclass ngx-toastr'})
```
In the same dir, I have an css file
```
.yourclass .toast-message {
    background-color: blue;
}
```
I don't see it blue, am I doing smth wrong?

**Comment by Ashish-rajpoot** [comment]
node_modules/ngx-toastr/toastr/toast.directive.d.ts:8:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

**Comment by SagarStake** [comment]
My requirement is to show a countdown timer in the toastr message, is there any way to do this?
Is there a way for the toastr to use templateRef element to show in the message. That way I can use an observable value in the templateRef to show the dynamic value of the observable at any given time.

**Comment by marjanjavid** [comment]
If you'd like to apply a custom style (e.g., a background color) to all your toastr messages, follow these steps:

 ```
    ToastrModule.forRoot({
      toastClass: 'ngx-toastr custom-toast' // Add custom class to all toasts
    })
```

and in the styles.scss
```
.ngx-toastr.custom-toast {
  background-color: #FF9900 !important; /* Replace with your desired background color */
  color: #FFFFFF !important; /* Customize text color */
}
```

But if you want to only change the background color for the "info" toastr messages while keeping other toastr types (success, warning, error) unchanged, follow these steps:
```
.toast-info {
  background-color: #17a2b8 !important; /* Replace with your desired background color */
  color: #ffffff !important; /* Adjust text color if necessary */
}
```

**Comment by vinodsantharam** [comment]
> ```
> .toast-info {
>   background-color: #17a2b8 !important; /* Replace with your desired background color */
>   color: #ffffff !important; /* Adjust text color if necessary */
> }
> ```

exactly what I needed! Thanks @marjanjavid 🥇

**Comment by git-harshIIIT** [comment]
How can i change the icon to be displayed in the left most side? I want to add my own svg icon
