### ISSUE TITLE
bootstrap 4.2 toastr

### ISSUE THREAD

**Issue by scttcper** [scttcper/ngx-toastr#601]
There's actual bootstrap toast styles
https://getbootstrap.com/docs/4.2/components/toasts/

maybe a custom component?

**Comment by bastienmoulia** [comment]
This component already exist in ng-bootstrap 5:
https://ng-bootstrap.github.io/#/components/toast

**Comment by scttcper** [comment]
Wow it does. Looks like they decided to not provide a proper service and have everyone implement their own and the service example is a ngFor loop 😒 
Still a good start
