### ISSUE TITLE
Not showing unless hovering

### ISSUE THREAD

**Issue by hellseyfer** [scttcper/ngx-toastr#605]
It was working well but after some issues and updates of angular dependencies it won't show normally unless i hover it. Already tried without animation without success

**Comment by yarrgh** [comment]
By the way you've described what is happening, it sounds like it's not working properly unless you trigger change detection on the toast.

Are you triggering the toast outside of change detection or outside of angular's zone?

**Comment by higgs01** [comment]
@yarrgh not that i know of, i've just followed the guide in https://github.com/scttcper/ngx-toastr#setup and https://github.com/scttcper/ngx-toastr#use

Here is my code:

Styles: 
```
/* You can add global styles to this file, and also import other style files */
@import '~ngx-toastr/toastr.css';
body {
  margin: 0;
}
```

app.module.ts
```
@NgModule({
  declarations: [
    AppComponent,
    FormComponent,
    HeaderComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    FormsModule,
    HttpClientModule,
    AngularEditorModule,
    RecaptchaModule,
    RecaptchaFormsModule,
    ReactiveFormsModule,
    ToastrModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
```

form.component.ts
```
constructor(private _types: PlugintypeService, private _toastr: ToastrService) { }

  ngOnInit() {
    this._types.getPluginTypes().subscribe(types => {
      this.types = types;
    });
  }

  public onSubmit(): void {
    if (this.createForm.status === 'INVALID') {
      console.warn('Form invalid');
      this._toastr.error('Formular nicht vollständig', 'fehler');
    } else {
      console.warn(this.createForm.value);
    }
  }
```

**Comment by yarrgh** [comment]
Yes, I can confirm that this is happening. Not sure exactly why though.

Funny thing is, if you turn on the progress bar it works fine.

Example:
```ts
  click() {
    this.toastr.success('testing', 'Test', { progressBar: true });
  }
```

**Comment by nikhilpatel7** [comment]
I am facing the same issue. But after digging for hours I was able to find the solution...
**There's a naming collision for the .toastr CSS class in bootstrap and ngx-toastr.**
You can find out the solution on : https://stackblitz.com/edit/angular-avcidu
Source of solution:
https://stackoverflow.com/questions/53989445/ngx-toastr-toast-not-showing-in-angular-7#

Thanks

**Comment by higgs01** [comment]
@nikhilpatel7 thank you very much. This solved it for me

**Comment by scttcper** [comment]
duplicate of #602 probably

**Comment by yarrgh** [comment]
I don't think this is specific to bootstrap. I performed my tests with a brand new angular-cli project without bootstrap and was able to get this strange behavior to happen.

**Comment by yarrgh** [comment]
Here a repo with the issue: https://github.com/yarrgh/test-toast-app

I can't duplicate it on StackBlitz. If you run `ng serve` or run `ng build --prod` and then serve the dist files, you should be able to see what I'm seeing.

**Comment by yarrgh** [comment]
I think the issue I found may be separate from the OP but I'm not entirely sure until they respond.

**Comment by scttcper** [comment]
@yarrgh you don't have animations loaded?

**Comment by yarrgh** [comment]
Touché.

That's what I get by going too fast. I stopped once I "duplicated" the issue.

**Comment by hellseyfer** [comment]
My issue could be related to angular material or angular updates, it was working fine with bootstap. Just wanted to know if it was only me, thanks

**Comment by ngKisor** [comment]
add this to your global style.css 
#toast-container > div {
    opacity:1;
}

**Comment by JosepRoo** [comment]
> add this to your global style.css
> #toast-container > div {
> opacity:1;
> }

with this i get a white toast

<img width="317" alt="captura de pantalla 2019-01-03 a la s 10 59 59" src="https://user-images.githubusercontent.com/14793786/50650664-c0e6f680-0f46-11e9-9082-3914d18ee1ed.png">

**Comment by ianbeemsterboerr** [comment]
I am having the same issue, and I can confirm that the problem is a collision with bootstrap, cause when I commented out the bootstrap reference in my styles attribute on angular.json the toasts showed up fine. However, even when I added: 

#toast-container > div {
opacity:1;
}

to my global styles css (which I assume is app.component.css in an angular project) the issue kept on persisting.

**Comment by Hernior** [comment]
> I am having the same issue, and I can confirm that the problem is a collision with bootstrap, cause when I commented out the bootstrap reference in my styles attribute on angular.json the toasts showed up fine. However, even when I added:
> 
> #toast-container > div {
> opacity:1;
> }
> 
> to my global styles css (which I assume is app.component.css in an angular project) the issue kept on persisting.

I had to do a few more things for this to work on my Angular + Bootstrap project, my style.css looked like this:

/* TOASTR BUGFIX */
#toast-container > div {
    opacity:1;
}
.toast {
  font-size: initial !important;
  border: initial !important;
  backdrop-filter: blur(0) !important;
}
.toast-success {
  background-color: #51A351 !important;
}
.toast-error {
  background-color: #BD362F !important;
}
.toast-info {
  background-color: #2F96B4 !important;
}
.toast-warning {
  background-color: #F89406 !important;
}

**Comment by abhaygawade** [comment]
manipulating existing CSS of toastr.css works for me
    .toast-container .toast {
        opacity: 1;
    }

**Comment by abhaygawade** [comment]
Adding BrowserAnimationsModule in `app.module.ts` works. We can close this issue.

**Comment by abhaygawade** [comment]
Adding `BrowserAnimationsModule` immediate after `BrowserModule` works. This is about module positioning

**Comment by ianbeemsterboerr** [comment]
After combining what @abhaygawade and @Hernior advised it works for me.

**Comment by naveenkengannar** [comment]
I am facing the same issue while using the latest Bootstrap 4.2.1. I tried all the workarounds given above but none of them fixed the issue. Anyone has tried the version of Bootstrap 4.2.1 and fixed the issue by any chance?

**Comment by guibleme** [comment]
I'm having the same issue. Not really sure what is going on, for real. I read the whole thread and tried all the fixes, nada. Feels like something related to component calls, don't know why though.

**Comment by pnutdev** [comment]
> Adding `BrowserAnimationsModule` immediate after `BrowserModule` or `CommonModule` works. This is about module positioning

No need to override the ngx-toastr styling. If animation module properly set. This will manage opacity thing

**Comment by sandrumirceaioan** [comment]
> No need to override the ngx-toastr styling. If animation module properly set. This will manage opacity thing

My modules are in the exact same order as you guys described, but nothing except css trick works...

**Comment by tomjvdberg** [comment]
I can confirm that the issue is introduced when I upgrade bootstrap to 4.3.1. Reverting to my previous version of 4.1.3 solves the issue.

Problem is that bootstrap uses the same class .toast with "opacity: 0;". Solution is to have this set in the toastr.css ".toast-container .toast " as "opacity: 1;" since it will overwrite the bootstrap style.

Created a pull request https://github.com/scttcper/ngx-toastr/pull/623

**Comment by metaliciouz** [comment]
Another solution: don't import **toast**, if you don't use it in your project.
Remove `@import "toasts"` from your scss file.

My style.scss with latest bootstrap, excluding some files:
```
// import bootstrap 4
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/root";
@import "~bootstrap/scss/reboot";
@import "~bootstrap/scss/type";
@import "~bootstrap/scss/images";
@import "~bootstrap/scss/grid";
@import "~bootstrap/scss/tables";
@import "~bootstrap/scss/forms";
@import "~bootstrap/scss/buttons";
@import "~bootstrap/scss/transitions";
@import "~bootstrap/scss/custom-forms";
@import "~bootstrap/scss/nav";
@import "~bootstrap/scss/navbar";
@import "~bootstrap/scss/card";
@import "~bootstrap/scss/jumbotron";
@import "~bootstrap/scss/list-group";
@import "~bootstrap/scss/close";
@import "~bootstrap/scss/modal";
@import "~bootstrap/scss/utilities";
@import "~bootstrap/scss/print";

// import ngx-toastr styles
@import '~ngx-toastr/toastr.css';
@import '~ngx-toastr/toastr-bs4-alert';

// code...
```

See: https://getbootstrap.com/docs/4.3/getting-started/theming/#importing
Source code: https://github.com/twbs/bootstrap/blob/master/scss/bootstrap.scss

**Comment by marchage** [comment]
Yeah, but for my setup that is not a solution. I am not importing 22+ bootstrap scss files but a simple cdn version. What would work in that is case is to append the fix from Tom's pull request ( #623 ) to your main src/styles.scss file. If you have one of course. And if it doesn't interfere with other "stuff" in your project.
```
.toast-container .toast {
  opacity: 1;
}
```

**Comment by deckerbd** [comment]
Just ran into this as well after updating to the latest version of Bootstrap. The snippet by @Hernior worked for me. Are there any plans to fix this?

**Comment by scttcper** [comment]
@deckerbd 	looking to make a bunch of breaking changes around the ivy release and make this fix a part of that. It requires breaking changes. The opacity: 1 isn't a good fix and ideally people wouldn't import toast styles they aren't using.

If you're using bootstrap with scss you should not import the toast styles see #602

**Comment by yarrgh** [comment]
Can somebody try 9.2.0 and see if this works without needing to add the additional css? From my initial quick tests on an empty project using Bootstrap 4.3.1 and ngx-toastr 9.2.0 toasts are showing up without having to add the opacity css in my project.

**Comment by Hernior** [comment]
> 🎉 This issue has been resolved in version 10.0.0 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/ngx-toastr)
> * [GitHub release](https://github.com/scttcper/ngx-toastr/releases/tag/v10.0.0)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

Thank you Scott <3

**Comment by andrebrz** [comment]
> Adding `BrowserAnimationsModule` immediate after `BrowserModule` or `CommonModule` works. This is about module positioning

Perfect! Thank you!

**Comment by prasanga-b** [comment]
you need to import  BrowserAnimationsModule in app.module.ts

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

**Comment by SamiHK** [comment]
@pnutmath  your answer solved the issue for me. Thank you soo much!

**Comment by amiram** [comment]
I'm using ng9 with toastr 12.1.0. Trying to show a toast from a service listening to firebase messaging. Nothing here helped other than `progressBar: true`. Even if I showing the toast in the component that holds the service and call `detectChanges()`, still not working unless hovering.
