### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by MetaiR** [scttcper/ngx-toastr#610]
is there any support for rtl?

**Comment by scttcper** [comment]
custom toast component can look however you like

**Comment by MetaiR** [comment]
tnx, I try to achieve this with through CSS and it worked

**Comment by tamimjabban** [comment]
> tnx, I try to achieve this through CSS and it worked

Can you share how you achieved this using CSS? Thank you.

**Comment by noamyg** [comment]
> > tnx, I try to achieve this through CSS and it worked
> 
> Can you share how you achieved this using CSS? Thank you.

```
.ngx-toastr {
    text-align: right;
}
```

?

**Comment by tamimjabban** [comment]
@noamyg Thank you. I ended up doing a bit more to make give it full rtl support. I did this with the following scss, in case it can help others too:

```
.custom-toast {
  background-position-y: 50% !important;
  .toast-close-button {
    right: 0 !important;
  }
}

.custom-toast-ltr {
  @extend .custom-toast;
  background-position-x: 5% !important;
}

.custom-toast-rtl {
  @extend .custom-toast;
  background-position-x: 95% !important;
  padding-right: 50px !important;
  padding-left: 15px !important;
  .toast-close-button {
    float: left !important;
  }
}
```

I gave an additional class to the toast depending on ltr/rtl in the component.
