### ISSUE TITLE
bootstrap dependency

### ISSUE THREAD

**Issue by hellerbarde** [scttcper/ngx-toastr#621]
Is there an easy way to get rid of the bootstrap dependency? 

We use angular material and purposefully removed all our bootstrap dependencies.

**Comment by scttcper** [comment]
there is no dependency on bootstrap

**Comment by hellerbarde** [comment]
Can I make a pull request adjusting the package.json accordingly in that case?

**Comment by scttcper** [comment]
the package.json being shipped does not have bootstrap in it.

**Comment by hellerbarde** [comment]
okay. thanks for the clarification. I wasn't aware. great work!
