### ISSUE TITLE
Error calling toastr inside a dialog

### ISSUE THREAD

**Issue by Alsmith141510** [scttcper/ngx-toastr#629]
I am using angular 7.3.3, angular material and ngrx-toastr. I have a login screen which is a matdialog. On error I want show a toastr with error message. Any pointer would be helpful. The error is

LoginComponent.html:5 ERROR CONTEXT DebugContext_component: (...)componentRenderElement: (...)context: (...)elDef: {nodeIndex: 5, parent: {…}, renderParent: {…}, bindingIndex: 2, outputIndex: 0, …}elOrCompView: (...)elView: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: LoginComponent, …}injector: (...)nodeDef: {nodeIndex: 5, parent: {…}, renderParent: {…}, bindingIndex: 2, outputIndex: 0, …}nodeIndex: 5providerTokens: (...)references: (...)renderNode: (...)view: {def: {…}, parent: {…}, viewContainerParent: null, parentNodeDef: {…}, context: LoginComponent, …}__proto__: Object
View_LoginComponent_0 @ LoginComponent.html:5

**Comment by darshanDevrai** [comment]
I am using the same configuration and I am able to show the error messages in mat-dialog successfully.
Have followed the [docs](https://github.com/scttcper/ngx-toastr#put-toasts-in-your-own-container)?

**Comment by Alsmith141510** [comment]
Thanks Darshan:
   You were right it was the Toastr container. Dumb of me not to read the documentation. Thanks for pointing me in the right direction.

My apologies for not getting ack to you earlier.

Al

**Comment by darshanDevrai** [comment]
> You were right it was the Toastr container. Dumb of me not to read the documentation. Thanks for pointing me in the right direction.

That's how Open Source works by helping each other.  I am glad you got it working:)

> My apologies for not getting ack to you earlier.

No worries:)
