### ISSUE TITLE
Not able to close a Toast with v. 10

### ISSUE THREAD

**Issue by destus90** [scttcper/ngx-toastr#634]
Can't clear a Toast with ngx-toastr v.10. When you click on the close button, you won't get any results. It works fine with v.9. Demo https://stackblitz.com/edit/angular-qsbo9d?file=src/styles.css:

**Comment by vmhung93** [comment]
I am also facing this problem. But I realize that if you use "Bootstrap 4 Style" mode then you can click close button and clear this toastr.

**Comment by ujjaldey** [comment]
Yes. I am also facing the same issue. Close button is not working.

**Comment by scttcper** [comment]
thanks for clear explanation. looks like i missed renaming one of the classes

**Comment by ajuravle** [comment]
On version 10.0.4 still not working

**Comment by ubrucezhang** [comment]
I tried 10.1.0, 10.0.1 and v9.0.0, 
None of them works.
