### ISSUE TITLE
Prevent duplicates and maxopened not working properly

### ISSUE THREAD

**Issue by sacynthia** [scttcper/ngx-toastr#641]
Hi Team,
     I am using the following version of ngx toastr in my angular web application and defined the config which is to prevent the duplicate opening of messages and to be active until the user manually click it.
version:   "ngx-toastr": "^9.2.0",
config:
 public toastconfig: any = { timeOut: 0, extendedTimeOut: 0, preventDuplicates: true, maxOpened: 1, autoDismiss: false };
  this.toastService.success(Message, Title, this.toastconfig);

Issue:
   The issue am facing here is still the duplicate toastr messages are displaying as a stack...

Can you please help me to resolve.

**Comment by scttcper** [comment]
check your css
