### ISSUE TITLE
InjectFlags still causing errors on angular 4

### ISSUE THREAD

**Issue by fatifleu** [scttcper/ngx-toastr#646]
i installed ngxtoastr in angular 4 but it gives me those errors
ERROR in C:/Users/FATIKMA/Documents/lokate/node_modules/ngx-toastr/toastr/toast-injector.d.ts (1,20): Module '"C:/Users/FATIKMA/Documents/lokate/node_modules/@angular/core/core"' has no exported member 'InjectFlags'.
ERROR in C:/Users/FATIKMA/Documents/lokate/node_modules/ngx-toastr/toastr/toast-noanimation.component.d.ts (1,37): Cannot find module '@angular/compiler/src/core'.
ERROR in Metadata version mismatch for module C:/Users/FATIKMA/Documents/lokate/node_modules/ngx-toastr/ngx-toastr.d.ts, found version 4, expected 3, resolving symbol GeneAppModule in C:/Users/FATIKMA/Documents/lokate/src/app/app.module.ts, resolving symbol GeneAppModule in C:/Users/FATIKMA/Documents/lokate/src/app/app.module.ts, resolving symbol GeneAppModule in C:/Users/FATIKMA/Documents/lokate/src/app/app.module.ts

**Comment by scttcper** [comment]
Upgrade angular or see the readme for a compatible version.
