### ISSUE TITLE
Toastr does not show HTML even with HTML enabled

### ISSUE THREAD

**Issue by samunisys** [scttcper/ngx-toastr#658]
I've tried this in a local repository, and on your demo site. I can't get the message to display any HTML like buttons or links.

![toastr](https://user-images.githubusercontent.com/40183553/57030571-2906ca00-6c13-11e9-9ee8-92785bd471f6.PNG)

Locally in my repository, all I have is:

```
this.toastr.error('message: <button>push me...</button>','',{
  enableHtml: true,
  disableTimeout:true
});
```

and it displays the same (without rendering the button) as your demo page.

Oh, and I'm using Angular 6 with BS 4

**Comment by scttcper** [comment]
only specific tags will work like `<h1>` as its sanitized

https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toastr.service.ts#L270
