### ISSUE TITLE
preventDuplicates not working if title is different

### ISSUE THREAD

**Issue by santu47** [scttcper/ngx-toastr#659]
preventDuplicates is suppressing toast messages even if title of toast is different.
Though message is sasme, titles are different, since preventDuplicates is to prevent duplicate toast, I assume it should not stop toasts with different titles from displaying. 
correct me if am wrong.

**Comment by scttcper** [comment]
currently, only message is compared.

https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toastr.service.ts#L181-L190

**Comment by ArielLeslie** [comment]
I see that there is a year-old PR to compare both title and message (https://github.com/scttcper/ngx-toastr/pull/526). Is there a reason not to include this change? I would like to use ngx-toastr for an application where multiple sources (shown in the title) send the same message.

**Comment by s4m0r4m4** [comment]
+1 one for this - I just spent a while scratching my head trying to figure out why my toasts were getting counted as duplicates when the titles were different. I have several use cases where the titles are unique strings and the messages are all the same (indicating what source the notification came from). To avoid counting duplicates with the current scheme, I believe I will have to add unique text to the message of each toastr, which will cause them to grow larger and take up more of the UI space.

Just to make sure I have the status correct - the old PR (#526) was closed without being merged, and now there is another PR open (#814). I definitely understand the concern about breaking changes. Perhaps you could put out a new minor version that has an additional configuration property that allows users to control whether titles count in duplicate calculations. The property can default to the way it currently works so nobody gets a breaking change, and then you can switch the default behavior (or not) whenever you feel its appropriate, maybe next major version.

**Comment by domisginger** [comment]
@scttcper im happy to write PR based on @s4m0r4m4 suggested changes if your in agreement?

**Comment by scttcper** [comment]
i think #814 already does some of it

**Comment by s4m0r4m4** [comment]
Seems like a fine place to start, just have to add the configurable param and you're there!

**Comment by s4m0r4m4** [comment]
Awesome thank you, excited to try this out!
