### ISSUE TITLE
Issue on IE Version

### ISSUE THREAD

**Issue by Nagenderpratap** [scttcper/ngx-toastr#660]
toastr not working on IE8,9 ^

**Comment by scttcper** [comment]
might work if you use enough polyfills. wontfix.

**Comment by Nagenderpratap** [comment]
i have used enough polyfills in my angular 7 project but after all not working toastr.

**Comment by luankevinferreira** [comment]
It's not working for me on IE as well.

**Comment by ChrisProlls** [comment]
Same here, even the demo page isn't working ...
