### ISSUE TITLE
Custom toast component in lazy-loading submodule

### ISSUE THREAD

**Issue by javyzheng** [scttcper/ngx-toastr#662]
I defined my custom toast component in a lazy-loading submodule and add `entryComponents: [MyToastComponent],` on this module.

When I try to use it, I got the following error:
```
no component factory found for MyToastConponent. Did you add it to @ngmodule.entrycomponents
```
To solve this problem, I need to import the submodule into the root module, which breaks modularity of the project.

Is there a better way to solve this problem?

**Comment by scttcper** [comment]
not that i know of

**Comment by javyzheng** [comment]
@scttcper, just want to clarify. Do you mean that I am not using it in the right way, or, I have to make the custom toast component available in root module?

**Comment by scttcper** [comment]
making the custom toast available in root is the only way i know to make this work
