### ISSUE TITLE
Options per type 

### ISSUE THREAD

**Issue by Et3rnal** [scttcper/ngx-toastr#663]
Is this possible?
I know we have global and per single toast, but how about something for type?
I want all success and warning toasts to have autoDismiss turned on

I want to make sure it's not there before going through all the toast I have or do a PR  💃

**Comment by scttcper** [comment]
can pass options when triggering a single toast and global options

**Comment by barmyard** [comment]
@Et3rnal 
Did you manage to solve this problem?

@scttcper I don't understand what you are saying, do you have an example?

**Comment by Et3rnal** [comment]
@barmyard It's not possible other.
the 2 methods are global which applies to all and per single toastr

Global:
```
ToastrModule.forRoot({
    timeOut: 10000,
    positionClass: 'toast-bottom-right',
    preventDuplicates: true,
  })
```

Single:
```
this.toastrService.error('everything is broken', 'Major Error', {
  timeOut: 3000
});
```
