### ISSUE TITLE
Custom toastr without animations

### ISSUE THREAD

**Issue by Et3rnal** [scttcper/ngx-toastr#665]
After all the headache IE11 giving me, I decided to get rid of animations altogether, however, the custom toastr (copy of pink) isn't working without it and not that only, once I fire a custom toastr all following normal toasters adapt its animation etc..

So starting with custom then all others start throwing this:
`Found the synthetic property @flyInOut. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.`

and once that happens, I lose the `maxOpened` restriction! 

I had the same issue with animations, so I decided to get rid of it. Now my "pink toastr" doesn't have 
`animations: [..]`

To fix all that I add this:

```
    animations: [
      trigger('flyInOut', [
          state('inactive', style({
              display: 'none',
              opacity: 0
          })),
          state('active', style({})),
          state('removed', style({})),
      ])
    ]
```
Im happy with final result, it just toke me while to figure it out so Im leaving this here.

PS: I'm on v8.10.2 because still on angular 6

**Comment by scttcper** [comment]
Pretty sure 6 works with the latest version

**Comment by Et3rnal** [comment]
I run `npm install ngx-toastr --save` and it got me 8.10.2!

**Comment by scttcper** [comment]
could be npm caching it or if this is a work project there could be some other setting happening.

`npm install ngx-toastr@10.0.4 --save`

you can see what the latest tag is by doing `npm info ngx-toastr@latest version`
