### ISSUE TITLE
The demo is not working on IE 11

### ISSUE THREAD

**Issue by luankevinferreira** [scttcper/ngx-toastr#673]
https://scttcper.github.io/ngx-toastr/

Is it a bug or anything else?

**Comment by gustavomerini** [comment]
+1

**Comment by brenonaraujo** [comment]
+1

**Comment by pzmuda13** [comment]
You have to add polyfill for Object.keys 
import 'core-js/features/object/keys';

This worked for me :)

**Comment by scttcper** [comment]
it's usually polyfills. closing unless there's some issue blocking ie 11

**Comment by dlsso** [comment]
@pzmuda13  Does not work for me, but I may be seeing a different issue. Toast is there, just mangled.
