### ISSUE TITLE
does not work with angular 8

### ISSUE THREAD

**Issue by taskiukas** [scttcper/ngx-toastr#674]
with angular 8
when opening toast, this error occurs: Failed to execute 'createElement' on 'Document': The tag name provided ('') is not a valid name.

**Comment by mo3in** [comment]
+1

**Comment by matiasromero** [comment]
+1

**Comment by scttcper** [comment]
angular 8 works fine for me, are you doing anything else like enabling ivy?

**Comment by SEVCO** [comment]
Caused by ;) 

  "angularCompilerOptions": {
    "enableIvy": true
  }

thanks

**Comment by taskiukas** [comment]
thanks

**Comment by mo3in** [comment]
ivy is enable and toastr not working yet ...

**Comment by scttcper** [comment]
yeah we know bro

**Comment by mo3in** [comment]
i have big problem in our company ...
we migrate to angular 8 and we dont have any toast from apps :)
is not problem i send pull request for migrating to angular 8 ?

**Comment by scttcper** [comment]
your best bet is to disable ivy
