### ISSUE TITLE
CountDuplicated problem on Angular 7/ Tsc 3.1.5

### ISSUE THREAD

**Issue by Andranik-89** [scttcper/ngx-toastr#675]
Hi everyone, I am getting an error when adding ToastrModule with root if there is a countDuplicates property. Seems the compiler doesn't really recognise it.

**Comment by Andranik-89** [comment]
![image](https://user-images.githubusercontent.com/20794092/59515838-17cb0180-8ed1-11e9-8e55-668534d664fb.png)

**Comment by scttcper** [comment]
what version do you have installed

**Comment by Andranik-89** [comment]
Hi. "ngx-toastr": "^9.1.1"

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr/releases/tag/v10.0.0

**Comment by Andranik-89** [comment]
@scttcper thank you Scott, I am not getting the error after updating. However the error toastr has now very strange 'wave-like' white splashes on it - is this ok? 
![image](https://user-images.githubusercontent.com/20794092/59528480-6d160b80-8eef-11e9-983d-2eeecbace690.png)

**Comment by Andranik-89** [comment]
its hight has also shrinked twice as you see on the screenshot

**Comment by scttcper** [comment]
did you check the breaking changes for v10
