### ISSUE TITLE
Broken styles in IE 11 in 10.0.4

### ISSUE THREAD

**Issue by dlsso** [scttcper/ngx-toastr#677]
Toastr 9.1.1 was not working at all with Angular 7 in IE 11, Edge and Safari.
Updated to 10.0.4, fixed that problem.

However, now that the toast is showing, I can see that styles are broken in IE 11 (other browsers fine), see image.

Based on feedback for other issues such as #673 I added all core-js es6 and es7 polyfills, but that did not fix the issue.

Based on that I expect it's a CSS issue, but unfortunately don't have the tools to debug it effectively.
We are not applying any styles to `.toast`, so breaking changes for 10.0.0 should not be in play here.

![image](https://user-images.githubusercontent.com/6238782/59944073-7cceac00-9429-11e9-8c43-6f19925ea252.png)

**Comment by dlsso** [comment]
Did a few more tests, the change in behavior between **** and **10.0.4** happened at **9.1.2**.

**Comment by scttcper** [comment]
please open a PR if this is still an issue. not targeting ie 11 with this package.
