### ISSUE TITLE
Broken toastr in Angular

### ISSUE THREAD

**Issue by yannickboy15** [scttcper/ngx-toastr#679]
Sup,

I got everything to the latest version. Bootstrap, ngx-toastr and the Angular-CLI. There's something really weird that happens though. Upon triggering a toast, I get to see the following:

<img width="1429" alt="Schermafbeelding 2019-06-26 om 23 41 08" src="https://user-images.githubusercontent.com/20385056/60217199-78acef00-986c-11e9-90ac-06539551df37.png">
You see the text appear, but there's no box around.

Now when I manually import all the styles, I get to see the following:
<img width="1015" alt="Schermafbeelding 2019-06-26 om 23 40 45" src="https://user-images.githubusercontent.com/20385056/60217206-7ea2d000-986c-11e9-89e0-442e650569a9.png">

As you can see, the box is there. It's not properly shaped, the format of the box in general is just messed up and so on.

Been googling a bit but I am struggling to find someone with the same issue, hence I'll be reporting it here to see if there's a solution. Cheers!

**Comment by scttcper** [comment]
What version of ngx-toastr are you using?

**Comment by yannickboy15** [comment]
I'm using the 10.0.4 version. I'm on Angular 7 and Bootstrap 4.3.1.

Op do 27 jun. 2019 04:28 schreef Scott Cooper <notifications@github.com>:

**Comment by scttcper** [comment]
It seems like there’s some styles colliding with something else you’re using. Should try to find out where those other styles are coming from. Are you passing any settings to ToastrModule.forRoot?

**Comment by yannickboy15** [comment]
Negative, it's the same setup as how it's explained on the Github and npm site.

I've got Bootstrap 4, styles.scss that's empty and the CSS files from ngx-toastr, nothing else. Not sure what could be it.

**Comment by yannickboy15** [comment]
Do you have an example of some CSS classes ngx-toastr uses? I might be able to see if the bootstrap 4 template is still overwriting it.

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr.css

**Comment by yannickboy15** [comment]
Alright.

I tested this, disabled all stylesheets including the bootstrap one and it still happens as in the screenshots. I tried it with Bootstrap enabled, neither worked. I am pretty much stuck on how this can happen. I'll see if it'll work with a complete new project.

**Comment by yannickboy15** [comment]
Update:

After adding `@import "../node_modules/ngx-toastr/toastr.css";` to the styles.scss, it worked. Really weird that the CLI doesn't recognise this, but it might be useful to consider as a fix.
