### ISSUE TITLE
Toast message ignores all timeout settings when inside of an NGRX pipe function

### ISSUE THREAD

**Issue by brandon-sigao** [scttcper/ngx-toastr#687]
I would like to display a toast message in my NGRX effect for some amount of time and then resolve the effect with an action, but for some reason my messages disappear after ~1000ms no matter what I do.  My default is 5000 and I'm overriding it to 10000, but nothing works.  These are all the things I've tried:

This one should be the most clean and functional, but does not work:
```
const t = this.toastrService.warn('blah', 'blah', { timeOut: 10000});
return t.onHidden.map(()=> myNewAction()); 
```

This one is my backup, but still no dice:
```
 return of(true).pipe(
                    map(() => this.toastrService.show('blah', 'blah', { timeOut: 0 })),
                    delay(10000),
                    tap(t => t.toastRef.close()),
                    map(() => myNewAction())
                );
```
Hell, at this point I'd be fine with launching the toast message and not even waiting for it to be done to resolve the effect.  I just want ANYTHING on this planet to get that stupid message to stick around for more than 1 second.  I'm definitely out of ideas on this one.

**Comment by scttcper** [comment]
try using disableTimeOut: true
