### ISSUE TITLE
No display in IE11 / Edge

### ISSUE THREAD

**Issue by chriswks** [scttcper/ngx-toastr#701]
Possibly relates to; https://github.com/scttcper/ngx-toastr/issues/673

Angular Version : 8.0

ngx-toastr versions tried : 8.73, 9.1.1, 9.1.2, 10.0.2, 10.0.4, 10.1.0

So we upgraded to angular 8, and the toast notifications completely stopped showing for IE11 / Edge (and I would suspect also Safari though I have no way to test) yet work fine in Firefox / Chrome.

Upon debugging you quickly notice that the rendered nodes retain a `display: none` css style attribute when displayed, so they get created but are never visible. I was able to work-around this with a quick specificity selector via media query for the culprit browsers;

```
[role=alert].alert.ng-trigger.ng-trigger-flyInOut.ng-animating {
        display: block !important;
 }
```

However of course it's not ideal. Wondering if there's some additional steps I'm missing and if this is somehow unique or if others have ran into the same issue? I saw the other bugs about CSS discrepancies but they at least still display the toast but just look incorrectly styled, with this issue they just don't display at all, as example;

Appended Node HTML to Chrome;
![image](https://user-images.githubusercontent.com/11682512/63363215-d4f63180-c338-11e9-8a6b-7fc15596f54d.png)

Appended Node HTML to Edge;
![image](https://user-images.githubusercontent.com/11682512/63363558-72516580-c339-11e9-99f3-bd3b83b3f9a0.png)

Thanks, dig the package otherwise!

**Comment by kmiasko** [comment]
Same issue on Angular: 7.2.15

**Comment by scttcper** [comment]
let me know if this is fixed in in 10.2.0
https://github.com/scttcper/ngx-toastr/releases/tag/v10.2.0

**Comment by kmiasko** [comment]
> let me know if this is fixed in in 10.2.0

@scttcper Works for me. Thank you for quick fix :)

**Comment by GurpreetSingh5** [comment]
Hi @scttcper , still facing this issue in edge.

**Comment by scttcper** [comment]
please open a PR, otherwise closing. its most likely an animation issue or a css issue.
