### ISSUE TITLE
No display with 10.2.0

### ISSUE THREAD

**Issue by TiGGeRTSK** [scttcper/ngx-toastr#708]
You can see text popping thru the very tiny bit of background. Custom component tho. Maybe docs for custom one needs to be updated?
Every browser affected.
Rolling back to 10.0.4 or 10.1.0 helped.
![image](https://user-images.githubusercontent.com/16795332/64232959-3d3e3900-cf1d-11e9-94b0-0b3a9b0ab5be.png)

**Comment by scttcper** [comment]
Maybe need to set the display property on the background portion to block in your css?
