### ISSUE TITLE
NGX Toastr TEXT not showing on build

### ISSUE THREAD

**Issue by nickykapur** [scttcper/ngx-toastr#710]
I have been trying to get my application ready for production, and realized my toastrs appearing but not showing the messages in it.

**Comment by pixeldepth** [comment]
I have the same problem, but for me text is missing also for ng serve.
The problem isn't css, because content of notify is emtpy, for example:
```
<div id="toast-container" class="toast-top-right toast-container">
  <div class="ng-tns-c19-6 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-success" style="opacity: 1;">
    <!--container-->
    <!--container-->
    <!--container-->
    <!--container-->
    <!--container-->
  </div>
</div>
```
Project uses Angular 9.0.0-next.6

**Comment by raysuelzer** [comment]
Sounds like an AOT issue

**Comment by scttcper** [comment]
need some way to reproduce

**Comment by alainbelez** [comment]
> I have the same problem, but for me text is missing also for ng serve.
> The problem isn't css, because content of notify is emtpy, for example:
> 
> ```
> <div id="toast-container" class="toast-top-right toast-container">
>   <div class="ng-tns-c19-6 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-success" style="opacity: 1;">
>     
>     
>     
>     
>     
>   </div>
> </div>
> ```
> 
> Project uses Angular 9.0.0-next.6

i also have this output using angular 8.3.8 with ivy enabled
