### ISSUE TITLE
(click)="doSomething()" is not rendered in innerHtml. Trusted HTML support should be added for links/anchors in message.

### ISSUE THREAD

**Issue by KumarNarendra** [scttcper/ngx-toastr#712]
(click)="doSomething()" is not rendered in innerHtml. Trusted HTML support should be added for links/anchors in message.
Need the below HTML to be rendered:
<span class="btn-link text-blue cusrsor-pointer" (click)="doSomething($event)">Details</span>

instead, it is rendered as :
<span class="btn-link text-blue cusrsor-pointer">Details</span>

**Comment by scttcper** [comment]
Use a custom toast instead.

**Comment by KumarNarendra** [comment]
Tried the custom component as well but no luck.
`<div class="row" [style.display]="state.value === 'inactive' ? 'none' : ''">
  <div class="col-9">
    <div *ngIf="title" [class]="options.titleClass" [attr.aria-label]="title">
      {{ title }}
    </div>
    <div *ngIf="message && options.enableHtml" role="alert" aria-live="polite" [class]="options.messageClass"
      [innerHTML]="message | safeHtml">
    </div>
    <div *ngIf="message && !options.enableHtml" role="alert" aria-live="polite" [class]="options.messageClass"
      [attr.aria-label]="message">
      {{ message }}
    </div>
  </div>
  <div class="col-3 text-right">
    <span *ngIf="options.closeButton" (click)="remove()" class="sap-icon sap-decline">
      close
    </span>
  </div>
</div>
<div *ngIf="options.progressBar">
  <div class="toast-progress" [style.width]="width + '%'"></div>
</div>`

**Comment by KumarNarendra** [comment]
@scttcper Please share an example where it works.

**Comment by scttcper** [comment]
in a custom component you can add all the click actions you want. angular cannot compile functioning templates from strings in the browser, that's the whole point of angular 2+
