### ISSUE TITLE
Latest ngx-toastr not working in prod, only dev 

### ISSUE THREAD

**Issue by gunnarsireus** [scttcper/ngx-toastr#713]
Hello. 
I have been using ngx-toastr for some months starting with ngx-toastr 5 and Angular2 version 4. 
After updating to Angular2 version 8 ngx-toastr works as before when compiling with webpack dev. However, with webpack prod there is no toast at all showing up.
I then switched back to ngx-toastr 6.5.0 and then it worked again in both dev and prod mode. That's nice.  
I have done another version of the application using lazy loading and AOT, ahead of time compilation. With this version ngx-toastr 6.5.0 works almost perfectly but not ngx-toastr 10. 
However, with ngx-toastr 6.5.0 the small cross indicating where to click to delete the toast is gone. The cross has disappeared in the AOT version but not in the other version without AOT. Can you please explain what's happening?

**Comment by scttcper** [comment]
there's new class names in newer versions. its most likely a css issue
