### ISSUE TITLE
Notifications sticking in my screen - with opacity 0 and blocking my navbar

### ISSUE THREAD

**Issue by DedalusOsX** [scttcper/ngx-toastr#714]
So here's the problem:

I use Angular 7 and ngx-toastr's 10.2.0 version.

After the notification appears it's not removed, but rather it stays with changing only its own opacity!

**app.module.ts**
`    
BrowserModule,
BrowserAnimationsModule,
HttpClientModule,
AppRoutingModule,
ReactiveFormsModule,
ToastrModule.forRoot({
      timeOut: 1000,
      closeButton: true,
 }),`

I've uploaded styles, through angular.json as mentioned in the documentation. Custom style that i applied - I don't believe they interfere, in any case here they are:
**_toastr.scss**
`.toast-top-full-width{

  >div{
    border-radius: 0 !important;
    width: 100vw !important;
    height: $nav-size !important;
    box-shadow: none !important;
  }
}

.toast-top-right{
  >div{
    border-radius: 0 !important;
    box-shadow: none !important;

    &.toast-error{background-color: $red !important;}
    &.toast-success{background-color: $green !important;}
    &.toast-warning{background-color: $yellow !important;}
    &.toast-info{background-color: $blue !important;}
  }
}
`
and the DOM looks like this after the notification is hidden:
`<div toast-component="" class="toast-error ngx-toastr ng-trigger ng-trigger-flyInOut" style="opacity: 0;"><button aria-label="Close" class="toast-close-button ng-tns-c4-0 ng-star-inserted" style=""><span class="ng-tns-c4-0" aria-hidden="true">×</span></button><div aria-live="polite" role="alertdialog" class="toast-message ng-star-inserted" aria-label="Permission denied" style=""> Permission denied </div></div>`

Attaching [image](https://drive.google.com/file/d/1TZ8bMCzWknyl7v-SX69qWrsLYOd1S4Qg/view?usp=sharing) from html debugging!

**Comment by scttcper** [comment]
honestly i would try another version of angular 7. like 7.2.15

**Comment by DedalusOsX** [comment]
I've even upgraded to angular 8.2.8 and toastr 11.0.0. The problem still remains :/

**Comment by DedalusOsX** [comment]
@scttcper found the issue - so this problem occurs if i create a toaster service injectable like so:

in my app.module.ts

`    { provide: 'notifier', useClass: ToastrService },`

If i call ToastrService directly in the components the issue is gone. Please fix this. It's more convenient to use Injectable! 

Thanks

**Comment by scttcper** [comment]
Not sure how you would fix that

**Comment by scttcper** [comment]
You could extend the module or implement your own instead of making only a provider. I think you're missing the forRoot function in yours https://github.com/scttcper/ngx-toastr/blob/master/src/lib/toastr/toastr.module.ts#L22
