### ISSUE TITLE
Overlay-container not being removed from DOM and toastId keeps increasing

### ISSUE THREAD

**Issue by kirstenfrager** [scttcper/ngx-toastr#719]
When dismissing a toast, the 'overlay-container', container stays in the DOM.

This is an inconvenience for me as I have changed the css for the overlay-component to show on the screen so that the background elements cannot be clicked while the toast is open;

css used for overlay-component to display over content:
`.overlay-container {
  background-color: rgba(0, 0, 0, 0.4);
  z-index: 999999;
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
}`

Overlay over content so that background buttons/links etc cannot be clicked while open:
<img width="1168" alt="Screen Shot 2019-10-06 at 4 21 49 pm" src="https://user-images.githubusercontent.com/21212453/66264661-6c660400-e855-11e9-998b-8cef158a4e34.png">

However, even when toast is dismissed, the container still stays in the DOM and so the backdrop is still covering the content.

<img width="455" alt="Screen Shot 2019-10-06 at 4 16 40 pm" src="https://user-images.githubusercontent.com/21212453/66264651-3294fd80-e855-11e9-8c9b-d209df1bc408.png">

Also, even when closing the toast, when a new one is opened it has an increased toastID. Shouldn't it start at 1 again if the previous one has been closed? Is this why the container is still showing in the DOM even when the toast is closed?

<img width="442" alt="Screen Shot 2019-10-06 at 4 16 22 pm" src="https://user-images.githubusercontent.com/21212453/66264650-31fc6700-e855-11e9-975e-e65f9ea8d44f.png">

Code for creating toast:
<img width="899" alt="Screen Shot 2019-10-06 at 4 25 15 pm" src="https://user-images.githubusercontent.com/21212453/66264685-e8604c00-e855-11e9-81fb-394ec99a10d8.png">

`showAlert(message: string, title?: string) {
const toastRef = this.toastr.info(
this.getTranslatedText(message), 
this.getTranslatedText(title), {
      positionClass: 'toast-center-center',
      closeButton: true,
      timeOut: 0,
      extendedTimeOut: 0
    })
    // toast.onShown.subscribe(() => $("#toast-overlay").show());
    console.log('toast', toastRef)
    toastRef.onHidden.subscribe((action) => {
      // function goes here
    });
  }`

in app.module.ts:
`    ToastrModule.forRoot({
      preventDuplicates: true,
      maxOpened: 1
    }),`

package.json:
    "ngx-toastr": "^10.1.0",
    "@angular/animations": "^7.2.2",
    "@angular/cdk": "^7.2.2",
    "@angular/common": "^7.2.2",
    "@angular/compiler": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/material": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",

**Comment by scttcper** [comment]
The id increasing is how toastr has always worked and the container isn’t removed? I think what you might be looking for is a modal

**Comment by kirstenfrager** [comment]
@scttcper i was trying to use the toastr in the same way as I saw that there was an overlay-component which could be modified with css. are you able to explain to me though how come even when closing the toastr the template stays in the DOM?

**Comment by scttcper** [comment]
the container is reused between toasts and is not intended to be used as a modal.
