### ISSUE TITLE
Got an error with Ivy and AOT

### ISSUE THREAD

**Issue by ottodranik** [scttcper/ngx-toastr#721]
Got an error in DEV mode with Ivy and AOT on use simple:
`this.toastr.success('Hello world!', 'Toastr fun!');`
Am I doing something wrong? @angular/compiler, @angular/platform-browser-dynamic are in dependencies.

UPD. Works (but without any data except icon) only if I add 
`import '@angular/compiler';`
in app module file o_O. Is it normal?
> ERROR Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
>   - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
>   - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
>   - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
>     at getCompilerFacade (core.js:482)
>     at Function.get (core.js:25054)
>     at getComponentDef (core.js:1515)
>     at assertComponentType (core.js:1665)
>     at ComponentFactoryResolver.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.ComponentFactoryResolver.resolveComponentFactory (core.js:21471)
>     at DomPortalHost.push../node_modules/ngx-toastr/__ivy_ngcc__/fesm5/ngx-toastr.js.DomPortalHost.attachComponentPortal (ngx-toastr.js:200)
>     at DomPortalHost.push../node_modules/ngx-toastr/__ivy_ngcc__/fesm5/ngx-toastr.js.BasePortalHost.attach (ngx-toastr.js:161)
>     at OverlayRef.push../node_modules/ngx-toastr/__ivy_ngcc__/fesm5/ngx-toastr.js.OverlayRef.attach (ngx-toastr.js:288)
>     at ToastrService.push../node_modules/ngx-toastr/__ivy_ngcc__/fesm5/ngx-toastr.js.ToastrService._buildNotification (ngx-toastr.js:652)
>     at ToastrService.push../node_modules/ngx-toastr/__ivy_ngcc__/fesm5/ngx-toastr.js.ToastrService._preBuildNotification (ngx-toastr.js:615)

**Comment by ottodranik** [comment]
There is a high probability that current issue is connected to Angular 9 (next 6 and 7) issue

**Comment by ottodranik** [comment]
Had a lot of similar issues with Angular 9 (next6, 7 and 8) in a lot of packages. Maybe, some braking changes in Angular 9.

**Comment by ottodranik** [comment]
I investigated a problem and understood that it works fine with latest stable Angular 8.2.10 (with Ivy and production AOT) and with newest Angular 9.0.0-next.10 too (with Ivy and AOT).
I think, that Angular 9.0.0-next.6 and next.7 had some breaking changes and some errors during a compilation process (Example: "Can't compile with Angular 9 (next7) #1728" issue of angular-google-maps package is one of them)

**Comment by hiepxanh** [comment]
I have the same issue, what should I do? adding `import '@angular/compiler';` like you to application or upgrade to angular next 10?
