### ISSUE TITLE
Possible issue with ivy compiler?

### ISSUE THREAD

**Issue by initplatform** [scttcper/ngx-toastr#732]
Hello,

Just upgraded all my packages and tried to build with ivy, I am getting this error 

```
Compiling ngx-toastr : es2015 as esm2015

ERROR in No suitable injection token for parameter 'el' of class 'ToastContainerDirective'.
no type or decorator
```

I load `ToastrModule.forRoot(),` in my app.module, then I have some lazy loaded children modules that leverage ToastrService. 

Was not including  `ToastrModule` in the includes for those lazy modules, not sure I have to, but just to see I added them and still same error. 

```
"ngx-toastr": "11.2.0",
"@angular/core": "8.2.13",
```

build command: `node --max_old_space_size=8000 ./node_modules/.bin/ng build --prod --source-map --build-optimizer=true --statsJson=true`

of course `"enableIvy": true` in tsconfig

**Comment by scttcper** [comment]
i think this will only work in angular 9's ivy compiler

**Comment by ViktorDimitrievski** [comment]
I had the same problem. And I fix it with  `"enableIvy": false` for now it's not working with Ivy compiler.

**Comment by Coooi** [comment]
@scttcper I'm having exactly this issue now with Ivy.
Disabling it would not be an option right now since it goes against the stream.

**Comment by konuch** [comment]
Agreed, disabling Ivy build is not really a fix for this issue.

**Comment by scttcper** [comment]
yes it is. if you want to keep ivy, upgrade to 9 rc
