### ISSUE TITLE
simplify bootstrap 4 styles integration

### ISSUE THREAD

**Issue by gladkiy** [scttcper/ngx-toastr#738]
I have angular 8 app with UI theme based on bootstrap v4. I also use Less.
Can you compile complete `toastr-bs4-alert.css` with all needed functionality from bootstrap v4?

**Comment by BernardoMB** [comment]
> I have angular 8 app with UI theme based on bootstrap v4. I also use Less.
> Can you compile complete `toastr-bs4-alert.css` with all needed functionality from bootstrap v4?

@gladkiy This is what I did in my Angular Material project just to have these toasts.

In my global styles .scss file (styles.scss) a placed the following code:

`// Option 1 (Regular style)

/* @import '~ngx-toastr/toastr'; */

// Option 2 (Bootstrap 4 styles)
// Requires bootstrap

/* @import '~bootstrap/scss/bootstrap';
@import '~ngx-toastr/toastr-bs4-alert'; */

// Option 2 [Alternative] (Bootstrap 4 styles)
// if you'd like to use it without importing all of bootstrap it requires only functions, variables and mixins.

@import '~bootstrap/scss/functions';
@import '~bootstrap/scss/variables';
@import '~bootstrap/scss/mixins';
@import '~ngx-toastr/toastr-bs4-alert';`

Uncomment the option you would like to use.

**Comment by gladkiy** [comment]
What do you suggest me if I use Less instead of Sass?

**Comment by BernardoMB** [comment]
> @BernardoMB What do you suggest me if I use Less instead of Sass?

They specify in the documentation that they only support the Bootstrap 4 styles for Sass projects.

Let me see if there is a workaround.
