### ISSUE TITLE
toast not visible in safari

### ISSUE THREAD

**Issue by salah-yousef** [scttcper/ngx-toastr#741]
toast not visible in safari
display: none; problem
current version "ngx-toastr": 10.2.0,
angular version 7.2.0
<img width="1440" alt="Screen Shot 2019-11-19 at 16 25 57" src="https://user-images.githubusercontent.com/17572461/69150266-67999e80-0ae9-11ea-8661-c0cb104348f2.png">

**Comment by axeleroy** [comment]
Did you take a look at #609?
TL;DR : remove `display: none` from the inactive state (but keep `opacity: 0`) and you're all done.
