### ISSUE TITLE
maxOpened = 1 not working when there are many calls at the same time

### ISSUE THREAD

**Issue by kimljj** [scttcper/ngx-toastr#742]
Hi,

firstly many thanks for this wonderful library. 

It's working very well until I set maxOpened to 1 and called one of the methods(show(), error() and warn()) many times "at the same time" for example I have a method named openToast() in a component. 

` 
// global options
imports: [
  ToastrModule.forRoot({
     maxOpened: 1
    preventDuplicates: true,
  }),
],

//method
openToast() {
 this.toastrService.error('Show a error', 'Major Error');
 this.toastrService.error('Show an another error', 'Major Error');
 }`

 both of them will be opened by calling the method openToast()

Could you please take a look at it and tell me if I did something wrong?

![1](https://user-images.githubusercontent.com/13731896/69372453-07019180-0ca2-11ea-9c80-5f96b2102c8f.JPG)

**Comment by mihaiioan** [comment]
Any updates on this?

**Comment by yl-endress** [comment]
maxOpened seems to be buggy in 10.2.0, too!
Also the current demo seems to be affected. Simply click in a fast manner on the Toast button and you will see a lot of them:

![image](https://user-images.githubusercontent.com/44203645/72069012-83017880-32e6-11ea-82cd-2d78d2dfd549.png)

In rare cases some messages stay hidden (version 10.2.0):
![image](https://user-images.githubusercontent.com/44203645/72069140-d5429980-32e6-11ea-89e4-037fcb3d5e78.png)

**Comment by kimljj** [comment]
i have fixed it in https://github.com/scttcper/ngx-toastr/pull/743. But still wating for merging
