### ISSUE TITLE
Automatic update of Toastr content possible?

### ISSUE THREAD

**Issue by elementalPRESS** [scttcper/ngx-toastr#751]
I really love ngx-toastr, but is there any possibility to update the content of an already opened toastr window?

I tried something like:

`this.toastrService.success("Test ${this.timer}",'Success', {
	closeButton: true,
	disableTimeOut: true
});`

where timer is something like:

`import { timer } from "rxjs";
timer(0, 100).subscribe(()=> {
	this.timer = this.timer + 0.5;
})`

**Comment by scttcper** [comment]
would require a custom toast component

**Comment by elementalPRESS** [comment]
> would require a custom toast component

Thx for your answer. But please can you give me a code example how this can look like?

**Comment by scttcper** [comment]
you will need to create a toast component and pass that in and then after triggering it use the ActiveToast you get back to do activeToast.toastRef and access the component directly.
