### ISSUE TITLE
WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 264:39-57    "export 'ɵɵdefineInjectable' was not found in '@angular/core' 

### ISSUE THREAD

**Issue by bishoe** [scttcper/ngx-toastr#765]
`WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 264:39-57   
"export 'ɵɵdefineInjectable' was not found in '@angular/core'        

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 368:30-48   
"export 'ɵɵdefineInjectable' was not found in '@angular/core'        

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 672:36-54   
"export 'ɵɵdefineInjectable' was not found in '@angular/core'        

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 264:135-143 
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 368:108-116 
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 368:136-144 
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 368:172-180 
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 368:198-206 
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 672:126-134 
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 672:150-158 
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 672:169-177 
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 672:189-197 
"export 'ɵɵinject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js 672:213-221 
"export 'ɵɵinject' was not found in '@angular/core'`

**import { ToastrService } from 'ngx-toastr';
constructor(public service: UserService  ,private toastr:ToastrService ) { }**

Angular CLI: 7.2.4
Node: 12.14.0
OS: win32 x64
Angular: 7.2.16
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/animations               8.2.14
@angular/cli                      7.2.4
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

PS C:\Users\bishoe\Desktop\StarAdmin-Free-Angular-Admin-Template-master>

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr#dependencies

**Comment by bishoe** [comment]
What do I do specifically to solve this problem?

**Comment by scttcper** [comment]
use the correct version of angular for the version of ngx-toastr

**Comment by bishoe** [comment]
now it work s thank you

**Comment by jobincs** [comment]
just remove the ee from 'ɵɵdefineInjectable' use defineInjectable in import and usage in the library file
