### ISSUE TITLE
closeButton is not working when toastClass

### ISSUE THREAD

**Issue by raugaral** [scttcper/ngx-toastr#768]
Hi I found a problem when add a toastClass property.
The toast close button doesn't work. 
im working on 11.3.0

For example:

> this.toastr.success(message, title, {
      positionClass: 'toast-bottom-right',
      toastClass: 'my-toast success-toast',
      timeOut: 300000,
      closeButton: true,
      tapToDismiss: true,
    });

**Comment by vglaeser** [comment]
This problem also occurs with onTap-Event.

**Comment by scttcper** [comment]
make sure you have pointer events enabled in your stylesheet.

**Comment by pedrobacchini** [comment]
> make sure you have pointer events enabled in your stylesheet.

my mistake was exactly that, thanks
