### ISSUE TITLE
Error in importing the library

### ISSUE THREAD

**Issue by Luperco** [scttcper/ngx-toastr#779]
Hi, I'm trying to use ngx-toastr but i doesn't work. 
I've just included the module in my main module (together with the required animation module.

I'm receiving the following error during applicazione compilation:

client:168 node_modules/ngx-toastr/portal/portal.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.

This is my package.json:

{
  "name": "armad-backoffice-ui",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.16",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@clr/angular": "^1.3.5",
    "@clr/icons": "^1.3.5",
    "@clr/ui": "^1.3.5",
    "@webcomponents/custom-elements": "^1.0.0",
    "core-js": "^2.5.4",
    "ngx-toastr": "^12.0.0",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/cli": "~7.3.0",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}

Thanks.

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr#dependencies

**Comment by jafar-albadarneh** [comment]
Same issue here! I've double-checked the dependencies, all seem fine.
```json
{
  "name": "projectx",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.12",
    "@angular/common": "8.2.12",
    "@angular/compiler": "8.2.12",
    "@angular/core": "8.2.12",
    "@angular/forms": "8.2.12",
    "@angular/platform-browser": "8.2.12",
    "@angular/platform-browser-dynamic": "8.2.12",
    "@angular/router": "8.2.12",
    "@fortawesome/fontawesome-free": "5.11.2",
    "@ng-select/ng-select": "^3.7.2",
    "chartjs": "^0.3.24",
    "ngx-toastr": "^12.0.0",
    "popper.js": "1.16.0",
    "rxjs": "6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.803.15",
    "@angular/cli": "8.3.15",
    "@angular/compiler-cli": "8.2.12",
    "@angular/language-service": "8.2.12",
    "@types/node": "8.9.4",
    "@types/jasmine": "3.3.8",
    "@types/jasminewd2": "2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "3.4.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.1",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "5.4.0",
    "ts-node": "7.0.0",
    "tslint": "5.15.0",
    "typescript": "3.5.3"
  }
}
```

**Comment by scttcper** [comment]
The original poster was using an old version of angular that is incompatible. Are you?
