### ISSUE TITLE
portal.d.ts issues

### ISSUE THREAD

**Issue by marrej** [scttcper/ngx-toastr#781]
![ngx-toastr issue](https://user-images.githubusercontent.com/13024177/75157572-af494b00-5714-11ea-8014-50bb76da0a35.jpg)

ngx-toastr portal types seem to be throwing errors for me in the base example implementation, anyone have solution for this?

**Comment by scttcper** [comment]
What’s in your package.json

**Comment by usamanawazfrt** [comment]
> {
>   "name": "Bingos",
>   "version": "1.0.0",
>   "license": "MIT",
>   "scripts": {
>     "ng": "ng",
>     "service": "ng g s",
>     "component": "ng g c",
>     "start": "ng serve",
>     "build": "ng build --prod",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular-devkit/core": "8.1.0",
>     "@angular/animations": "^8.1.0",
>     "@angular/cdk": "^8.0.2",
>     "@angular/common": "^8.1.0",
>     "@angular/compiler": "^8.1.0",
>     "@angular/core": "^8.1.0",
>     "@angular/flex-layout": "8.0.0-beta.26",
>     "@angular/forms": "^8.1.0",
>     "@angular/http": "^7.2.15",
>     "@angular/material": "^8.0.2",
>     "@angular/material-moment-adapter": "^8.0.2",
>     "@angular/platform-browser": "^8.1.0",
>     "@angular/platform-browser-dynamic": "^8.1.0",
>     "@angular/router": "^8.1.0",
>     "@angular/service-worker": "^9.0.0",
>     "@swimlane/ngx-charts": "^12.0.1",
>     "@swimlane/ngx-datatable": "^15.0.2",
>     "ajv": "^6.10.1",
>     "angular-calendar": "^0.27.12",
>     "chart.js": "^2.8.0",
>     "chartist": "^0.11.4",
>     "core-js": "^3.1.4",
>     "d3": "^5.9.7",
>     "date-fns": "^1.30.1",
>     "hammerjs": "^2.0.8",
>     "html-to-pdfmake": "^1.2.0",
>     "lodash": "^4.17.11",
>     "moment": "^2.24.0",
>     "ng-chartist": "4.1.0",
>     "ng-multiselect-dropdown": "^0.2.3",
>     "ng2-charts": "2.3.0",
>     "ng2-completer": "^3.0.2",
>     "ng2-dragula": "2.1.1",
>     "ng2-file-upload": "1.3.0",
>     "ng2-smart-table": "^1.5.0",
>     "ng2-validation": "^4.2.0",
>     "ngx-facebook": "^2.4.0",
>     "ngx-perfect-scrollbar": "8.0.0",
>     "ngx-quill": "^7.0.2",
>     "ngx-toastr": "^12.0.0",
>     "pdfmake": "^0.1.62",
>     "quill": "^1.3.6",
>     "rxjs": "^6.5.2",
>     "rxjs-compat": "^6.5.2",
>     "rxjs-tslint": "^0.1.7",
>     "uglify-es": "^3.2.2",
>     "zone.js": "^0.9.1"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "^0.803.25",
>     "@angular/cli": "^8.1.0",
>     "@angular/compiler-cli": "^8.1.0",
>     "@angular/language-service": "^8.1.0",
>     "@types/chartist": "0.9.46",
>     "@types/jasmine": "~3.3.13",
>     "@types/jasminewd2": "~2.0.6",
>     "@types/jquery": "^3.3.30",
>     "@types/node": "~12.0.12",
>     "codelyzer": "~5.1.0",
>     "jasmine-core": "~3.4.0",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "^4.1.0",
>     "karma-chrome-launcher": "~2.2.0",
>     "karma-cli": "~2.0.0",
>     "karma-coverage-istanbul-reporter": "~2.0.5",
>     "karma-jasmine": "~2.0.1",
>     "karma-jasmine-html-reporter": "^1.4.2",
>     "protractor": "^5.4.1",
>     "ts-node": "~8.3.0",
>     "tslint": "~5.18.0",
>     "typescript": "~3.4.5",
>     "webpack-cli": "^3.3.10"
>   }
> }

Same error occurs with my this Package.json

**Comment by scttcper** [comment]
v12 requires angular >9 
https://github.com/scttcper/ngx-toastr#dependencies
