### ISSUE TITLE
ngx-restangular.module.d.ts issue

### ISSUE THREAD

**Issue by aravind1991** [scttcper/ngx-toastr#788]
Updated angular 5 to 9 i got below error:

ERROR in node_modules/ngx-restangular/dist/esm/src/ngx-restangular.module.d.ts:5:51 - error NG6005: RestangularModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

  static forRoot(config1?: any, config2?: any): ModuleWithProviders;

**Comment by scttcper** [comment]
What is restangular

**Comment by aravind1991** [comment]
@scttcper 
https://www.npmjs.com/package/ngx-restangular

below my package.json:

"dependencies": {
    "@angular/animations": "^9.0.4",
    "@angular/cdk": "9.1.0",
    "@angular/cli": "^9.0.4",
    "@angular/common": "^9.0.4",
    "@angular/compiler": "^9.0.4",
    "@angular/compiler-cli": "^9.0.4",
    "@angular/core": "^9.0.4",
    "@angular/forms": "^9.0.4",
    "@angular/material": "9.1.0",
    "@angular/material-moment-adapter": "9.1.0",
    "@angular/platform-browser": "^9.0.4",
    "@angular/platform-browser-dynamic": "^9.0.4",
    "@angular/platform-server": "^9.0.4",
    "@angular/router": "^9.0.4",
    "@angular/upgrade": "9.0.3",
    "@angularclass/hmr": "2.1.3",
    "@angularclass/hmr-loader": "3.0.4",
    "ajv": "^6.0.0",
    "angular-date-value-accessor": "0.0.2",
    "angular-in-memory-web-api": "~0.2.4",
    "angular2-toaster": "^8.0.0",
    "big-number": "^2.0.0",
    "bluebird": "^3.5.3",
    "bootstrap": "^3.2.0",
    "core-js": "^2.4.1",
    "dayjs": "^1.8.17",
    "dcl-component": "^4.4.4",
    "jquery": "^2.2.4",
    "jquery-slimscroll": "^1.3.8",
    "lodash": "^4.17.10",
    "lodash.assign": "^4.2.0",
    "moment": "^2.24.0",
    "ng-busy": "^1.4.8",
    "ng2-auto-complete": "^0.12.0",
    "ng2-bootstrap": "^1.6.3",
    "ng2-bootstrap-modal": "^1.0.1",
    "ng2-eonasdan-datetimepicker": "^0.1.4",
    "ng2-google-charts": "^4.0.0",
    "ng2-opd-popup": "^1.1.21",
    "ng2-table": "^1.3.2",
    "ng2-toastr": "^4.1.2",
    "ng4-loading-spinner": "^1.1.3",
    "ngx-bootstrap": "^5.3.2",
    "ngx-gallery": "^5.10.0",
    "ngx-tabs": "0.0.13",
    "ngx-toastr": "^12.0.0",
    "ngxf-uploader": "^1.2.3",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.5.4",
    "systemjs": "^0.19.40",
    "toastr": "^2.1.4",
    "true-case-path": "^1.0.3",
    "tslib": "^1.11.1",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.900.4",
    "@types/jasmine": "2.5.36",
    "@types/lodash": "^4.14.149",
    "@types/node": "^12.11.1",
    "canonical-path": "0.0.2",
    "codelyzer": "^5.1.2",
    "concurrently": "^3.2.0",
    "expose-loader": "^0.7.5",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.2.2",
    "ng2-bs3-modal": "0.10.4",
    "ngx-restangular": "^2.2.3",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",
    "tslint": "^5.9.1",
    "tslint-angular": "^1.1.2",
    "tslint-config-prettier": "^1.15.0",
    "tslint-sonarts": "^1.8.0",
    "typescript": "3.7.5"
  },
  "repository": {}

**Comment by scttcper** [comment]
I'm confused as to why you've opened this issue. You seem to be getting an error from ngx-restangular? Also you have 3 different toast libraries installed.
