### ISSUE TITLE
remove Fn takes toaster id which isn't optional 

### ISSUE THREAD

**Issue by parthdevloper** [scttcper/ngx-toastr#793]
Hello,
I am using ngx-toastr for a while and found the following issue:

![toastr-remove-bug](https://user-images.githubusercontent.com/58413215/76830947-5ae54700-684c-11ea-8068-61075eb6f01e.jpg)

As You see in the Image:

> **Remove function requires 1 argumenet.. (Ie. toastId: number) which is not optional** 

As I See In The Documentation Of Remove Function I see that` "remove(toastId?: number): Takes toaster id which is optional"`
![toastr-docs](https://user-images.githubusercontent.com/58413215/76831426-51a8aa00-684d-11ea-987b-e03604c02637.png)

I want to remove all toastr once I fire the remove Function... But currently not possible.

**Comment by scttcper** [comment]
why not clear?

**Comment by cofad** [comment]
I think updating the documentation for the remove function to delete the note indicating the id is optional would help. That would make it more apparent that clear is intended for removing all toasts.

Happy to submit a PR to update the readme if desired.
