### ISSUE TITLE
Showing toastr cause lost focus from textbox

### ISSUE THREAD

**Issue by MehdiSaeedifar** [scttcper/ngx-toastr#80]
Hi,
Showing toastr cause lost focus from textbox when an async operation call toastr .

**Comment by scttcper** [comment]
I tried this out with an input box and a setInterval opening a new toast and wasn't able to reproduce. What kind of async operation is pulling the focus?

**Comment by MehdiSaeedifar** [comment]
Yeah, it was my fault, sorry.
