### ISSUE TITLE
Error when start a upgraded project from 8 to 9 Angular

### ISSUE THREAD

**Issue by astrO1** [scttcper/ngx-toastr#802]
I upgrade my project from Angular 8 to 9 and now I having this error when I start my application:

**see the error referring the package - at Object.Overlay_Factory [as factory] (ngx-toastr.js:502)**

main.ts:12 Error: Cannot instantiate cyclic dependency! ApplicationRef
    at throwCyclicDependencyError (core.js:5554)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.hydrate (core.js:11593)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.get (core.js:11414)
    at injectInjectorOnly (core.js:822)
    at ɵɵinject (core.js:827)
    at Object.Overlay_Factory [as factory] (ngx-toastr.js:502)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.hydrate (core.js:11597)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.get (core.js:11414)
    at injectInjectorOnly (core.js:822)
    at ɵɵinject (core.js:827)

**Comment by scttcper** [comment]
What’s in package.json

**Comment by astrO1** [comment]
Here

{
  "name": "menap",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.2",
    "@angular/cdk": "^9.2.1",
    "@angular/common": "~9.1.2",
    "@angular/compiler": "~9.1.2",
    "@angular/core": "~9.1.2",
    "@angular/forms": "~9.1.2",
    "@angular/http": "~7.2.16",
    "@angular/material": "^9.2.1",
    "@angular/platform-browser": "~9.1.2",
    "@angular/platform-browser-dynamic": "~9.1.2",
    "@angular/router": "~9.1.2",
    "@ngx-loading-bar/core": "^4.2.0",
    "angular-confirmation-popover": "^5.0.0",
    "angular2-text-mask": "^9.0.0",
    "browserslist": "^4.11.1",
    "caniuse-lite": "^1.0.30001043",
    "core-js": "^3.6.5",
    "crypto-js": "^4.0.0",
    "datatables.net": "^1.10.20",
    "firebase": "^7.14.1",
    "idlejs": "^2.1.0",
    "jquery": "^3.5.0",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "muuri": "^0.8.0",
    "ngx-auth": "^5.3.0",
    "ngx-cookie-service": "^3.0.4",
    "ngx-currency": "^2.3.2",
    "ngx-dropzone": "^2.2.2",
    "ngx-lightbox": "^2.1.2",
    "ngx-loading": "^8.0.0",
    "ngx-material-timepicker": "^5.5.1",
    "ngx-spinner": "^9.0.2",
    "ngx-toastr": "^12.0.1",
    "ngx-ui-loader": "^9.1.1",
    "node-sass": "^4.13.1",
    "popper.js": "^1.16.1",
    "rxjs": "~6.5.5",
    "sweetalert2": "^9.10.12",
    "text-mask-addons": "^3.8.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.1",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.2",
    "@angular/language-service": "~9.1.2",
    "@types/jasmine": "~3.5.10",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "~13.13.0",
    "codelyzer": "~5.2.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.1",
    "karma": "~5.0.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "~3.1.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "^5.4.4",
    "ts-node": "~8.8.2",
    "tslint": "~6.1.1",
    "typescript": "~3.8.3"
  }
}

**Comment by scttcper** [comment]
I would try removing your node_modules folder and package-lock.json and reinstalling

**Comment by fabianedl777** [comment]
I have the same problem; I am using ngx toastr for error handler in the shared module. This problem appeared when update angular from 8 to 9.

**Comment by williamdes** [comment]
@fabianedl777 I hope this will help you https://github.com/scttcper/ngx-toastr/issues/804#issuecomment-619987359
