### ISSUE TITLE
 ERROR in ../node_modules/ngx-toastr/portal/portal.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.  26     get isAttached(): boolean;

### ISSUE THREAD

**Issue by nyarilokak** [scttcper/ngx-toastr#803]
ERROR in ../node_modules/ngx-toastr/portal/portal.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.

get isAttached(): boolean;

**Comment by scttcper** [comment]
Are you using the right version for the version of angular you are using. What’s in package.json

**Comment by adityadi98** [comment]
I had this issue.. with `"ngx-toastr": "^13.0.0",`

This solved it
https://stackoverflow.com/questions/60281234/node-modules-ngx-toastr-toastr-toast-noanimation-component-d-ts19-9

**Comment by nishant-zartek** [comment]
please install the appropriate version according to angular version
