### ISSUE TITLE
Incompatible with Ivy

### ISSUE THREAD

**Issue by pmullot** [scttcper/ngx-toastr#806]
This is the error message I get after including the library in the core module:

ERROR in node_modules/ngx-toastr/toastr/toastr.module.d.ts:4:22 - error NG6002: Appears in the NgModule.imports of CoreModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ngx-toastr) which declares ToastrModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by edy-ap** [comment]
This likely means that the library (ngx-toastr) which declares ToastrModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

**Comment by edy-ap** [comment]
Its works for me

**Comment by scttcper** [comment]
I think most people have been using ngx-toastr with ivy

**Comment by pmullot** [comment]
Yes,
This is a mystery one. I uninstalled and installed again and the problem
vanished
Sorry not to have closed the issue in github

**Comment by dkruchok** [comment]
I run into the same issue first.

The problem that VS Code imported modul like this:
`import { ToastrModule } from 'ngx-toastr/toastr/toastr.module'; <--- wrong` 

instead of the correct one:
`import { ToastrModule } from 'ngx-toastr'; <--- correct`

I hope it will help someone.
