### ISSUE TITLE
Same toastrId inside for of

### ISSUE THREAD

**Issue by vaiulian** [scttcper/ngx-toastr#822]
Hi

so i'm having this code right here (super simplified it):

	
	for (const item of this.listOfItems) {
      	this.toastrManageCurrentItem(item);
    }

	toastrManageCurrentItem = (item) => {

    const toastr = this.toastrService
      .error(
        this.translateService.instant('healthcheck.toastr_error_message'),
        this.translateService.instant('healthcheck.toastr_error_title', { item }),
        { disableTimeOut: true }
      );

      toastr.onTap.subscribe(() =>  {
        this.removeToastrForCurrentItem(toastr.toastId)
      });
	}

 Now, my problem is that i get back the same `toastr.toastId` for multiple different items inside `this.listOfItems`

Am i doing something wrong? it there something i'm not seeing?

Thanks.

**Comment by vaiulian** [comment]
ok, so preventDuplicates checks only for message, not taking into account the title, that is different on my example

i can see this MR https://github.com/scttcper/ngx-toastr/issues/659 that will fix it, any news on this?

i can't add preventDuplicates to my forRoot because it will mess things up on different parts of my application

**Comment by scttcper** [comment]
there's a new duplicate option
