### ISSUE TITLE
How to get toast Id?

### ISSUE THREAD

**Issue by aks7665** [scttcper/ngx-toastr#824]
I not able to find out how to get toastId. That is unique and mentioned in the document.
What i want is that i want to show a toast with disable timeout and it will be clear from screen when i hit to remove that specific toast. Is there any way?
I know we can do that with toast id but i don't know how to get toast id.

I have also another question.
And is it also possible to assign a random unique toastId to the toast? That id will be created by me.

**Comment by yarrgh** [comment]
When you use the `ToastrService` to show a toast, it returns an `ActiveToast`. `ActiveToast` contains a property called `toastId`

**Comment by julmot** [comment]
```typescript
const toast = this.toastr.success(...);
console.log(toast.toastId);
```
