### ISSUE TITLE
'NullInjectorError: No provider for ToastrService'

### ISSUE THREAD

**Issue by stevenxi** [scttcper/ngx-toastr#842]
The problem happens in version 13.0.0
After following the instruction, imports ToastrModule.forRoot() in the MainModule,  application gives 'NullInjectorError: No provider for ToastrService' error. 
Even if add ToastrService to the provider, it gives no provider for Overlay error. 
And then OverlayModule.

Issue gone after downgrade to 12.1.0

**Comment by scttcper** [comment]
what else is in your package.json

**Comment by stevenxi** [comment]
'''

"@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/google-maps": "^10.0.2",
    "@angular/http": "^7.2.15",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@fullcalendar/angular": "^4.4.2",
    "@fullcalendar/core": "^4.4.2",
    "@fullcalendar/daygrid": "^4.4.2",
    "@fullcalendar/interaction": "^4.4.2",
    "@fullcalendar/timegrid": "^4.4.2",
    "@types/date-fns": "^2.6.0",
    "@udintel/material": "0.0.37",
    "angular2-markdown": "^2.2.3",
    "angular2-text-mask": "^9.0.0",
    "bootstrap": "^4.4.1",
    "core-js": "^2.5.4",
    "file-saver": "^2.0.2",
    "font-awesome": "^4.7.0",
    "guid-typescript": "^1.0.9",
    "jquery": "^3.4.1",
    "ngx-dropzone-wrapper": "^9.0.0",
    "ngx-file-drop": "^8.0.8",
    "ngx-infinite-scroll": "^8.0.1",
    "ngx-malihu-scrollbar": "^7.0.0",
    "ngx-mat-select-search": "^2.1.2",
    "ngx-summernote": "^0.7.7",
    "ngx-toastr": "^12.1.0",
    "please-wait": "0.0.5",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.4.0",
    "simple-breakpoints": "^1.1.3",
    "spinkit": "^1.2.5",
    "stacktrace-js": "^2.0.2",
    "summernote": "^0.8.18",
    "text-mask-addons": "^3.8.0",
    "time-ago-pipe": "^1.3.2",
    "tslib": "^1.11.1",
    "vanilla-text-mask": "^5.1.1",
    "zone.js": "~0.8.26"

'''

And I believe I'm not the only one experiencing this.  There's another sample on Stackoverflow, but that case only happens in a prod build:  https://stackoverflow.com/questions/63360638/nullinjectorerror-no-provider-for-overlay-ngxtoastr

**Comment by scttcper** [comment]
latest version requires angular 10 https://github.com/scttcper/ngx-toastr#dependencies

**Comment by stevenxi** [comment]
Actually this issue still exist even after downgrade.

Very strange that it works well in dev build. but after switch to prod build, getting "NullInjectorError: No provider for ToastrService" error.
