### ISSUE TITLE
countDuplicates doesn't work if there is no title

### ISSUE THREAD

**Issue by jonatancompiani** [scttcper/ngx-toastr#846]
It could be useful to have the count for messages with no title.

As of now I am forced to either show duplicate messages, or just keep showing the same message in response of user actions.

![image](https://user-images.githubusercontent.com/15322453/91663460-52fa2600-eabf-11ea-9298-011ac35ffa11.png)

**Comment by scttcper** [comment]
should work with the new duplicate option
