### ISSUE TITLE
ERROR in Symbol Toast declared

### ISSUE THREAD

**Issue by picninim** [scttcper/ngx-toastr#851]
Toastr 13.0.0 has an issue with ng10x compiler

ERROR in Symbol Toast declared in .../node_modules/ngx-toastr/toastr/toast.component.d.ts is not exported from ngx-toastr/toastr/toastr.module (import into .../src/app/app.component.ts)

Project deps version:
`"dependencies": {
    "@angular/animations": "~10.0.9",
    "@angular/cdk": "^10.1.3",
    "@angular/common": "~10.0.9",
    "@angular/compiler": "~10.0.9",
    "@angular/core": "~10.0.9",
    "@angular/forms": "~10.0.9",
    "@angular/material": "^10.1.3",
    "@angular/platform-browser": "~10.0.9",
    "@angular/platform-browser-dynamic": "~10.0.9",
    "@angular/router": "~10.0.9",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "angular-svg-icon": "^10.0.0",
    "ng5-slider": "^1.2.4",
    "ngx-mask": "^10.0.1",
    "ngx-toastr": "13.0.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  }`

**Comment by scttcper** [comment]
i would try removing your node_modules folder

**Comment by roddc** [comment]
I also have this problem, have you fixed it? I tried to remove node_modules and reinstalled, it still doesn't work.

**Comment by adelabd** [comment]
I have the same error. 
Have you fixed it ?

**Comment by ramesh-peopletech** [comment]
I too facing same issue. can someone help ?

**Comment by Chris380** [comment]
I had the same issue. In my case the auto import by VS Code `import { ToastrModule } from 'ngx-toastr/toastr/toastr.module';` caused the issue. Just changed it to `import { ToastrModule } from 'ngx-toastr';`.

**Comment by karanrane96** [comment]
@Chris380  has given the solution. VS Code auto imports to import { ToastrModule } from 'ngx-toastr/toastr/toastr.module';
Just change it to import { ToastrModule } from 'ngx-toastr'; and you're good to go.
