### ISSUE TITLE
NullInjectorError: No provider for ToastrService! in angular8.3.7

### ISSUE THREAD

**Issue by thedevankit** [scttcper/ngx-toastr#852]
StaticInjectorError(AppModule)[HomeComponent -> ToastrService]: 
  StaticInjectorError(Platform: core)[HomeComponent -> ToastrService]: 
    NullInjectorError: No provider for ToastrService!

![image](https://user-images.githubusercontent.com/17850047/92915145-e9c4cc00-f449-11ea-8940-08a355975bb8.png)

While working on lazy loading.

Is anyone know to to ket resolved this error.

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr#dependencies
