### ISSUE TITLE
The toas does not appear

### ISSUE THREAD

**Issue by Lesnier** [scttcper/ngx-toastr#853]
I put the fallow:

**In app.module.ts:**
.....

	imports: [
		RouterModule,
		BrowserModule,
		AppRoutingModule,
		FormsModule,
		HttpClientModule,
		SlickCarouselModule,
		BrowserAnimationsModule,
		ToastrModule.forRoot({
			timeOut: 10000,
			positionClass: 'toast-bottom-right',
			preventDuplicates: true,
		}),
	],
...........

In **content.component.ts**
.............
import { ToastrService } from 'ngx-toastr';

	addCartProduct(producto) {
		this.cartPresenter.inserProductEnCarrito(producto.id);
		let texProductDetail = producto.name + ' - $' + producto.precio_now;
		this.showSuccess('Added to cart', 'texProductDetail');
	}

	showSuccess(title, message) {		
		this.toastr.success(title, message);
	}

**Comment by vishnu-dev** [comment]
Does your constructor in `content.component.ts` have,
```
constructor(
    private toastr: ToastrService
): {}
```

**Comment by SergioComputerx** [comment]
here the solution was  @import "../node_modules/ngx-toastr/toastr.css" in styles.scss
