### ISSUE TITLE
Progressbar?

### ISSUE THREAD

**Issue by bjorntj** [scttcper/ngx-toastr#854]
Trying to use toastr with progressbar but I can not see any progressbar, shouldn't I?

I am using the following code:

`let toast = this.toastr.show('Waiting for the results...', '', { timeOut: 1000000, progressBar: true, progressAnimation: "increasing", tapToDismiss: false });`

**Comment by bjorntj** [comment]
Never mind, was the black color that was the reason...

**Comment by tayambamwanza** [comment]
Actually, is there anyway to change the progress bars color?

**Comment by jackz7** [comment]
yes! you can change the progress bar color using css file as follow

```
.toast-progress {
  position: absolute;
  left: 0;
  bottom: 0;
  height: 4px;
  background-color: #fff;
  opacity: 0.4;
}
```
