### ISSUE TITLE
ngx-toastr 12.1.0

### ISSUE THREAD

**Issue by dpapini** [scttcper/ngx-toastr#860]
Hi i've insalled angular 9.1.4 and i try to use ngx-toast 12.1.0, but after installed, when compiled my project with ng serve, i've the follo error:

ERROR in node_modules/ngx-toastr/toastr/toast-noanimation.component.d.ts:49:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-toastr/toastr/toast-noanimation.component) which declares ToastNoAnimationModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

49 export declare class ToastNoAnimationModule {

can you help me?

**Comment by scttcper** [comment]
Do you have `@angular/animations` installed. Whats in your package.json

**Comment by dpapini** [comment]
No i don’t install animation. I use noanimationmodule. 
 What version I need install ?

**Comment by scttcper** [comment]
It only needs the types from `angular/animations` to typecheck. You should use the same version as your `angular/core`

**Comment by dpapini** [comment]
Ok I need install animation even if I don’t use?

**Comment by scttcper** [comment]
yes

**Comment by dpapini** [comment]
ok thank you, now it works.
you can close the issue
