### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by aayushikumar-schoyo** [scttcper/ngx-toastr#861]
I am using the latest version of ngx-toastr it seems to throw an error 

> ERROR in node_modules/ngx-toastr/portal/portal.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.
>     node_modules/ngx-toastr/toastr/toast-noanimation.component.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
>     node_modules/ngx-toastr/toastr/toast.component.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.

I can't fall back to the version, if I do so it asks me to downsize another npm version which in return downsize the whole project version. 

Can someone Help me with the issue.

**Comment by scttcper** [comment]
what is your package.json, make sure you followed https://github.com/scttcper/ngx-toastr#dependencies

**Comment by tiramon** [comment]
just had the same error messages, for be the problem was that i installed toastr v13 with angular 8 after i downgraded toastr to v11 it worked
