### ISSUE TITLE
using a custom toast component and toast message is duplicate showing

### ISSUE THREAD

**Issue by koshtiankit** [scttcper/ngx-toastr#862]
-  i am  using the **Angular 8** and  **"ngx-toastr": "^11.3.3",** 
- using the custom toast component toast is duplicating and showing, i've  also added the 
`preventDuplicates and maxOpened` but nothing is worked for me to prevent duplication toaster

as shown in the documentation in the global configuration ,
```
ToastrModule.forRoot({
      preventDuplicates: true,
      maxOpened: 1,
      toastComponent: AlertComponent,
    }),
```

please help me to fix and add the comment  if anyone faced and fixed the same issue !

**Comment by koshtiankit** [comment]
@scttcper Please help me to fix this issue  !

**Comment by koshtiankit** [comment]
@HarikumarG @domisginger Please help me fix this bug !

**Comment by domisginger** [comment]
@koshtiankit you would need to provide an example of the toast your dislpaying or share a minumum projcect with the error reproducable. This is less of an issue reported and more a stackoverflow question.

**Comment by koshtiankit** [comment]
It is fixed .. After investigate full though it has other dependency of code issues and it is fixed now 

Thanks @domisginger for you time !

**Comment by koshtiankit** [comment]
i am closing the issue as it is fixed for me !
