### ISSUE TITLE
Using ngx-toastr

### ISSUE THREAD

**Issue by edenfisher** [scttcper/ngx-toastr#875]
Hello,

We are using ngx-toastr in our application and It was working great.
Recently we have decided to start managing our Angular application change detection manually. Therefore we also stopped using NgZone(Using the dummy - { ngZone: 'noop' }).
Unfortunately toastr is not working well with that configuration and showing something like that:
![image](https://user-images.githubusercontent.com/13810807/105979082-eef28280-609b-11eb-8ea6-8f1d0c15da8c.png)
(Not rendering the toastr well)

Does anybody have any input on how we can solve that?
Thank you

**Comment by rafialikhan** [comment]
I have the same issue, I have also turned off change detection using ngZone: 'noop' to create angular elements. @edenfisher - did you manage to crack this.

**Comment by nikunjkonduru** [comment]
@rafialikhan I am trying to do the same with Angular Elements. Have you figured out a way to make it work as a web component?
