### ISSUE TITLE
ngx-toastr still not compadable with ivy

### ISSUE THREAD

**Issue by kevin192291** [scttcper/ngx-toastr#876]
new install of angular, (v11)
New project,
first package installed was ngx-toastr and I get the error:
`This likely means that the library (ngx-toastr) which declares ToastNoAnimation has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`
Has anyone found a fix for this? I haven't found anything from searching issues.

**Comment by Shadowsith** [comment]
@kevin192291 my workaround for ivy incompatible packages:
 ```json
"scripts": {
     "postinstall": "ngcc --properties es2015 es5 browser module main --first-only --create-ivy-entry-points"
}
```

**Comment by cybercussion** [comment]
Is this also possible why when updating to Angular 12 I'm getting:
```
/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDef'.
78     static ɵfac: ɵngcc0.ɵɵFactoryDef<ToastrService, never>;
```

**Comment by scttcper** [comment]
Released a new version for v12
