### ISSUE TITLE
ngx-toastr changing angular template view infinite time

### ISSUE THREAD

**Issue by himanshubudhlakoti** [scttcper/ngx-toastr#883]
Hi,
i have been using ngx-toastr since last 4 years no doubt it is superb NPM module --
But today when i called a function from my template it is called infinite times after execution of " **this.toastr.success("Added Sussessfully")"** the statement --
i have cross-checked many times it is only because of ngx.toastr

when the statement **"this.toastr.success("Added Sussessfully");"**  OR **"this.toastr.error("Failed!");"** is executed 
in a .ts file of component then view of that components template runs/changes for infinite times and browser is down at the same time

i am attaching code what i have used --

**app.module.ts**
import { ToastrModule } from 'ngx-toastr';
import { ToastrService } from 'ngx-toastr';

@NgModule({
   imports:[ToastrModule.forRoot({
      positionClass: 'toast-top-right',
      preventDuplicates: true,
      progressBar: true,
      closeButton: true
    })],
   providers:[ToastrService ]

})

**login.html**
`<form>`
`<input type="text" />`
`<span> {{getMsg()}} </span>`
`<button type="button"(click)="submitForm()">Submit</button>`
`</form>`

**login.ts**
import { ToastrService } from 'ngx-toastr';

constructor(    private toastr: ToastrService){}

public submitForm():void{
  **this.toastr.success("Added Sussessfully");**// after execution of this statement templates changes its view infinite times
}

getMsg():string{
    console.log("********Hey, i am called ********)
}
**so now when i click on submit button then submitForm() function is executed and and toastr statement as well and after that** **getMsg() function from template is executed for infinite times because template is changing its view continuously**
so in my browser's console "Hey, i am called" is displayed for infinite times and its count continuously increased this means that the login template changing its view  continuously that's why getMsg() function called continuously.

and it happens only after execution of **this.toastr.success("Added Sussessfully");**
if i remove this toastr statement from submitForm() function of my login.ts file then view is changed normally for 50times that is ok but and if keep the **this.toastr.success("Added Sussessfully");** statement and after only execution of this line view of 
login.html template is changed for infinite times and getMsg() function is called again n again...

Please help me out, i am putting issue here after full of my research.
Thanks

**Comment by himanshubudhlakoti** [comment]
login.html
`<div>
  <input type="text" placeholder="Enter email">
  **<span>{{ getMsg() }}</span>**
  <button (click)="submitForm()">Submit</button>
</div>`

**Comment by scttcper** [comment]
if you are importing `ToastrModule` you do not need to re-declare `ToastrService`. You likely have two instances.

**Comment by Pledje** [comment]
Hi,
followed the same, but issue did not resolved.
Can you please let me know what is the exact issue
