### ISSUE TITLE
Is it possible to use only the logic and use our own css 

### ISSUE THREAD

**Issue by SinghChandrabhan** [scttcper/ngx-toastr#889]
So let say you have various type of toasts/snackbar in your application and then you only want to use the core logic from ngx-toastr with your own CSS.HTML.
For exaple  I have below kind of toasts(and many more) or notification:

![image](https://user-images.githubusercontent.com/20701328/121678785-e5e8d780-cab7-11eb-9530-4bbbf6ca3585.png)

How can we achive this?

**Comment by scttcper** [comment]
you would need to use a custom toast for undo/dismiss buttons but everything else can be done with css

**Comment by SinghChandrabhan** [comment]
@scttcper  thanks will give it a try
