### ISSUE TITLE
Angular 13

### ISSUE THREAD

**Issue by destus90** [scttcper/ngx-toastr#910]
Please update your library peer deps in order to support the newest version of Angular. It doesn't have lots of breaking changes, so the update should be smooth.

https://github.com/angular/angular/blob/master/CHANGELOG.md#1300-2021-11-03

**Comment by damingerdai** [comment]
it is a breaking changes because of ivy

**Comment by muhammadawaisshaikh** [comment]
I want to take over this task. please assign it to me
