### ISSUE TITLE
Errors related to ngx-toastr after doing npm install 

### ISSUE THREAD

**Issue by neerajk22** [scttcper/ngx-toastr#915]
Errors related to ngx-toastr after doing npm install 
While running application - npm run start

Error: ./node_modules/ngx-toastr/fesm2015/ngx-toastr.mjs 137:4-17
Can't import the named export 'ɵɵtemplate' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-toastr/fesm2015/ngx-toastr.mjs 113:4-13
Can't import the named export 'ɵɵtext' from non EcmaScript module (only default export is available)

Error: ./node_modules/ngx-toastr/fesm2015/ngx-toastr.mjs 84:4-25
Can't import the named export 'ɵɵtextInterpolate1' from non EcmaScript module (only default export is available)

**Comment by scttcper** [comment]
what version of angular and angular cli

**Comment by JRafael91** [comment]
Same errors, i had the version installed 14.1.3, i have installed version 11 of angular,
the solution was to install ngx-toastr 13.2.1.

![image](https://user-images.githubusercontent.com/39107286/141872511-95c472e2-bc7e-4f12-bad6-10e832862e15.png)

**Comment by neerajk22** [comment]
> 13.2.1

yup it worked after using version 13.2.1

**Comment by sherifalaa55** [comment]
issue still happening on version 14.2

I had to revert to 14.1.4

**Comment by Bezlepkin** [comment]
same issue. Angular 12.2.4

**Comment by szahn** [comment]
Still getting this issue

**Comment by Bezlepkin** [comment]
If you need a simple library with notifications, I can upload my library to npm. This library didn't work, I had to make my own :)

**Comment by JRafael91** [comment]
check the version of nodejs, to angular 12, the node version should be v14.

ref: https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3#file-angular-cli-node-js-typescript-rxjs-compatiblity-matrix-csv

**Comment by mahmmoudkinawy** [comment]
- The following solution gonna make it work!!
npm install ngx-toastr --save --force

**Comment by EnoRich88** [comment]
thanks alot, it works

**Comment by EnoRich88** [comment]
> * The following solution gonna make it work!!
>   npm install ngx-toastr --save --force

thanks alot, it works

**Comment by mokhtaarr** [comment]
i have same problem and use npm install ngx-toastr --save --force .. and this error come to me 
Error: ../node_modules/ngx-toastr/toastr/toast-injector.d.ts:47:5 - error TS2416: Property 'get' in type 'ToastInjector' is not assignable to the same property in base type 'Injector'.
  Type '<T>(token: any, notFoundValue?: T | undefined, flags?: InjectFlags | undefined) => T | ToastPackage' is not assignable to type '{ <T>(token: ProviderToken<T>, notFoundValue: undefined, options: InjectOptions & { optional?: false | undefined; }): T; <T>(token: ProviderToken<T>, notFoundValue: null | 
undefined, options: InjectOptions): T | null; <T>(token: ProviderToken<...>, notFoundValue?: T | undefined, options?: InjectOptions | ... 1 more ...'.    
    Types of parameters 'flags' and 'options' are incompatible.
      Type 'InjectOptions & { optional?: false | undefined; }' is not assignable to type 'InjectFlags | undefined'.

**Comment by dlp140** [comment]
> i have same problem and use npm install ngx-toastr --save --force .. and this error come to me Error: ../node_modules/ngx-toastr/toastr/toast-injector.d.ts:47:5 - error TS2416: Property 'get' in type 'ToastInjector' is not assignable to the same property in base type 'Injector'. Type '(token: any, notFoundValue?: T | undefined, flags?: InjectFlags | undefined) => T | ToastPackage' is not assignable to type '{ (token: ProviderToken, notFoundValue: undefined, options: InjectOptions & { optional?: false | undefined; }): T; (token: ProviderToken, notFoundValue: null | undefined, options: InjectOptions): T | null; (token: ProviderToken<...>, notFoundValue?: T | undefined, options?: InjectOptions | ... 1 more ...'. Types of parameters 'flags' and 'options' are incompatible. Type 'InjectOptions & { optional?: false | undefined; }' is not assignable to type 'InjectFlags | undefined'.

I am having this exact issue. Have you found a solution?

**Comment by fatimavb** [comment]
I have the same problem and i use npm install ngx-toastr --save --force. Version Angular: 15.0.0 -  ../node_modules/ngx-toastr/toastr/toast-injector.d.ts:47:5 - error TS2416: Property 'get' in type 'ToastInjector' is not assignable to the same property in base type 'Injector'. Type '(token: any, notFoundValue?: T | undefined, flags?: InjectFlags | undefined) => T | ToastPackage' is not assignable to type '{ (token: ProviderToken, notFoundValue: undefined, options: InjectOptions & { optional?: false | undefined; }): T; (token: ProviderToken, notFoundValue: null | undefined, options: InjectOptions): T | null; (token: ProviderToken<...>, notFoundValue?: T | undefined, options?: InjectOptions | ... 1 more ...'. Types of parameters 'flags' and 'options' are incompatible. Type 'InjectOptions & { optional?: false | undefined; }' is not assignable to type 'InjectFlags | undefined'.

Please, have you found a solution?

**Comment by BogdanZafiu** [comment]
adding "skipLibCheck":true in tsconfig.json worked for me

**Comment by Rabeb1998** [comment]
> j'ai le même problème et j'utilise npm install ngx-toastr --save --force .. et cette erreur me vient Erreur: ../node_modules/ngx-toastr/toastr/toast-injector.d.ts:47 :5 - erreur TS2416 : la propriété 'get' dans le type 'ToastInjector' n'est pas assignable à la même propriété dans le type de base 'Injector'. Tapez '(token : any, notFoundValue ? : T | undefined, flags ? : InjectFlags | undefined) => T | ToastPackage' n'est pas assignable au type '{ (token : ProviderToken, notFoundValue : undefined, options : InjectOptions & { optional ? : false | undefined; }): T ; (jeton : ProviderToken, notFoundValue : null | non défini, options : InjectOptions) : T | nul ;(token : ProviderToken<...>, notFoundValue ? : T | non défini, options ? : InjectOptions | ... 1 de plus ...'. Tapez 'InjectOptions & { facultatif ? : faux | indéfini; }' n'est pas assignable au type 'InjectFlags | indéfini'.

Pour résoudre cette erreur, vous pouvez accéder au fichier "node_modules/ngx-toastr/toastr/toast-injector.d.ts" et essayer de modifier la signature de la méthode 'get' dans la classe 'ToastInjector' pour correspondre à celle de la classe de base 'Injector'. Voici comment vous pouvez le faire: get<T>(token: any, notFoundValue?: T | undefined): T | ToastPackage;

**Comment by flaviamedici** [comment]
Adding "skipLibCheck":true in tsconfig.json also worked for me

**Comment by moon-web75** [comment]
I have same Problem using "ngx-toastr": "^14.3.0",

**Angular CLI: 15.2.11
Node: 16.20.2
Package Manager: npm 8.11.0
OS: win32 x64**

**Comment by shyamsandesh7** [comment]
> * The following solution gonna make it work!!
>   npm install ngx-toastr --save --force

Thanks it's working
