### ISSUE TITLE
Angular 13 sass issue

### ISSUE THREAD

**Issue by cybercussion** [scttcper/ngx-toastr#916]
Not sure whats causing this yet but in my styles.scss:
original: @import '~ngx-toastr/toastr-bs4-alert';
had to backup to: @import '../node_modules/ngx-toastr/toastr-bs4-alert';

Kept getting:
-- inner error --
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
    ╷
246 │ @import '~ngx-toastr/toastr-bs4-alert';

All the bootstrap includes work but this was the only hangup after upgrading.

**Comment by scttcper** [comment]
i think it might have been fixed in https://github.com/scttcper/ngx-toastr/releases/tag/v14.2.1

**Comment by cybercussion** [comment]
Indeed, that got it - thanks.
