### ISSUE TITLE
Not working in aot build

### ISSUE THREAD

**Issue by TianCNCA** [scttcper/ngx-toastr#92]
Hi, ngx-toastr seems to stop working in aot build. Toastrs don't show up.

Tested using angular-seed, build.prod.aot.

angular version: ~2.4.0
typescript: ~2.0.9

Anyone else been having this issue?
Thanks.

**Comment by yarrgh** [comment]
Just tested with @angular/cli with aot and it works fine for me.

```json
@angular/cli: 1.0.0-rc.2
node: 7.4.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/cli: 1.0.0-rc.2
@angular/compiler-cli: 2.4.9
```

which angular-seed are you using?

**Comment by yarrgh** [comment]
Also tried [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) with aot and it also is working.

**Comment by scttcper** [comment]
The demo is using AoT. Throw up a repo and we can check it out with you :+1:

**Comment by TianCNCA** [comment]
Hi, it's https://github.com/mgechev/angular-seed

**Comment by yarrgh** [comment]
Just tried it with the latest angular-seed. It was using Angular 4 RC 3 but I installed the latest ngx-toastr anyways (not ngx-toastr@next). 

In `tools/config/project.config.ts` I made sure to add the toastr.umd.js and reference the toastr.css

```typescript
    // ...

    // Add `local` third-party libraries to be injected/bundled.
    this.APP_ASSETS = [
      // {src: `${this.APP_SRC}/your-path-to-lib/libs/jquery-ui.js`, inject: true, vendor: false}
      // {src: `${this.CSS_SRC}/path-to-lib/test-lib.css`, inject: true, vendor: false},
      { src: 'node_modules/ngx-toastr/toastr.css', inject: true, vendor: false },
    ];

    // Add packages (e.g. ng2-translate)
    let additionalPackages: ExtendPackages[] = [
      {
        name: 'ngx-toastr',
        // Path to the package's bundle
        path: 'node_modules/ngx-toastr/toastr.umd.js'
      }
    ];

    this.addPackagesBundles(additionalPackages);

  // ...
```
And then the rest is exactly what is in the readme file. Add `ToastrModule.forRoot()` to the imports of the `AppModule` . I injected `ToastrService` into the `home.component.ts`, created a simple method to show a success toast, and then added a button to the html that calls that method when clicked. Running `npm start`, everything was working correctly.

I ran `npm run build.prod.aot`  and copied everything in the `dist/prod` folder to my local server. Page shows up and the toasts are showing up correctly.

For kicks, I even ran  `npm run build.prod.rollup.aot` and everything worked properly as well.

I wasn't able to duplicate what your experiencing. I'll go ahead and downgrade Angular to 2.4.9 and see if the result is any different.

**Comment by yarrgh** [comment]
Downgrading to Angular 2.4.10 didn't make a difference. Toasts are still working correctly. If you have your code in a repo, send us the link so that we can look at it with you.

**Comment by TianCNCA** [comment]
Hi,

In my case, the overlay-container div was created correctly when a toastr message is thrown, but the toast-container div inside it is always empty. Do you have any clue why it behaved like that?

Thanks,

**Comment by TianCNCA** [comment]
Unfortunately I'm experiencing this issue in our production environment so I can't post a repo. What I'm observing is that when I compile the code with AoT the  toast-container div isn't getting inserted with toaster divs when it should be. No errors are seen in the console.

**Comment by scttcper** [comment]
how are you triggering the alert? is ngx-toastr being loaded at the root of your application? Is anything being lazy loaded? thanks

**Comment by scttcper** [comment]
Also try setting 'onActivateTick: true' in your settings

**Comment by yarrgh** [comment]
scttcper brings up a good point. Are you trying to open a toast from an async process? If it happens to be outside of Angular's zone, Angular won't run change detection and it needs to be triggered mannually using `onActiveTick: true`

**Comment by TianCNCA** [comment]
Hi,

I load ngx-toastr in a service which is imported in the app.module.ts (the root module). It's used by the whole application.

Every feature module has their own routing module. I only have two lazy loading paths defined at the root level:
      {
        path: '',
        redirectTo: '/dailyapprovals',
        pathMatch: 'full'
      },
      { path: '**', component: PageNotFoundComponent }

I tried to set onActivateTick to true, but it didn't work.

**Comment by scttcper** [comment]
I don't have any more ideas. Can always try the latest version.
