### ISSUE TITLE
Closing hidden toast show more toasts than maxOpened allows

### ISSUE THREAD

**Issue by trpharove** [scttcper/ngx-toastr#922]
My global settings are

```ts
ToastrModule.forRoot({
	newestOnTop: false,
	tapToDismiss: true,
	positionClass: 'toast-bottom-right',
	maxOpened: 5
}),
```

I made a bit of code to store all the generated toasts with a given key, for example for a warning :

```ts
const activeToast = this._toastManager.warning(content, title, { disableTimeOut: true });
activeToast.onHidden.pipe(take(1)).subscribe(() => this._toastMap.delete(key));
this._toastMap.set(key, activeToast);
```
in order to be able to remove a toast without the need to manually click on it using the key, like so :

```ts
this._toastManager.remove(this._toastMap.get(key).toastId);
this._toastMap.delete(key);
```

Mainly to allow a toast to be closed on a user action, like solving the reason the toast was added to the queue.

Right now, when I clear a toast that is not currently shown to the screen it (wrongly?) reduces the amount of currentlyActive toasts, causing the amount of toasts on screen to go above the maxOpened value.

**Comment by TimJ0212** [comment]
Hello, first-time contributor here. I looked in the code and found the problem. In the `toastr.service.ts` the remove function reduce the number of current  active toasts before testing if the toast even is active. I opened a PR.
