### ISSUE TITLE
ERROR TypeError: Cannot read properties of undefined (reading 'toastId')

### ISSUE THREAD

**Issue by GregoireLgt** [scttcper/ngx-toastr#928]
Using the last version of the package (14.2.3), i am having this error : 

![image](https://user-images.githubusercontent.com/47480030/162401543-3b3ce8e0-94a8-40e8-92a3-3487cd432027.png)

Works fine in 14.2.2

**Comment by optimistex** [comment]
I confirm the same error!

On PROD:
![image](https://user-images.githubusercontent.com/11228640/162898028-08ae3f1e-f480-4076-9484-f6c0e5bda0a0.png)


On DEV:
![image](https://user-images.githubusercontent.com/11228640/162898246-71afddf2-0ab8-4595-a7fb-26e536fe75ce.png)

package.json: 
```
"ngx-toastr": "^14.1.0",
```
package-lock.json: 
```
    "ngx-toastr": {
      "version": "14.2.3",
      "resolved": "https://registry.npmjs.org/ngx-toastr/-/ngx-toastr-14.2.3.tgz",
      "integrity": "sha512-vFQqDikI6elnNq2b0LJzMUFlKcHTQsgjk8ImibHbr2jvSHdSS7oCWaDoxwFcqDCqyFIt3+qYKy8K3aY47kaZRA==",
      "requires": {
        "tslib": "^2.3.0"
      }
    },
```
