### ISSUE TITLE
NullInjectorError: No provider for ToastPackage!

### ISSUE THREAD

**Issue by amarshilpakar** [scttcper/ngx-toastr#935]
I am using ngx-toastr in my application and while running unit test I am getting following errror

```
NullInjectorError: R3InjectorError(DynamicTestModule)[ToastPackage -> ToastPackage]: 
          NullInjectorError: No provider for ToastPackage!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'ToastPackage', 'ToastPackage' ] })
        NullInjectorError: R3InjectorError(DynamicTestModule)[ToastPackage -> ToastPackage]: 
          NullInjectorError: No provider for ToastPackage!

        Error: Expected undefined to be truthy.
            at <Jasmine>
            at UserContext.<anonymous> (src/app/modules/nxg-widgets/nxg-toast/nxg-toast-content/nxg-toast-content.component.spec.ts:33:23)
            at ZoneDelegate.invoke (node_modules/zone.js/fesm2015/zone.js:372:1)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/fesm2015/zone-testing.js:287:1)
```

**Comment by amarshilpakar** [comment]
@scttcper any idea?

**Comment by tanzeelrana** [comment]
![Screen Shot 2022-06-11 at 1 22 53 PM](https://user-images.githubusercontent.com/2520028/173198160-738aab3d-2586-4adb-98c6-a1cd5785d714.png)

**Comment by BanhakeiaMhamed** [comment]
npm install ngx-toastr --save, then Import your ToastrModule in app.module.ts

**Comment by Pascalmh** [comment]
@scttcper I get this error as well again after upgrading to v17 (using angular 16) - here is a reproduction: 

https://stackblitz.com/edit/angular-q7zvst?file=src/main.ts

**Comment by scttcper** [comment]
@Pascalmh your problem is different fixed in https://github.com/scttcper/ngx-toastr/releases/tag/v17.0.2
