### ISSUE TITLE
Erro no import { ModuleWithProviders } from '@angular/compiler/src/core';

### ISSUE THREAD

**Issue by WandersonRber** [scttcper/ngx-toastr#960]
Error: src/app/app.module.ts:10:37 - error TS2307: Cannot find module '@angular/compiler/src/core' or its corresponding type declarations.       

10 import { ModuleWithProviders } from '@angular/compiler/src/core';
                                                                   ~~~~~~~~~~~~~~~~~~~~
![app module ts - CursoAngularREST - Visual Studio Code 14_11_2022 19_14_06](https://user-images.githubusercontent.com/87829513/201779664-631c1dad-5ff5-4c5b-877c-da31b31b3aa2.png)

**Comment by scttcper** [comment]
what does this have to do with ngx-toastr
