### ISSUE TITLE
Error with ngx-toastr and Angular 14

### ISSUE THREAD

**Issue by dmccolloughOneGas** [scttcper/ngx-toastr#971]
I created a new angular 14 project.

I added the package for ngx-toastr.

I referenced the css file in my angular.json file

I added the ToastrModule to my app.module.ts like this
  imports: [
    CommonModule,
    BrowserAnimationsModule, // required animations module
    ToastrModule.forRoot(), // ToastrModule added
  ],

after a npm install
I did a ng serve and I'm getting this error message

Error: node_modules/ngx-toastr/toastr/toast-noanimation.component.d.ts:50:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

50     static ɵcmp: i0.ɵɵComponentDeclaration<ToastNoAnimation, "[toast-component]", never, {}, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-toastr/toastr/toast.component.d.ts:57:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

57     static ɵcmp: i0.ɵɵComponentDeclaration<Toast, "[toast-component]", never, {}, {}, never, never, false, never>;
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/ngx-toastr/toastr/toast.directive.d.ts:8:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

8     static ɵdir: i0.ɵɵDirectiveDeclaration<ToastContainerDirective, "[toastContainer]", ["toastContainer"], {}, {}, never, never, false, never>;

This is a new blank angular app using Angular 14, all I've done so far is just add the package and do the configuration per the docs.

How do I fix this ?

**Comment by scttcper** [comment]
use the correct version for angular 14 https://github.com/scttcper/ngx-toastr#dependencies

**Comment by dmccolloughOneGas** [comment]
@scttcper  I just found that. The readme on the npm page is incorrect. https://www.npmjs.com/package/ngx-toastr
