### ISSUE TITLE
Can't resolve '~ngx-toastr/toastr.css'

### ISSUE THREAD

**Issue by changhuixu** [scttcper/ngx-toastr#976]
Related to #964 

So, before v16, we can add `@import '~ngx-toastr/toastr.css';` to the global `styles.css` file. But not now. I tried to add `"node_modules/ngx-toastr/toastr.css"` to the `angular.json` file. It works in that way.
However, we prefer to use `styles.css`  instead of touching `angular.json`, which is mostly angular stuff, while `styles.css` is our project related.

I guess the breaking change is in the v16.0.0 release bc776777a2a5e519486cf7049e0c4320d41b61f6 removed the `~` in front of bootstrap.
Not sure about the reasoning.

**Comment by scttcper** [comment]
Try without the ~

**Comment by changhuixu** [comment]
Removing the `~` doesn't work either. 
![image](https://user-images.githubusercontent.com/16184464/216772421-492c789d-91fa-43fc-93ed-2ca24c2b2ca6.png)

However, `@import 'bootstrap/dist/css/bootstrap.min.css';` works without the `~`.

**Comment by changhuixu** [comment]
@scttcper Any thoughts? Or estimated timeline? Thank you.

**Comment by scttcper** [comment]
no idea

**Comment by changhuixu** [comment]
Just for people who stumble into this problem in the future: my solution is to remove the package `ngx-toastr`, and use `ng-bootstrap` instead.

`ng-bootstrap` has many useful Bootstrap components, including `toast` module.

https://ng-bootstrap.github.io/#/components/toast/overview

**Comment by temush** [comment]
I also faced the issue

@scttcper The issue could be resolved if you explicitly add "toastr.css" export (beside "toastr") to the package.json
