### ISSUE TITLE
After upgrading to angular 15 from 14 not able to run project give error in class => toast-injector.d.ts 

### ISSUE THREAD

**Issue by ManiyarIrfan** [scttcper/ngx-toastr#977]
Code 

`/** Custom injector type specifically for instantiating components with a toast. */
export declare class ToastInjector implements Injector {
    private _toastPackage;
    private _parentInjector;
    constructor(_toastPackage: ToastPackage, _parentInjector: Injector);
    get<T>(token: any, notFoundValue?: T, flags?: InjectFlags): T | ToastPackage;
}`

Error on mouse over :
Property 'get' in type 'ToastInjector' is not assignable to the same property in base type 'Injector'.
  Type '<T>(token: any, notFoundValue?: T | undefined, flags?: InjectFlags | undefined) => ToastPackage | T' is not assignable to type '{ <T>(token: ProviderToken<T>, notFoundValue: undefined, options: InjectOptions & { optional?: false | undefined; }): T; <T>(token: ProviderToken<T>, notFoundValue: null | undefined, options: InjectOptions): T | null; <T>(token: ProviderToken<...>, notFoundValue?: T | undefined, options?: InjectFlags | ... 1 more .....'.
    Types of parameters 'flags' and 'options' are incompatible.
      Type 'InjectOptions & { optional?: false | undefined; }' is not assignable to type 'InjectFlags | undefined'.ts(2416)

Error in termial 

```
 Type '<T>(token: any, notFoundValue?: T, flags?: InjectFlags) => T | ToastPackage' is not assignable to type '{ <T>(token: ProviderToken<T>, notFoundValue: undefined, options: InjectOptions & { optional?: false; }): T; <T>(token: ProviderToken<T>, notFoundValue: null, options: InjectOptions): T; <T>(token: ProviderToken<...>, notFoundValue?: T, options?: InjectFlags | InjectOptions): T; <T>(token: ProviderToken<...>, notFou...'.
    Types of parameters 'flags' and 'options' are incompatible.
      Type 'InjectOptions & { optional?: false; }' is not assignable to type 'InjectFlags'.
```

Woking Fine if I do changes in get<> line like below 

`get<T>(token: any, notFoundValue?: T): T | ToastPackage;`

![image](https://user-images.githubusercontent.com/87698037/217802776-de9c237e-a5e8-4f3f-b8d5-735bb133b5bd.png)

![image](https://user-images.githubusercontent.com/87698037/217802862-79bf8194-aa73-4aad-89a7-a15adafd50f9.png)

**Comment by sidsaxena0** [comment]
I am also getting this error, is there any other way without editing `toast-injector.d.ts ` because changes get lost as soon as I run `npm install`.

**Comment by scttcper** [comment]
make sure you're using the correct version

**Comment by ManiyarIrfan** [comment]
@sidsaxena0  After Updating toster to 16.0.2 working fine for me.
thanks @scttcper
