### ISSUE TITLE
Unable to install in Angular 15.x

### ISSUE THREAD

**Issue by northernfrontier** [scttcper/ngx-toastr#979]
Cannot install into a project that is using Angular 15.x. see attached reports and logs

[ngx-toastr-debug.log.txt](https://github.com/scttcper/ngx-toastr/files/10870312/ngx-toastr-debug.log.txt)
[ngx-toastr-install.txt](https://github.com/scttcper/ngx-toastr/files/10870313/ngx-toastr-install.txt)

**Comment by scttcper** [comment]
https://github.com/scttcper/ngx-toastr#dependencies

**Comment by northernfrontier** [comment]
I followed the dependencies and installed 
 @angular/animations@15.1.3 
as it is used elsewhere in my app

**Comment by northernfrontier** [comment]
trying a complete reinstall of all angular packages.

**Comment by northernfrontier** [comment]
complete update and reinstall fixed the issues.
