### ISSUE TITLE
Toaster notification not displayed

### ISSUE THREAD

**Issue by BanhakeiaMhamed** [scttcper/ngx-toastr#987]
I m using in my angular project toaster. I woud like to display notificatin when form data are not valid and the user clic on button register. 
i got in th console this : 
{toastId: 11, 
title: '', message: 'Veuillez à Entrer des données correctes',
 toastRef: ToastRef,
 onShown: Observable, …}
message: "Veuillez à Entrer des données correctes"
onAction: Observable {source: Subject}
onHidden: Observable {source: Subject}
onShown: Observable {source: Subject}
onTap: Observable {source: Subject}
portal: ComponentRef {location: ElementRef, _rootLView: Array(38), _tNode: {…},
 instance: Toast,
 changeDetectorRef: RootViewRef, …}
title: ""toastId: 11toastRef: ToastRef {_overlayRef: OverlayRef, duplicatesCount: 0, _afterClosed: Subject, _activate: Subject, _manualClose: Subject, …}[[Prototype]]: Object

**Comment by TobysNap** [comment]
Hello!
Did you managed to solve the issue you were facing? I would like to help!
